// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/spacemeshos/go-spacemesh/genvm/core (interfaces: Template)
//
// Generated by this command:
//
//	mockgen -typed -package=mocks -destination=./mocks/template.go github.com/spacemeshos/go-spacemesh/genvm/core Template
//

// Package mocks is a generated GoMock package.
package mocks

import (
	scale "github.com/spacemeshos/go-scale"
	core "github.com/spacemeshos/go-spacemesh/genvm/core"
	gomock "go.uber.org/mock/gomock"
)

// MockTemplate is a mock of Template interface.
type MockTemplate struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateMockRecorder
	isgomock struct{}
}

// MockTemplateMockRecorder is the mock recorder for MockTemplate.
type MockTemplateMockRecorder struct {
	mock *MockTemplate
}

// NewMockTemplate creates a new mock instance.
func NewMockTemplate(ctrl *gomock.Controller) *MockTemplate { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplate) EXPECT() *MockTemplateMockRecorder {
	_ = "STUB: not implemented"

	// BaseGas mocks base method.
	return nil
}

func (m *MockTemplate) BaseGas(arg0 uint8) uint64 { _ = "STUB: not implemented"; return 0 }

// BaseGas indicates an expected call of BaseGas.
func (mr *MockTemplateMockRecorder) BaseGas(arg0 any) *MockTemplateBaseGasCall {
	_ = "STUB: not implemented"
	return nil
}

// MockTemplateBaseGasCall wrap *gomock.Call
type MockTemplateBaseGasCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTemplateBaseGasCall) Return(arg0 uint64) *MockTemplateBaseGasCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockTemplateBaseGasCall) Do(f func(uint8) uint64) *MockTemplateBaseGasCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTemplateBaseGasCall) DoAndReturn(f func(uint8) uint64) *MockTemplateBaseGasCall {
	_ = "STUB: not implemented"
	return nil
}

// EncodeScale mocks base method.
func (m *MockTemplate) EncodeScale(enc *scale.Encoder) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// EncodeScale indicates an expected call of EncodeScale.
func (mr *MockTemplateMockRecorder) EncodeScale(enc any) *MockTemplateEncodeScaleCall {
	_ = "STUB: not implemented"
	return nil
}

// MockTemplateEncodeScaleCall wrap *gomock.Call
type MockTemplateEncodeScaleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTemplateEncodeScaleCall) Return(arg0 int, arg1 error) *MockTemplateEncodeScaleCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockTemplateEncodeScaleCall) Do(f func(*scale.Encoder) (int, error)) *MockTemplateEncodeScaleCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTemplateEncodeScaleCall) DoAndReturn(f func(*scale.Encoder) (int, error)) *MockTemplateEncodeScaleCall {
	_ = "STUB: not implemented"
	return nil
}

// ExecGas mocks base method.
func (m *MockTemplate) ExecGas(arg0 uint8) uint64 { _ = "STUB: not implemented"; return 0 }

// ExecGas indicates an expected call of ExecGas.
func (mr *MockTemplateMockRecorder) ExecGas(arg0 any) *MockTemplateExecGasCall {
	_ = "STUB: not implemented"
	return nil
}

// MockTemplateExecGasCall wrap *gomock.Call
type MockTemplateExecGasCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTemplateExecGasCall) Return(arg0 uint64) *MockTemplateExecGasCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockTemplateExecGasCall) Do(f func(uint8) uint64) *MockTemplateExecGasCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTemplateExecGasCall) DoAndReturn(f func(uint8) uint64) *MockTemplateExecGasCall {
	_ = "STUB: not implemented"
	return nil
}

// LoadGas mocks base method.
func (m *MockTemplate) LoadGas() uint64 { _ = "STUB: not implemented"; return 0 }

// LoadGas indicates an expected call of LoadGas.
func (mr *MockTemplateMockRecorder) LoadGas() *MockTemplateLoadGasCall {
	_ = "STUB: not implemented"
	return nil
}

// MockTemplateLoadGasCall wrap *gomock.Call
type MockTemplateLoadGasCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTemplateLoadGasCall) Return(arg0 uint64) *MockTemplateLoadGasCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockTemplateLoadGasCall) Do(f func() uint64) *MockTemplateLoadGasCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTemplateLoadGasCall) DoAndReturn(f func() uint64) *MockTemplateLoadGasCall {
	_ = "STUB: not implemented"
	return nil
}

// MaxSpend mocks base method.
func (m *MockTemplate) MaxSpend(arg0 uint8, arg1 any) (uint64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// MaxSpend indicates an expected call of MaxSpend.
func (mr *MockTemplateMockRecorder) MaxSpend(arg0, arg1 any) *MockTemplateMaxSpendCall {
	_ = "STUB: not implemented"
	return nil
}

// MockTemplateMaxSpendCall wrap *gomock.Call
type MockTemplateMaxSpendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTemplateMaxSpendCall) Return(arg0 uint64, arg1 error) *MockTemplateMaxSpendCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockTemplateMaxSpendCall) Do(f func(uint8, any) (uint64, error)) *MockTemplateMaxSpendCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTemplateMaxSpendCall) DoAndReturn(f func(uint8, any) (uint64, error)) *MockTemplateMaxSpendCall {
	_ = "STUB: not implemented"
	return nil
}

// Verify mocks base method.
func (m *MockTemplate) Verify(arg0 core.Host, arg1 []byte, arg2 *scale.Decoder) bool {
	_ = "STUB: not implemented"
	return false
}

// Verify indicates an expected call of Verify.
func (mr *MockTemplateMockRecorder) Verify(arg0, arg1, arg2 any) *MockTemplateVerifyCall {
	_ = "STUB: not implemented"
	return nil
}

// MockTemplateVerifyCall wrap *gomock.Call
type MockTemplateVerifyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTemplateVerifyCall) Return(arg0 bool) *MockTemplateVerifyCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockTemplateVerifyCall) Do(f func(core.Host, []byte, *scale.Decoder) bool) *MockTemplateVerifyCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTemplateVerifyCall) DoAndReturn(f func(core.Host, []byte, *scale.Decoder) bool) *MockTemplateVerifyCall {
	_ = "STUB: not implemented"
	return nil
}
