// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -typed -package=mocks -destination=./mocks/mocks.go -source=./interface.go -exclude_interfaces=Requester,SyncMessage,Conduit
//

// Package mocks is a generated GoMock package.
package mocks

import (
	time "time"

	rangesync "github.com/spacemeshos/go-spacemesh/sync2/rangesync"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderedSet is a mock of OrderedSet interface.
type MockOrderedSet struct {
	ctrl     *gomock.Controller
	recorder *MockOrderedSetMockRecorder
	isgomock struct{}
}

// MockOrderedSetMockRecorder is the mock recorder for MockOrderedSet.
type MockOrderedSetMockRecorder struct {
	mock *MockOrderedSet
}

// NewMockOrderedSet creates a new mock instance.
func NewMockOrderedSet(ctrl *gomock.Controller) *MockOrderedSet {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderedSet) EXPECT() *MockOrderedSetMockRecorder {
	_ = "STUB: not implemented"

	// Add mocks base method.
	return nil
}

func (m *MockOrderedSet) Add(k rangesync.KeyBytes) error { _ = "STUB: not implemented"; return nil }

// Add indicates an expected call of Add.
func (mr *MockOrderedSetMockRecorder) Add(k any) *MockOrderedSetAddCall {
	_ = "STUB: not implemented"
	return nil
}

// MockOrderedSetAddCall wrap *gomock.Call
type MockOrderedSetAddCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderedSetAddCall) Return(arg0 error) *MockOrderedSetAddCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderedSetAddCall) Do(f func(rangesync.KeyBytes) error) *MockOrderedSetAddCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderedSetAddCall) DoAndReturn(f func(rangesync.KeyBytes) error) *MockOrderedSetAddCall {
	_ = "STUB: not implemented"
	return nil
}

// Advance mocks base method.
func (m *MockOrderedSet) Advance() error { _ = "STUB: not implemented"; return nil }

// Advance indicates an expected call of Advance.
func (mr *MockOrderedSetMockRecorder) Advance() *MockOrderedSetAdvanceCall {
	_ = "STUB: not implemented"
	return nil
}

// MockOrderedSetAdvanceCall wrap *gomock.Call
type MockOrderedSetAdvanceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderedSetAdvanceCall) Return(arg0 error) *MockOrderedSetAdvanceCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderedSetAdvanceCall) Do(f func() error) *MockOrderedSetAdvanceCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderedSetAdvanceCall) DoAndReturn(f func() error) *MockOrderedSetAdvanceCall {
	_ = "STUB: not implemented"
	return nil
}

// EnsureLoaded mocks base method.
func (m *MockOrderedSet) EnsureLoaded() error { _ = "STUB: not implemented"; return nil }

// EnsureLoaded indicates an expected call of EnsureLoaded.
func (mr *MockOrderedSetMockRecorder) EnsureLoaded() *MockOrderedSetEnsureLoadedCall {
	_ = "STUB: not implemented"
	return nil
}

// MockOrderedSetEnsureLoadedCall wrap *gomock.Call
type MockOrderedSetEnsureLoadedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderedSetEnsureLoadedCall) Return(arg0 error) *MockOrderedSetEnsureLoadedCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderedSetEnsureLoadedCall) Do(f func() error) *MockOrderedSetEnsureLoadedCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderedSetEnsureLoadedCall) DoAndReturn(f func() error) *MockOrderedSetEnsureLoadedCall {
	_ = "STUB: not implemented"
	return nil
}

// Has mocks base method.
func (m *MockOrderedSet) Has(arg0 rangesync.KeyBytes) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// Has indicates an expected call of Has.
func (mr *MockOrderedSetMockRecorder) Has(arg0 any) *MockOrderedSetHasCall {
	_ = "STUB: not implemented"
	return nil
}

// MockOrderedSetHasCall wrap *gomock.Call
type MockOrderedSetHasCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderedSetHasCall) Return(arg0 bool, arg1 error) *MockOrderedSetHasCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderedSetHasCall) Do(f func(rangesync.KeyBytes) (bool, error)) *MockOrderedSetHasCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderedSetHasCall) DoAndReturn(f func(rangesync.KeyBytes) (bool, error)) *MockOrderedSetHasCall {
	_ = "STUB: not implemented"
	return nil
}

// Loaded mocks base method.
func (m *MockOrderedSet) Loaded() bool { _ = "STUB: not implemented"; return false }

// Loaded indicates an expected call of Loaded.
func (mr *MockOrderedSetMockRecorder) Loaded() *MockOrderedSetLoadedCall {
	_ = "STUB: not implemented"
	return nil
}

// MockOrderedSetLoadedCall wrap *gomock.Call
type MockOrderedSetLoadedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderedSetLoadedCall) Return(arg0 bool) *MockOrderedSetLoadedCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderedSetLoadedCall) Do(f func() bool) *MockOrderedSetLoadedCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderedSetLoadedCall) DoAndReturn(f func() bool) *MockOrderedSetLoadedCall {
	_ = "STUB: not implemented"
	return nil
}

// RangeInfo mocks base method.
func (m *MockOrderedSet) RangeInfo(x, y rangesync.KeyBytes) (rangesync.RangeInfo, error) {
	_ = "STUB: not implemented"
	return *new(rangesync.RangeInfo), nil
}

// RangeInfo indicates an expected call of RangeInfo.
func (mr *MockOrderedSetMockRecorder) RangeInfo(x, y any) *MockOrderedSetRangeInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// MockOrderedSetRangeInfoCall wrap *gomock.Call
type MockOrderedSetRangeInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderedSetRangeInfoCall) Return(arg0 rangesync.RangeInfo, arg1 error) *MockOrderedSetRangeInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderedSetRangeInfoCall) Do(f func(rangesync.KeyBytes, rangesync.KeyBytes) (rangesync.RangeInfo, error)) *MockOrderedSetRangeInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderedSetRangeInfoCall) DoAndReturn(f func(rangesync.KeyBytes, rangesync.KeyBytes) (rangesync.RangeInfo, error)) *MockOrderedSetRangeInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// Receive mocks base method.
func (m *MockOrderedSet) Receive(k rangesync.KeyBytes) error { _ = "STUB: not implemented"; return nil }

// Receive indicates an expected call of Receive.
func (mr *MockOrderedSetMockRecorder) Receive(k any) *MockOrderedSetReceiveCall {
	_ = "STUB: not implemented"
	return nil
}

// MockOrderedSetReceiveCall wrap *gomock.Call
type MockOrderedSetReceiveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderedSetReceiveCall) Return(arg0 error) *MockOrderedSetReceiveCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderedSetReceiveCall) Do(f func(rangesync.KeyBytes) error) *MockOrderedSetReceiveCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderedSetReceiveCall) DoAndReturn(f func(rangesync.KeyBytes) error) *MockOrderedSetReceiveCall {
	_ = "STUB: not implemented"
	return nil
}

// Received mocks base method.
func (m *MockOrderedSet) Received() rangesync.SeqResult {
	_ = "STUB: not implemented"
	return *new(rangesync.SeqResult)
}

// Received indicates an expected call of Received.
func (mr *MockOrderedSetMockRecorder) Received() *MockOrderedSetReceivedCall {
	_ = "STUB: not implemented"
	return nil
}

// MockOrderedSetReceivedCall wrap *gomock.Call
type MockOrderedSetReceivedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderedSetReceivedCall) Return(arg0 rangesync.SeqResult) *MockOrderedSetReceivedCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderedSetReceivedCall) Do(f func() rangesync.SeqResult) *MockOrderedSetReceivedCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderedSetReceivedCall) DoAndReturn(f func() rangesync.SeqResult) *MockOrderedSetReceivedCall {
	_ = "STUB: not implemented"
	return nil
}

// Recent mocks base method.
func (m *MockOrderedSet) Recent(since time.Time) (rangesync.SeqResult, int) {
	_ = "STUB: not implemented"
	return *new(rangesync.SeqResult), 0
}

// Recent indicates an expected call of Recent.
func (mr *MockOrderedSetMockRecorder) Recent(since any) *MockOrderedSetRecentCall {
	_ = "STUB: not implemented"
	return nil
}

// MockOrderedSetRecentCall wrap *gomock.Call
type MockOrderedSetRecentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderedSetRecentCall) Return(arg0 rangesync.SeqResult, arg1 int) *MockOrderedSetRecentCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderedSetRecentCall) Do(f func(time.Time) (rangesync.SeqResult, int)) *MockOrderedSetRecentCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderedSetRecentCall) DoAndReturn(f func(time.Time) (rangesync.SeqResult, int)) *MockOrderedSetRecentCall {
	_ = "STUB: not implemented"
	return nil
}

// SetInfo mocks base method.
func (m *MockOrderedSet) SetInfo() (rangesync.RangeInfo, error) {
	_ = "STUB: not implemented"
	return *new(rangesync.RangeInfo), nil
}

// SetInfo indicates an expected call of SetInfo.
func (mr *MockOrderedSetMockRecorder) SetInfo() *MockOrderedSetSetInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// MockOrderedSetSetInfoCall wrap *gomock.Call
type MockOrderedSetSetInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderedSetSetInfoCall) Return(arg0 rangesync.RangeInfo, arg1 error) *MockOrderedSetSetInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderedSetSetInfoCall) Do(f func() (rangesync.RangeInfo, error)) *MockOrderedSetSetInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderedSetSetInfoCall) DoAndReturn(f func() (rangesync.RangeInfo, error)) *MockOrderedSetSetInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// SplitRange mocks base method.
func (m *MockOrderedSet) SplitRange(x, y rangesync.KeyBytes, count int) (rangesync.SplitInfo, error) {
	_ = "STUB: not implemented"
	return *new(rangesync.SplitInfo), nil
}

// SplitRange indicates an expected call of SplitRange.
func (mr *MockOrderedSetMockRecorder) SplitRange(x, y, count any) *MockOrderedSetSplitRangeCall {
	_ = "STUB: not implemented"
	return nil
}

// MockOrderedSetSplitRangeCall wrap *gomock.Call
type MockOrderedSetSplitRangeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderedSetSplitRangeCall) Return(arg0 rangesync.SplitInfo, arg1 error) *MockOrderedSetSplitRangeCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderedSetSplitRangeCall) Do(f func(rangesync.KeyBytes, rangesync.KeyBytes, int) (rangesync.SplitInfo, error)) *MockOrderedSetSplitRangeCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderedSetSplitRangeCall) DoAndReturn(f func(rangesync.KeyBytes, rangesync.KeyBytes, int) (rangesync.SplitInfo, error)) *MockOrderedSetSplitRangeCall {
	_ = "STUB: not implemented"
	return nil
}

// WithCopy mocks base method.
func (m *MockOrderedSet) WithCopy(toCall func(rangesync.OrderedSet) error) error {
	_ = "STUB: not implemented"
	return nil
}

// WithCopy indicates an expected call of WithCopy.
func (mr *MockOrderedSetMockRecorder) WithCopy(toCall any) *MockOrderedSetWithCopyCall {
	_ = "STUB: not implemented"
	return nil
}

// MockOrderedSetWithCopyCall wrap *gomock.Call
type MockOrderedSetWithCopyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderedSetWithCopyCall) Return(arg0 error) *MockOrderedSetWithCopyCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderedSetWithCopyCall) Do(f func(func(rangesync.OrderedSet) error) error) *MockOrderedSetWithCopyCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderedSetWithCopyCall) DoAndReturn(f func(func(rangesync.OrderedSet) error) error) *MockOrderedSetWithCopyCall {
	_ = "STUB: not implemented"
	return nil
}
