// Code generated by MockGen. DO NOT EDIT.
// Source: ./interfaces.go
//
// Generated by this command:
//
//	mockgen -typed -package=mocks -destination=./mocks/mocks.go -source=./interfaces.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	types "github.com/spacemeshos/go-spacemesh/common/types"
	p2p "github.com/spacemeshos/go-spacemesh/p2p"
	gomock "go.uber.org/mock/gomock"
)

// Mockfetcher is a mock of fetcher interface.
type Mockfetcher struct {
	ctrl     *gomock.Controller
	recorder *MockfetcherMockRecorder
	isgomock struct{}
}

// MockfetcherMockRecorder is the mock recorder for Mockfetcher.
type MockfetcherMockRecorder struct {
	mock *Mockfetcher
}

// NewMockfetcher creates a new mock instance.
func NewMockfetcher(ctrl *gomock.Controller) *Mockfetcher { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockfetcher) EXPECT() *MockfetcherMockRecorder {
	_ = "STUB: not implemented"

	// LegacyMalfeasanceProofs mocks base method.
	return nil
}

func (m *Mockfetcher) LegacyMalfeasanceProofs(arg0 context.Context, arg1 []types.NodeID) error {
	_ = "STUB: not implemented"
	return nil
}

// LegacyMalfeasanceProofs indicates an expected call of LegacyMalfeasanceProofs.
func (mr *MockfetcherMockRecorder) LegacyMalfeasanceProofs(arg0, arg1 any) *MockfetcherLegacyMalfeasanceProofsCall {
	_ = "STUB: not implemented"
	return nil
}

// MockfetcherLegacyMalfeasanceProofsCall wrap *gomock.Call
type MockfetcherLegacyMalfeasanceProofsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockfetcherLegacyMalfeasanceProofsCall) Return(arg0 error) *MockfetcherLegacyMalfeasanceProofsCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockfetcherLegacyMalfeasanceProofsCall) Do(f func(context.Context, []types.NodeID) error) *MockfetcherLegacyMalfeasanceProofsCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockfetcherLegacyMalfeasanceProofsCall) DoAndReturn(f func(context.Context, []types.NodeID) error) *MockfetcherLegacyMalfeasanceProofsCall {
	_ = "STUB: not implemented"
	return nil
}

// LegacyMaliciousIDs mocks base method.
func (m *Mockfetcher) LegacyMaliciousIDs(arg0 context.Context, arg1 p2p.Peer) ([]types.NodeID, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// LegacyMaliciousIDs indicates an expected call of LegacyMaliciousIDs.
func (mr *MockfetcherMockRecorder) LegacyMaliciousIDs(arg0, arg1 any) *MockfetcherLegacyMaliciousIDsCall {
	_ = "STUB: not implemented"
	return nil
}

// MockfetcherLegacyMaliciousIDsCall wrap *gomock.Call
type MockfetcherLegacyMaliciousIDsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockfetcherLegacyMaliciousIDsCall) Return(arg0 []types.NodeID, arg1 error) *MockfetcherLegacyMaliciousIDsCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockfetcherLegacyMaliciousIDsCall) Do(f func(context.Context, p2p.Peer) ([]types.NodeID, error)) *MockfetcherLegacyMaliciousIDsCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockfetcherLegacyMaliciousIDsCall) DoAndReturn(f func(context.Context, p2p.Peer) ([]types.NodeID, error)) *MockfetcherLegacyMaliciousIDsCall {
	_ = "STUB: not implemented"
	return nil
}

// MalfeasanceProofs mocks base method.
func (m *Mockfetcher) MalfeasanceProofs(arg0 context.Context, arg1 []types.NodeID) error {
	_ = "STUB: not implemented"
	return nil
}

// MalfeasanceProofs indicates an expected call of MalfeasanceProofs.
func (mr *MockfetcherMockRecorder) MalfeasanceProofs(arg0, arg1 any) *MockfetcherMalfeasanceProofsCall {
	_ = "STUB: not implemented"
	return nil
}

// MockfetcherMalfeasanceProofsCall wrap *gomock.Call
type MockfetcherMalfeasanceProofsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockfetcherMalfeasanceProofsCall) Return(arg0 error) *MockfetcherMalfeasanceProofsCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockfetcherMalfeasanceProofsCall) Do(f func(context.Context, []types.NodeID) error) *MockfetcherMalfeasanceProofsCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockfetcherMalfeasanceProofsCall) DoAndReturn(f func(context.Context, []types.NodeID) error) *MockfetcherMalfeasanceProofsCall {
	_ = "STUB: not implemented"
	return nil
}

// MaliciousIDs mocks base method.
func (m *Mockfetcher) MaliciousIDs(arg0 context.Context, arg1 p2p.Peer) ([]types.NodeID, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// MaliciousIDs indicates an expected call of MaliciousIDs.
func (mr *MockfetcherMockRecorder) MaliciousIDs(arg0, arg1 any) *MockfetcherMaliciousIDsCall {
	_ = "STUB: not implemented"
	return nil
}

// MockfetcherMaliciousIDsCall wrap *gomock.Call
type MockfetcherMaliciousIDsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockfetcherMaliciousIDsCall) Return(arg0 []types.NodeID, arg1 error) *MockfetcherMaliciousIDsCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockfetcherMaliciousIDsCall) Do(f func(context.Context, p2p.Peer) ([]types.NodeID, error)) *MockfetcherMaliciousIDsCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockfetcherMaliciousIDsCall) DoAndReturn(f func(context.Context, p2p.Peer) ([]types.NodeID, error)) *MockfetcherMaliciousIDsCall {
	_ = "STUB: not implemented"
	return nil
}

// SelectBestShuffled mocks base method.
func (m *Mockfetcher) SelectBestShuffled(arg0 int) []p2p.Peer {
	_ = "STUB: not implemented"
	return nil
}

// SelectBestShuffled indicates an expected call of SelectBestShuffled.
func (mr *MockfetcherMockRecorder) SelectBestShuffled(arg0 any) *MockfetcherSelectBestShuffledCall {
	_ = "STUB: not implemented"
	return nil
}

// MockfetcherSelectBestShuffledCall wrap *gomock.Call
type MockfetcherSelectBestShuffledCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockfetcherSelectBestShuffledCall) Return(arg0 []p2p.Peer) *MockfetcherSelectBestShuffledCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockfetcherSelectBestShuffledCall) Do(f func(int) []p2p.Peer) *MockfetcherSelectBestShuffledCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockfetcherSelectBestShuffledCall) DoAndReturn(f func(int) []p2p.Peer) *MockfetcherSelectBestShuffledCall {
	_ = "STUB: not implemented"
	return nil
}

// MocklayerClock is a mock of layerClock interface.
type MocklayerClock struct {
	ctrl     *gomock.Controller
	recorder *MocklayerClockMockRecorder
	isgomock struct{}
}

// MocklayerClockMockRecorder is the mock recorder for MocklayerClock.
type MocklayerClockMockRecorder struct {
	mock *MocklayerClock
}

// NewMocklayerClock creates a new mock instance.
func NewMocklayerClock(ctrl *gomock.Controller) *MocklayerClock {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklayerClock) EXPECT() *MocklayerClockMockRecorder {
	_ = "STUB: not implemented"

	// AwaitLayer mocks base method.
	return nil
}

func (m *MocklayerClock) AwaitLayer(layerID types.LayerID) <-chan struct{} {
	_ = "STUB: not implemented"
	return nil
}

// AwaitLayer indicates an expected call of AwaitLayer.
func (mr *MocklayerClockMockRecorder) AwaitLayer(layerID any) *MocklayerClockAwaitLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// MocklayerClockAwaitLayerCall wrap *gomock.Call
type MocklayerClockAwaitLayerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocklayerClockAwaitLayerCall) Return(arg0 <-chan struct{}) *MocklayerClockAwaitLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocklayerClockAwaitLayerCall) Do(f func(types.LayerID) <-chan struct{}) *MocklayerClockAwaitLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocklayerClockAwaitLayerCall) DoAndReturn(f func(types.LayerID) <-chan struct{}) *MocklayerClockAwaitLayerCall {
	_ = "STUB: not implemented"
	return nil
}
