// Code generated by MockGen. DO NOT EDIT.
// Source: ./pubsub.go
//
// Generated by this command:
//
//	mockgen -typed -package=mocks -destination=./mocks/publisher.go -source=./pubsub.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	pubsub "github.com/spacemeshos/go-spacemesh/p2p/pubsub"
	gomock "go.uber.org/mock/gomock"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	_ = "STUB: not implemented"

	// Publish mocks base method.
	return nil
}

func (m *MockPublisher) Publish(arg0 context.Context, arg1 string, arg2 []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Publish indicates an expected call of Publish.
func (mr *MockPublisherMockRecorder) Publish(arg0, arg1, arg2 any) *MockPublisherPublishCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPublisherPublishCall wrap *gomock.Call
type MockPublisherPublishCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPublisherPublishCall) Return(arg0 error) *MockPublisherPublishCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPublisherPublishCall) Do(f func(context.Context, string, []byte) error) *MockPublisherPublishCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPublisherPublishCall) DoAndReturn(f func(context.Context, string, []byte) error) *MockPublisherPublishCall {
	_ = "STUB: not implemented"
	return nil
}

// MockSubscriber is a mock of Subscriber interface.
type MockSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriberMockRecorder
	isgomock struct{}
}

// MockSubscriberMockRecorder is the mock recorder for MockSubscriber.
type MockSubscriberMockRecorder struct {
	mock *MockSubscriber
}

// NewMockSubscriber creates a new mock instance.
func NewMockSubscriber(ctrl *gomock.Controller) *MockSubscriber {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriber) EXPECT() *MockSubscriberMockRecorder {
	_ = "STUB: not implemented"

	// Register mocks base method.
	return nil
}

func (m *MockSubscriber) Register(arg0 string, arg1 pubsub.GossipHandler, arg2 ...pubsub.ValidatorOpt) {
	_ = "STUB: not implemented"
	return
}

// Register indicates an expected call of Register.
func (mr *MockSubscriberMockRecorder) Register(arg0, arg1 any, arg2 ...any) *MockSubscriberRegisterCall {
	_ = "STUB: not implemented"
	return nil
}

// MockSubscriberRegisterCall wrap *gomock.Call
type MockSubscriberRegisterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSubscriberRegisterCall) Return() *MockSubscriberRegisterCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockSubscriberRegisterCall) Do(f func(string, pubsub.GossipHandler, ...pubsub.ValidatorOpt)) *MockSubscriberRegisterCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSubscriberRegisterCall) DoAndReturn(f func(string, pubsub.GossipHandler, ...pubsub.ValidatorOpt)) *MockSubscriberRegisterCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPublishSubscriber is a mock of PublishSubscriber interface.
type MockPublishSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockPublishSubscriberMockRecorder
	isgomock struct{}
}

// MockPublishSubscriberMockRecorder is the mock recorder for MockPublishSubscriber.
type MockPublishSubscriberMockRecorder struct {
	mock *MockPublishSubscriber
}

// NewMockPublishSubscriber creates a new mock instance.
func NewMockPublishSubscriber(ctrl *gomock.Controller) *MockPublishSubscriber {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublishSubscriber) EXPECT() *MockPublishSubscriberMockRecorder {
	_ = "STUB: not implemented"

	// Publish mocks base method.
	return nil
}

func (m *MockPublishSubscriber) Publish(arg0 context.Context, arg1 string, arg2 []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Publish indicates an expected call of Publish.
func (mr *MockPublishSubscriberMockRecorder) Publish(arg0, arg1, arg2 any) *MockPublishSubscriberPublishCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPublishSubscriberPublishCall wrap *gomock.Call
type MockPublishSubscriberPublishCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPublishSubscriberPublishCall) Return(arg0 error) *MockPublishSubscriberPublishCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPublishSubscriberPublishCall) Do(f func(context.Context, string, []byte) error) *MockPublishSubscriberPublishCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPublishSubscriberPublishCall) DoAndReturn(f func(context.Context, string, []byte) error) *MockPublishSubscriberPublishCall {
	_ = "STUB: not implemented"
	return nil
}

// Register mocks base method.
func (m *MockPublishSubscriber) Register(arg0 string, arg1 pubsub.GossipHandler, arg2 ...pubsub.ValidatorOpt) {
	_ = "STUB: not implemented"
	return
}

// Register indicates an expected call of Register.
func (mr *MockPublishSubscriberMockRecorder) Register(arg0, arg1 any, arg2 ...any) *MockPublishSubscriberRegisterCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPublishSubscriberRegisterCall wrap *gomock.Call
type MockPublishSubscriberRegisterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPublishSubscriberRegisterCall) Return() *MockPublishSubscriberRegisterCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPublishSubscriberRegisterCall) Do(f func(string, pubsub.GossipHandler, ...pubsub.ValidatorOpt)) *MockPublishSubscriberRegisterCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPublishSubscriberRegisterCall) DoAndReturn(f func(string, pubsub.GossipHandler, ...pubsub.ValidatorOpt)) *MockPublishSubscriberRegisterCall {
	_ = "STUB: not implemented"
	return nil
}
