// Code generated by MockGen. DO NOT EDIT.
// Source: ./store.go
//
// Generated by this command:
//
//	mockgen -typed -package=datastore -destination=./mocks.go -source=./store.go
//

// Package datastore is a generated GoMock package.
package datastore

import (
	context "context"

	types "github.com/spacemeshos/go-spacemesh/common/types"
	gomock "go.uber.org/mock/gomock"
)

// MockMalfeasanceProvider is a mock of MalfeasanceProvider interface.
type MockMalfeasanceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockMalfeasanceProviderMockRecorder
	isgomock struct{}
}

// MockMalfeasanceProviderMockRecorder is the mock recorder for MockMalfeasanceProvider.
type MockMalfeasanceProviderMockRecorder struct {
	mock *MockMalfeasanceProvider
}

// NewMockMalfeasanceProvider creates a new mock instance.
func NewMockMalfeasanceProvider(ctrl *gomock.Controller) *MockMalfeasanceProvider {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMalfeasanceProvider) EXPECT() *MockMalfeasanceProviderMockRecorder {
	_ = "STUB: not implemented"

	// ProofByID mocks base method.
	return nil
}

func (m *MockMalfeasanceProvider) ProofByID(ctx context.Context, nodeID types.NodeID) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ProofByID indicates an expected call of ProofByID.
func (mr *MockMalfeasanceProviderMockRecorder) ProofByID(ctx, nodeID any) *MockMalfeasanceProviderProofByIDCall {
	_ = "STUB: not implemented"
	return nil
}

// MockMalfeasanceProviderProofByIDCall wrap *gomock.Call
type MockMalfeasanceProviderProofByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMalfeasanceProviderProofByIDCall) Return(arg0 []byte, arg1 error) *MockMalfeasanceProviderProofByIDCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockMalfeasanceProviderProofByIDCall) Do(f func(context.Context, types.NodeID) ([]byte, error)) *MockMalfeasanceProviderProofByIDCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMalfeasanceProviderProofByIDCall) DoAndReturn(f func(context.Context, types.NodeID) ([]byte, error)) *MockMalfeasanceProviderProofByIDCall {
	_ = "STUB: not implemented"
	return nil
}
