// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -typed -package=beacon -destination=./mocks.go -source=./interface.go
//

// Package beacon is a generated GoMock package.
package beacon

import (
	context "context"
	time "time"

	weakcoin "github.com/spacemeshos/go-spacemesh/beacon/weakcoin"
	types "github.com/spacemeshos/go-spacemesh/common/types"
	p2p "github.com/spacemeshos/go-spacemesh/p2p"
	gomock "go.uber.org/mock/gomock"
)

// Mockcoin is a mock of coin interface.
type Mockcoin struct {
	ctrl     *gomock.Controller
	recorder *MockcoinMockRecorder
	isgomock struct{}
}

// MockcoinMockRecorder is the mock recorder for Mockcoin.
type MockcoinMockRecorder struct {
	mock *Mockcoin
}

// NewMockcoin creates a new mock instance.
func NewMockcoin(ctrl *gomock.Controller) *Mockcoin { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockcoin) EXPECT() *MockcoinMockRecorder {
	_ = "STUB: not implemented"

	// FinishEpoch mocks base method.
	return nil
}

func (m *Mockcoin) FinishEpoch(arg0 context.Context, arg1 types.EpochID) {
	_ = "STUB: not implemented"
	return
}

// FinishEpoch indicates an expected call of FinishEpoch.
func (mr *MockcoinMockRecorder) FinishEpoch(arg0, arg1 any) *MockcoinFinishEpochCall {
	_ = "STUB: not implemented"
	return nil
}

// MockcoinFinishEpochCall wrap *gomock.Call
type MockcoinFinishEpochCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockcoinFinishEpochCall) Return() *MockcoinFinishEpochCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockcoinFinishEpochCall) Do(f func(context.Context, types.EpochID)) *MockcoinFinishEpochCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockcoinFinishEpochCall) DoAndReturn(f func(context.Context, types.EpochID)) *MockcoinFinishEpochCall {
	_ = "STUB: not implemented"
	return nil
}

// FinishRound mocks base method.
func (m *Mockcoin) FinishRound(arg0 context.Context) { _ = "STUB: not implemented"; return }

// FinishRound indicates an expected call of FinishRound.
func (mr *MockcoinMockRecorder) FinishRound(arg0 any) *MockcoinFinishRoundCall {
	_ = "STUB: not implemented"
	return nil
}

// MockcoinFinishRoundCall wrap *gomock.Call
type MockcoinFinishRoundCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockcoinFinishRoundCall) Return() *MockcoinFinishRoundCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockcoinFinishRoundCall) Do(f func(context.Context)) *MockcoinFinishRoundCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockcoinFinishRoundCall) DoAndReturn(f func(context.Context)) *MockcoinFinishRoundCall {
	_ = "STUB: not implemented"
	return nil
}

// Get mocks base method.
func (m *Mockcoin) Get(arg0 context.Context, arg1 types.EpochID, arg2 types.RoundID) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// Get indicates an expected call of Get.
func (mr *MockcoinMockRecorder) Get(arg0, arg1, arg2 any) *MockcoinGetCall {
	_ = "STUB: not implemented"
	return nil
}

// MockcoinGetCall wrap *gomock.Call
type MockcoinGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockcoinGetCall) Return(arg0 bool, arg1 error) *MockcoinGetCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockcoinGetCall) Do(f func(context.Context, types.EpochID, types.RoundID) (bool, error)) *MockcoinGetCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockcoinGetCall) DoAndReturn(f func(context.Context, types.EpochID, types.RoundID) (bool, error)) *MockcoinGetCall {
	_ = "STUB: not implemented"
	return nil
}

// HandleProposal mocks base method.
func (m *Mockcoin) HandleProposal(arg0 context.Context, arg1 p2p.Peer, arg2 []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// HandleProposal indicates an expected call of HandleProposal.
func (mr *MockcoinMockRecorder) HandleProposal(arg0, arg1, arg2 any) *MockcoinHandleProposalCall {
	_ = "STUB: not implemented"
	return nil
}

// MockcoinHandleProposalCall wrap *gomock.Call
type MockcoinHandleProposalCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockcoinHandleProposalCall) Return(arg0 error) *MockcoinHandleProposalCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockcoinHandleProposalCall) Do(f func(context.Context, p2p.Peer, []byte) error) *MockcoinHandleProposalCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockcoinHandleProposalCall) DoAndReturn(f func(context.Context, p2p.Peer, []byte) error) *MockcoinHandleProposalCall {
	_ = "STUB: not implemented"
	return nil
}

// StartEpoch mocks base method.
func (m *Mockcoin) StartEpoch(arg0 context.Context, arg1 types.EpochID) {
	_ = "STUB: not implemented"
	return
}

// StartEpoch indicates an expected call of StartEpoch.
func (mr *MockcoinMockRecorder) StartEpoch(arg0, arg1 any) *MockcoinStartEpochCall {
	_ = "STUB: not implemented"
	return nil
}

// MockcoinStartEpochCall wrap *gomock.Call
type MockcoinStartEpochCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockcoinStartEpochCall) Return() *MockcoinStartEpochCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockcoinStartEpochCall) Do(f func(context.Context, types.EpochID)) *MockcoinStartEpochCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockcoinStartEpochCall) DoAndReturn(f func(context.Context, types.EpochID)) *MockcoinStartEpochCall {
	_ = "STUB: not implemented"
	return nil
}

// StartRound mocks base method.
func (m *Mockcoin) StartRound(arg0 context.Context, arg1 types.RoundID, arg2 []weakcoin.Participant) {
	_ = "STUB: not implemented"
	return
}

// StartRound indicates an expected call of StartRound.
func (mr *MockcoinMockRecorder) StartRound(arg0, arg1, arg2 any) *MockcoinStartRoundCall {
	_ = "STUB: not implemented"
	return nil
}

// MockcoinStartRoundCall wrap *gomock.Call
type MockcoinStartRoundCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockcoinStartRoundCall) Return() *MockcoinStartRoundCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockcoinStartRoundCall) Do(f func(context.Context, types.RoundID, []weakcoin.Participant)) *MockcoinStartRoundCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockcoinStartRoundCall) DoAndReturn(f func(context.Context, types.RoundID, []weakcoin.Participant)) *MockcoinStartRoundCall {
	_ = "STUB: not implemented"
	return nil
}

// MockeligibilityChecker is a mock of eligibilityChecker interface.
type MockeligibilityChecker struct {
	ctrl     *gomock.Controller
	recorder *MockeligibilityCheckerMockRecorder
	isgomock struct{}
}

// MockeligibilityCheckerMockRecorder is the mock recorder for MockeligibilityChecker.
type MockeligibilityCheckerMockRecorder struct {
	mock *MockeligibilityChecker
}

// NewMockeligibilityChecker creates a new mock instance.
func NewMockeligibilityChecker(ctrl *gomock.Controller) *MockeligibilityChecker {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockeligibilityChecker) EXPECT() *MockeligibilityCheckerMockRecorder {
	_ = "STUB: not implemented"

	// PassStrictThreshold mocks base method.
	return nil
}

func (m *MockeligibilityChecker) PassStrictThreshold(arg0 types.VrfSignature) bool {
	_ = "STUB: not implemented"
	return false
}

// PassStrictThreshold indicates an expected call of PassStrictThreshold.
func (mr *MockeligibilityCheckerMockRecorder) PassStrictThreshold(arg0 any) *MockeligibilityCheckerPassStrictThresholdCall {
	_ = "STUB: not implemented"
	return nil
}

// MockeligibilityCheckerPassStrictThresholdCall wrap *gomock.Call
type MockeligibilityCheckerPassStrictThresholdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockeligibilityCheckerPassStrictThresholdCall) Return(arg0 bool) *MockeligibilityCheckerPassStrictThresholdCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockeligibilityCheckerPassStrictThresholdCall) Do(f func(types.VrfSignature) bool) *MockeligibilityCheckerPassStrictThresholdCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockeligibilityCheckerPassStrictThresholdCall) DoAndReturn(f func(types.VrfSignature) bool) *MockeligibilityCheckerPassStrictThresholdCall {
	_ = "STUB: not implemented"
	return nil
}

// PassThreshold mocks base method.
func (m *MockeligibilityChecker) PassThreshold(arg0 types.VrfSignature) bool {
	_ = "STUB: not implemented"
	return false
}

// PassThreshold indicates an expected call of PassThreshold.
func (mr *MockeligibilityCheckerMockRecorder) PassThreshold(arg0 any) *MockeligibilityCheckerPassThresholdCall {
	_ = "STUB: not implemented"
	return nil
}

// MockeligibilityCheckerPassThresholdCall wrap *gomock.Call
type MockeligibilityCheckerPassThresholdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockeligibilityCheckerPassThresholdCall) Return(arg0 bool) *MockeligibilityCheckerPassThresholdCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockeligibilityCheckerPassThresholdCall) Do(f func(types.VrfSignature) bool) *MockeligibilityCheckerPassThresholdCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockeligibilityCheckerPassThresholdCall) DoAndReturn(f func(types.VrfSignature) bool) *MockeligibilityCheckerPassThresholdCall {
	_ = "STUB: not implemented"
	return nil
}

// MocklayerClock is a mock of layerClock interface.
type MocklayerClock struct {
	ctrl     *gomock.Controller
	recorder *MocklayerClockMockRecorder
	isgomock struct{}
}

// MocklayerClockMockRecorder is the mock recorder for MocklayerClock.
type MocklayerClockMockRecorder struct {
	mock *MocklayerClock
}

// NewMocklayerClock creates a new mock instance.
func NewMocklayerClock(ctrl *gomock.Controller) *MocklayerClock {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklayerClock) EXPECT() *MocklayerClockMockRecorder {
	_ = "STUB: not implemented"

	// AwaitLayer mocks base method.
	return nil
}

func (m *MocklayerClock) AwaitLayer(arg0 types.LayerID) <-chan struct{} {
	_ = "STUB: not implemented"
	return nil
}

// AwaitLayer indicates an expected call of AwaitLayer.
func (mr *MocklayerClockMockRecorder) AwaitLayer(arg0 any) *MocklayerClockAwaitLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// MocklayerClockAwaitLayerCall wrap *gomock.Call
type MocklayerClockAwaitLayerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocklayerClockAwaitLayerCall) Return(arg0 <-chan struct{}) *MocklayerClockAwaitLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocklayerClockAwaitLayerCall) Do(f func(types.LayerID) <-chan struct{}) *MocklayerClockAwaitLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocklayerClockAwaitLayerCall) DoAndReturn(f func(types.LayerID) <-chan struct{}) *MocklayerClockAwaitLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// CurrentLayer mocks base method.
func (m *MocklayerClock) CurrentLayer() types.LayerID {
	_ = "STUB: not implemented"
	return *new(types.LayerID)
}

// CurrentLayer indicates an expected call of CurrentLayer.
func (mr *MocklayerClockMockRecorder) CurrentLayer() *MocklayerClockCurrentLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// MocklayerClockCurrentLayerCall wrap *gomock.Call
type MocklayerClockCurrentLayerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocklayerClockCurrentLayerCall) Return(arg0 types.LayerID) *MocklayerClockCurrentLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocklayerClockCurrentLayerCall) Do(f func() types.LayerID) *MocklayerClockCurrentLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocklayerClockCurrentLayerCall) DoAndReturn(f func() types.LayerID) *MocklayerClockCurrentLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// LayerToTime mocks base method.
func (m *MocklayerClock) LayerToTime(arg0 types.LayerID) time.Time {
	_ = "STUB: not implemented"
	return *new(time.Time)
}

// LayerToTime indicates an expected call of LayerToTime.
func (mr *MocklayerClockMockRecorder) LayerToTime(arg0 any) *MocklayerClockLayerToTimeCall {
	_ = "STUB: not implemented"
	return nil
}

// MocklayerClockLayerToTimeCall wrap *gomock.Call
type MocklayerClockLayerToTimeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocklayerClockLayerToTimeCall) Return(arg0 time.Time) *MocklayerClockLayerToTimeCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocklayerClockLayerToTimeCall) Do(f func(types.LayerID) time.Time) *MocklayerClockLayerToTimeCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocklayerClockLayerToTimeCall) DoAndReturn(f func(types.LayerID) time.Time) *MocklayerClockLayerToTimeCall {
	_ = "STUB: not implemented"
	return nil
}

// MockvrfSigner is a mock of vrfSigner interface.
type MockvrfSigner struct {
	ctrl     *gomock.Controller
	recorder *MockvrfSignerMockRecorder
	isgomock struct{}
}

// MockvrfSignerMockRecorder is the mock recorder for MockvrfSigner.
type MockvrfSignerMockRecorder struct {
	mock *MockvrfSigner
}

// NewMockvrfSigner creates a new mock instance.
func NewMockvrfSigner(ctrl *gomock.Controller) *MockvrfSigner {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvrfSigner) EXPECT() *MockvrfSignerMockRecorder {
	_ = "STUB: not implemented"

	// NodeID mocks base method.
	return nil
}

func (m *MockvrfSigner) NodeID() types.NodeID { _ = "STUB: not implemented"; return *new(types.NodeID) }

// NodeID indicates an expected call of NodeID.
func (mr *MockvrfSignerMockRecorder) NodeID() *MockvrfSignerNodeIDCall {
	_ = "STUB: not implemented"
	return nil
}

// MockvrfSignerNodeIDCall wrap *gomock.Call
type MockvrfSignerNodeIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockvrfSignerNodeIDCall) Return(arg0 types.NodeID) *MockvrfSignerNodeIDCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockvrfSignerNodeIDCall) Do(f func() types.NodeID) *MockvrfSignerNodeIDCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockvrfSignerNodeIDCall) DoAndReturn(f func() types.NodeID) *MockvrfSignerNodeIDCall {
	_ = "STUB: not implemented"
	return nil
}

// Sign mocks base method.
func (m *MockvrfSigner) Sign(msg []byte) types.VrfSignature {
	_ = "STUB: not implemented"
	return *new(types.VrfSignature)
}

// Sign indicates an expected call of Sign.
func (mr *MockvrfSignerMockRecorder) Sign(msg any) *MockvrfSignerSignCall {
	_ = "STUB: not implemented"
	return nil
}

// MockvrfSignerSignCall wrap *gomock.Call
type MockvrfSignerSignCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockvrfSignerSignCall) Return(arg0 types.VrfSignature) *MockvrfSignerSignCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockvrfSignerSignCall) Do(f func([]byte) types.VrfSignature) *MockvrfSignerSignCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockvrfSignerSignCall) DoAndReturn(f func([]byte) types.VrfSignature) *MockvrfSignerSignCall {
	_ = "STUB: not implemented"
	return nil
}

// MockvrfVerifier is a mock of vrfVerifier interface.
type MockvrfVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockvrfVerifierMockRecorder
	isgomock struct{}
}

// MockvrfVerifierMockRecorder is the mock recorder for MockvrfVerifier.
type MockvrfVerifierMockRecorder struct {
	mock *MockvrfVerifier
}

// NewMockvrfVerifier creates a new mock instance.
func NewMockvrfVerifier(ctrl *gomock.Controller) *MockvrfVerifier {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvrfVerifier) EXPECT() *MockvrfVerifierMockRecorder {
	_ = "STUB: not implemented"

	// Verify mocks base method.
	return nil
}

func (m *MockvrfVerifier) Verify(nodeID types.NodeID, msg []byte, sig types.VrfSignature) bool {
	_ = "STUB: not implemented"
	return false
}

// Verify indicates an expected call of Verify.
func (mr *MockvrfVerifierMockRecorder) Verify(nodeID, msg, sig any) *MockvrfVerifierVerifyCall {
	_ = "STUB: not implemented"
	return nil
}

// MockvrfVerifierVerifyCall wrap *gomock.Call
type MockvrfVerifierVerifyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockvrfVerifierVerifyCall) Return(arg0 bool) *MockvrfVerifierVerifyCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockvrfVerifierVerifyCall) Do(f func(types.NodeID, []byte, types.VrfSignature) bool) *MockvrfVerifierVerifyCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockvrfVerifierVerifyCall) DoAndReturn(f func(types.NodeID, []byte, types.VrfSignature) bool) *MockvrfVerifierVerifyCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknonceFetcher is a mock of nonceFetcher interface.
type MocknonceFetcher struct {
	ctrl     *gomock.Controller
	recorder *MocknonceFetcherMockRecorder
	isgomock struct{}
}

// MocknonceFetcherMockRecorder is the mock recorder for MocknonceFetcher.
type MocknonceFetcherMockRecorder struct {
	mock *MocknonceFetcher
}

// NewMocknonceFetcher creates a new mock instance.
func NewMocknonceFetcher(ctrl *gomock.Controller) *MocknonceFetcher {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknonceFetcher) EXPECT() *MocknonceFetcherMockRecorder {
	_ = "STUB: not implemented"

	// VRFNonce mocks base method.
	return nil
}

func (m *MocknonceFetcher) VRFNonce(arg0 types.NodeID, arg1 types.EpochID) (types.VRFPostIndex, error) {
	_ = "STUB: not implemented"
	return *new(types.VRFPostIndex), nil
}

// VRFNonce indicates an expected call of VRFNonce.
func (mr *MocknonceFetcherMockRecorder) VRFNonce(arg0, arg1 any) *MocknonceFetcherVRFNonceCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknonceFetcherVRFNonceCall wrap *gomock.Call
type MocknonceFetcherVRFNonceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknonceFetcherVRFNonceCall) Return(arg0 types.VRFPostIndex, arg1 error) *MocknonceFetcherVRFNonceCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknonceFetcherVRFNonceCall) Do(f func(types.NodeID, types.EpochID) (types.VRFPostIndex, error)) *MocknonceFetcherVRFNonceCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknonceFetcherVRFNonceCall) DoAndReturn(f func(types.NodeID, types.EpochID) (types.VRFPostIndex, error)) *MocknonceFetcherVRFNonceCall {
	_ = "STUB: not implemented"
	return nil
}
