// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -typed -package=mocks -destination=./mocks/mocks.go -source=./interface.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	types "github.com/spacemeshos/go-spacemesh/common/types"
	p2p "github.com/spacemeshos/go-spacemesh/p2p"
	server "github.com/spacemeshos/go-spacemesh/p2p/server"
	signing "github.com/spacemeshos/go-spacemesh/signing"
	gomock "go.uber.org/mock/gomock"
)

// MockstreamRequester is a mock of streamRequester interface.
type MockstreamRequester struct {
	ctrl     *gomock.Controller
	recorder *MockstreamRequesterMockRecorder
	isgomock struct{}
}

// MockstreamRequesterMockRecorder is the mock recorder for MockstreamRequester.
type MockstreamRequesterMockRecorder struct {
	mock *MockstreamRequester
}

// NewMockstreamRequester creates a new mock instance.
func NewMockstreamRequester(ctrl *gomock.Controller) *MockstreamRequester {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstreamRequester) EXPECT() *MockstreamRequesterMockRecorder {
	_ = "STUB: not implemented"

	// Run mocks base method.
	return nil
}

func (m *MockstreamRequester) Run(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// Run indicates an expected call of Run.
func (mr *MockstreamRequesterMockRecorder) Run(ctx any) *MockstreamRequesterRunCall {
	_ = "STUB: not implemented"
	return nil
}

// MockstreamRequesterRunCall wrap *gomock.Call
type MockstreamRequesterRunCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockstreamRequesterRunCall) Return(arg0 error) *MockstreamRequesterRunCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockstreamRequesterRunCall) Do(f func(context.Context) error) *MockstreamRequesterRunCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockstreamRequesterRunCall) DoAndReturn(f func(context.Context) error) *MockstreamRequesterRunCall {
	_ = "STUB: not implemented"
	return nil
}

// StreamRequest mocks base method.
func (m *MockstreamRequester) StreamRequest(arg0 context.Context, arg1 p2p.Peer, arg2 []byte, arg3 server.StreamRequestCallback, arg4 ...string) error {
	_ = "STUB: not implemented"
	return nil
}

// StreamRequest indicates an expected call of StreamRequest.
func (mr *MockstreamRequesterMockRecorder) StreamRequest(arg0, arg1, arg2, arg3 any, arg4 ...any) *MockstreamRequesterStreamRequestCall {
	_ = "STUB: not implemented"
	return nil
}

// MockstreamRequesterStreamRequestCall wrap *gomock.Call
type MockstreamRequesterStreamRequestCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockstreamRequesterStreamRequestCall) Return(arg0 error) *MockstreamRequesterStreamRequestCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockstreamRequesterStreamRequestCall) Do(f func(context.Context, p2p.Peer, []byte, server.StreamRequestCallback, ...string) error) *MockstreamRequesterStreamRequestCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockstreamRequesterStreamRequestCall) DoAndReturn(f func(context.Context, p2p.Peer, []byte, server.StreamRequestCallback, ...string) error) *MockstreamRequesterStreamRequestCall {
	_ = "STUB: not implemented"
	return nil
}

// Mockverifier is a mock of verifier interface.
type Mockverifier struct {
	ctrl     *gomock.Controller
	recorder *MockverifierMockRecorder
	isgomock struct{}
}

// MockverifierMockRecorder is the mock recorder for Mockverifier.
type MockverifierMockRecorder struct {
	mock *Mockverifier
}

// NewMockverifier creates a new mock instance.
func NewMockverifier(ctrl *gomock.Controller) *Mockverifier { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockverifier) EXPECT() *MockverifierMockRecorder {
	_ = "STUB: not implemented"

	// Verify mocks base method.
	return nil
}

func (m *Mockverifier) Verify(arg0 signing.Domain, arg1 types.NodeID, arg2 []byte, arg3 types.EdSignature) bool {
	_ = "STUB: not implemented"
	return false
}

// Verify indicates an expected call of Verify.
func (mr *MockverifierMockRecorder) Verify(arg0, arg1, arg2, arg3 any) *MockverifierVerifyCall {
	_ = "STUB: not implemented"
	return nil
}

// MockverifierVerifyCall wrap *gomock.Call
type MockverifierVerifyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockverifierVerifyCall) Return(arg0 bool) *MockverifierVerifyCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockverifierVerifyCall) Do(f func(signing.Domain, types.NodeID, []byte, types.EdSignature) bool) *MockverifierVerifyCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockverifierVerifyCall) DoAndReturn(f func(signing.Domain, types.NodeID, []byte, types.EdSignature) bool) *MockverifierVerifyCall {
	_ = "STUB: not implemented"
	return nil
}
