// Code generated by MockGen. DO NOT EDIT.
// Source: ./peerinfo.go
//
// Generated by this command:
//
//	mockgen -typed -package=peerinfo -destination=./mocks/mocks.go -source=./peerinfo.go
//

// Package peerinfo is a generated GoMock package.
package peerinfo

import (
	peer "github.com/libp2p/go-libp2p/core/peer"
	protocol "github.com/libp2p/go-libp2p/core/protocol"
	peerinfo "github.com/spacemeshos/go-spacemesh/p2p/peerinfo"
	gomock "go.uber.org/mock/gomock"
)

// MockPeerInfo is a mock of PeerInfo interface.
type MockPeerInfo struct {
	ctrl     *gomock.Controller
	recorder *MockPeerInfoMockRecorder
	isgomock struct{}
}

// MockPeerInfoMockRecorder is the mock recorder for MockPeerInfo.
type MockPeerInfoMockRecorder struct {
	mock *MockPeerInfo
}

// NewMockPeerInfo creates a new mock instance.
func NewMockPeerInfo(ctrl *gomock.Controller) *MockPeerInfo { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPeerInfo) EXPECT() *MockPeerInfoMockRecorder {
	_ = "STUB: not implemented"

	// EnsurePeerInfo mocks base method.
	return nil
}

func (m *MockPeerInfo) EnsurePeerInfo(p peer.ID) *peerinfo.Info {
	_ = "STUB: not implemented"
	return nil
}

// EnsurePeerInfo indicates an expected call of EnsurePeerInfo.
func (mr *MockPeerInfoMockRecorder) EnsurePeerInfo(p any) *MockPeerInfoEnsurePeerInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPeerInfoEnsurePeerInfoCall wrap *gomock.Call
type MockPeerInfoEnsurePeerInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPeerInfoEnsurePeerInfoCall) Return(arg0 *peerinfo.Info) *MockPeerInfoEnsurePeerInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPeerInfoEnsurePeerInfoCall) Do(f func(peer.ID) *peerinfo.Info) *MockPeerInfoEnsurePeerInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPeerInfoEnsurePeerInfoCall) DoAndReturn(f func(peer.ID) *peerinfo.Info) *MockPeerInfoEnsurePeerInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// EnsureProtoStats mocks base method.
func (m *MockPeerInfo) EnsureProtoStats(proto protocol.ID) *peerinfo.DataStats {
	_ = "STUB: not implemented"
	return nil
}

// EnsureProtoStats indicates an expected call of EnsureProtoStats.
func (mr *MockPeerInfoMockRecorder) EnsureProtoStats(proto any) *MockPeerInfoEnsureProtoStatsCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPeerInfoEnsureProtoStatsCall wrap *gomock.Call
type MockPeerInfoEnsureProtoStatsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPeerInfoEnsureProtoStatsCall) Return(arg0 *peerinfo.DataStats) *MockPeerInfoEnsureProtoStatsCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPeerInfoEnsureProtoStatsCall) Do(f func(protocol.ID) *peerinfo.DataStats) *MockPeerInfoEnsureProtoStatsCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPeerInfoEnsureProtoStatsCall) DoAndReturn(f func(protocol.ID) *peerinfo.DataStats) *MockPeerInfoEnsureProtoStatsCall {
	_ = "STUB: not implemented"
	return nil
}

// Protocols mocks base method.
func (m *MockPeerInfo) Protocols() []protocol.ID { _ = "STUB: not implemented"; return nil }

// Protocols indicates an expected call of Protocols.
func (mr *MockPeerInfoMockRecorder) Protocols() *MockPeerInfoProtocolsCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPeerInfoProtocolsCall wrap *gomock.Call
type MockPeerInfoProtocolsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPeerInfoProtocolsCall) Return(arg0 []protocol.ID) *MockPeerInfoProtocolsCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPeerInfoProtocolsCall) Do(f func() []protocol.ID) *MockPeerInfoProtocolsCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPeerInfoProtocolsCall) DoAndReturn(f func() []protocol.ID) *MockPeerInfoProtocolsCall {
	_ = "STUB: not implemented"
	return nil
}

// RecordReceived mocks base method.
func (m *MockPeerInfo) RecordReceived(n int64, proto protocol.ID, p peer.ID) {
	_ = "STUB: not implemented"
	return
}

// RecordReceived indicates an expected call of RecordReceived.
func (mr *MockPeerInfoMockRecorder) RecordReceived(n, proto, p any) *MockPeerInfoRecordReceivedCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPeerInfoRecordReceivedCall wrap *gomock.Call
type MockPeerInfoRecordReceivedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPeerInfoRecordReceivedCall) Return() *MockPeerInfoRecordReceivedCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPeerInfoRecordReceivedCall) Do(f func(int64, protocol.ID, peer.ID)) *MockPeerInfoRecordReceivedCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPeerInfoRecordReceivedCall) DoAndReturn(f func(int64, protocol.ID, peer.ID)) *MockPeerInfoRecordReceivedCall {
	_ = "STUB: not implemented"
	return nil
}

// RecordSent mocks base method.
func (m *MockPeerInfo) RecordSent(n int64, proto protocol.ID, p peer.ID) {
	_ = "STUB: not implemented"
	return
}

// RecordSent indicates an expected call of RecordSent.
func (mr *MockPeerInfoMockRecorder) RecordSent(n, proto, p any) *MockPeerInfoRecordSentCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPeerInfoRecordSentCall wrap *gomock.Call
type MockPeerInfoRecordSentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPeerInfoRecordSentCall) Return() *MockPeerInfoRecordSentCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPeerInfoRecordSentCall) Do(f func(int64, protocol.ID, peer.ID)) *MockPeerInfoRecordSentCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPeerInfoRecordSentCall) DoAndReturn(f func(int64, protocol.ID, peer.ID)) *MockPeerInfoRecordSentCall {
	_ = "STUB: not implemented"
	return nil
}
