// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -typed -package=mocks -destination=./mocks/mocks.go -source=./interface.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	types "github.com/spacemeshos/go-spacemesh/common/types"
	gomock "go.uber.org/mock/gomock"
)

// MockconservativeState is a mock of conservativeState interface.
type MockconservativeState struct {
	ctrl     *gomock.Controller
	recorder *MockconservativeStateMockRecorder
	isgomock struct{}
}

// MockconservativeStateMockRecorder is the mock recorder for MockconservativeState.
type MockconservativeStateMockRecorder struct {
	mock *MockconservativeState
}

// NewMockconservativeState creates a new mock instance.
func NewMockconservativeState(ctrl *gomock.Controller) *MockconservativeState {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconservativeState) EXPECT() *MockconservativeStateMockRecorder {
	_ = "STUB: not implemented"

	// LinkTXsWithBlock mocks base method.
	return nil
}

func (m *MockconservativeState) LinkTXsWithBlock(arg0 types.LayerID, arg1 types.BlockID, arg2 []types.TransactionID) error {
	_ = "STUB: not implemented"
	return nil
}

// LinkTXsWithBlock indicates an expected call of LinkTXsWithBlock.
func (mr *MockconservativeStateMockRecorder) LinkTXsWithBlock(arg0, arg1, arg2 any) *MockconservativeStateLinkTXsWithBlockCall {
	_ = "STUB: not implemented"
	return nil
}

// MockconservativeStateLinkTXsWithBlockCall wrap *gomock.Call
type MockconservativeStateLinkTXsWithBlockCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockconservativeStateLinkTXsWithBlockCall) Return(arg0 error) *MockconservativeStateLinkTXsWithBlockCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockconservativeStateLinkTXsWithBlockCall) Do(f func(types.LayerID, types.BlockID, []types.TransactionID) error) *MockconservativeStateLinkTXsWithBlockCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockconservativeStateLinkTXsWithBlockCall) DoAndReturn(f func(types.LayerID, types.BlockID, []types.TransactionID) error) *MockconservativeStateLinkTXsWithBlockCall {
	_ = "STUB: not implemented"
	return nil
}

// LinkTXsWithProposal mocks base method.
func (m *MockconservativeState) LinkTXsWithProposal(arg0 types.LayerID, arg1 types.ProposalID, arg2 []types.TransactionID) error {
	_ = "STUB: not implemented"
	return nil
}

// LinkTXsWithProposal indicates an expected call of LinkTXsWithProposal.
func (mr *MockconservativeStateMockRecorder) LinkTXsWithProposal(arg0, arg1, arg2 any) *MockconservativeStateLinkTXsWithProposalCall {
	_ = "STUB: not implemented"
	return nil
}

// MockconservativeStateLinkTXsWithProposalCall wrap *gomock.Call
type MockconservativeStateLinkTXsWithProposalCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockconservativeStateLinkTXsWithProposalCall) Return(arg0 error) *MockconservativeStateLinkTXsWithProposalCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockconservativeStateLinkTXsWithProposalCall) Do(f func(types.LayerID, types.ProposalID, []types.TransactionID) error) *MockconservativeStateLinkTXsWithProposalCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockconservativeStateLinkTXsWithProposalCall) DoAndReturn(f func(types.LayerID, types.ProposalID, []types.TransactionID) error) *MockconservativeStateLinkTXsWithProposalCall {
	_ = "STUB: not implemented"
	return nil
}

// RevertCache mocks base method.
func (m *MockconservativeState) RevertCache(arg0 types.LayerID) error {
	_ = "STUB: not implemented"
	return nil
}

// RevertCache indicates an expected call of RevertCache.
func (mr *MockconservativeStateMockRecorder) RevertCache(arg0 any) *MockconservativeStateRevertCacheCall {
	_ = "STUB: not implemented"
	return nil
}

// MockconservativeStateRevertCacheCall wrap *gomock.Call
type MockconservativeStateRevertCacheCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockconservativeStateRevertCacheCall) Return(arg0 error) *MockconservativeStateRevertCacheCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockconservativeStateRevertCacheCall) Do(f func(types.LayerID) error) *MockconservativeStateRevertCacheCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockconservativeStateRevertCacheCall) DoAndReturn(f func(types.LayerID) error) *MockconservativeStateRevertCacheCall {
	_ = "STUB: not implemented"
	return nil
}

// UpdateCache mocks base method.
func (m *MockconservativeState) UpdateCache(arg0 context.Context, arg1 types.LayerID, arg2 types.BlockID, arg3 []types.TransactionWithResult, arg4 []types.Transaction) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateCache indicates an expected call of UpdateCache.
func (mr *MockconservativeStateMockRecorder) UpdateCache(arg0, arg1, arg2, arg3, arg4 any) *MockconservativeStateUpdateCacheCall {
	_ = "STUB: not implemented"
	return nil
}

// MockconservativeStateUpdateCacheCall wrap *gomock.Call
type MockconservativeStateUpdateCacheCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockconservativeStateUpdateCacheCall) Return(arg0 error) *MockconservativeStateUpdateCacheCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockconservativeStateUpdateCacheCall) Do(f func(context.Context, types.LayerID, types.BlockID, []types.TransactionWithResult, []types.Transaction) error) *MockconservativeStateUpdateCacheCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockconservativeStateUpdateCacheCall) DoAndReturn(f func(context.Context, types.LayerID, types.BlockID, []types.TransactionWithResult, []types.Transaction) error) *MockconservativeStateUpdateCacheCall {
	_ = "STUB: not implemented"
	return nil
}

// MockvmState is a mock of vmState interface.
type MockvmState struct {
	ctrl     *gomock.Controller
	recorder *MockvmStateMockRecorder
	isgomock struct{}
}

// MockvmStateMockRecorder is the mock recorder for MockvmState.
type MockvmStateMockRecorder struct {
	mock *MockvmState
}

// NewMockvmState creates a new mock instance.
func NewMockvmState(ctrl *gomock.Controller) *MockvmState { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvmState) EXPECT() *MockvmStateMockRecorder {
	_ = "STUB: not implemented"

	// Apply mocks base method.
	return nil
}

func (m *MockvmState) Apply(arg0 types.LayerID, arg1 []types.Transaction, arg2 []types.CoinbaseReward) ([]types.Transaction, []types.TransactionWithResult, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

// Apply indicates an expected call of Apply.
func (mr *MockvmStateMockRecorder) Apply(arg0, arg1, arg2 any) *MockvmStateApplyCall {
	_ = "STUB: not implemented"
	return nil
}

// MockvmStateApplyCall wrap *gomock.Call
type MockvmStateApplyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockvmStateApplyCall) Return(arg0 []types.Transaction, arg1 []types.TransactionWithResult, arg2 error) *MockvmStateApplyCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockvmStateApplyCall) Do(f func(types.LayerID, []types.Transaction, []types.CoinbaseReward) ([]types.Transaction, []types.TransactionWithResult, error)) *MockvmStateApplyCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockvmStateApplyCall) DoAndReturn(f func(types.LayerID, []types.Transaction, []types.CoinbaseReward) ([]types.Transaction, []types.TransactionWithResult, error)) *MockvmStateApplyCall {
	_ = "STUB: not implemented"
	return nil
}

// GetStateRoot mocks base method.
func (m *MockvmState) GetStateRoot() (types.Hash32, error) {
	_ = "STUB: not implemented"
	return *new(types.Hash32), nil
}

// GetStateRoot indicates an expected call of GetStateRoot.
func (mr *MockvmStateMockRecorder) GetStateRoot() *MockvmStateGetStateRootCall {
	_ = "STUB: not implemented"
	return nil
}

// MockvmStateGetStateRootCall wrap *gomock.Call
type MockvmStateGetStateRootCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockvmStateGetStateRootCall) Return(arg0 types.Hash32, arg1 error) *MockvmStateGetStateRootCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockvmStateGetStateRootCall) Do(f func() (types.Hash32, error)) *MockvmStateGetStateRootCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockvmStateGetStateRootCall) DoAndReturn(f func() (types.Hash32, error)) *MockvmStateGetStateRootCall {
	_ = "STUB: not implemented"
	return nil
}

// Revert mocks base method.
func (m *MockvmState) Revert(arg0 types.LayerID) error { _ = "STUB: not implemented"; return nil }

// Revert indicates an expected call of Revert.
func (mr *MockvmStateMockRecorder) Revert(arg0 any) *MockvmStateRevertCall {
	_ = "STUB: not implemented"
	return nil
}

// MockvmStateRevertCall wrap *gomock.Call
type MockvmStateRevertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockvmStateRevertCall) Return(arg0 error) *MockvmStateRevertCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockvmStateRevertCall) Do(f func(types.LayerID) error) *MockvmStateRevertCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockvmStateRevertCall) DoAndReturn(f func(types.LayerID) error) *MockvmStateRevertCall {
	_ = "STUB: not implemented"
	return nil
}
