// Code generated by MockGen. DO NOT EDIT.
// Source: ./account.go
//
// Generated by this command:
//
//	mockgen -typed -package=v2alpha1 -destination=./account_mocks.go -source=./account.go
//

// Package v2alpha1 is a generated GoMock package.
package v2alpha1

import (
	types "github.com/spacemeshos/go-spacemesh/common/types"
	gomock "go.uber.org/mock/gomock"
)

// MockaccountConState is a mock of accountConState interface.
type MockaccountConState struct {
	ctrl     *gomock.Controller
	recorder *MockaccountConStateMockRecorder
}

// MockaccountConStateMockRecorder is the mock recorder for MockaccountConState.
type MockaccountConStateMockRecorder struct {
	mock *MockaccountConState
}

// NewMockaccountConState creates a new mock instance.
func NewMockaccountConState(ctrl *gomock.Controller) *MockaccountConState {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaccountConState) EXPECT() *MockaccountConStateMockRecorder {
	_ = "STUB: not implemented"

	// GetProjection mocks base method.
	return nil
}

func (m *MockaccountConState) GetProjection(arg0 types.Address) (uint64, uint64) {
	_ = "STUB: not implemented"
	return 0, 0
}

// GetProjection indicates an expected call of GetProjection.
func (mr *MockaccountConStateMockRecorder) GetProjection(arg0 any) *MockaccountConStateGetProjectionCall {
	_ = "STUB: not implemented"
	return nil
}

// MockaccountConStateGetProjectionCall wrap *gomock.Call
type MockaccountConStateGetProjectionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockaccountConStateGetProjectionCall) Return(arg0, arg1 uint64) *MockaccountConStateGetProjectionCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockaccountConStateGetProjectionCall) Do(f func(types.Address) (uint64, uint64)) *MockaccountConStateGetProjectionCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockaccountConStateGetProjectionCall) DoAndReturn(f func(types.Address) (uint64, uint64)) *MockaccountConStateGetProjectionCall {
	_ = "STUB: not implemented"
	return nil
}
