// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -typed -package=v2alpha1 -destination=./mocks.go -source=./interface.go
//

// Package v2alpha1 is a generated GoMock package.
package v2alpha1

import (
	context "context"

	spacemeshv2alpha1 "github.com/spacemeshos/api/release/go/spacemesh/v2alpha1"
	types "github.com/spacemeshos/go-spacemesh/common/types"
	events "github.com/spacemeshos/go-spacemesh/events"
	gomock "go.uber.org/mock/gomock"
)

// MockmalfeasanceInfo is a mock of malfeasanceInfo interface.
type MockmalfeasanceInfo struct {
	ctrl     *gomock.Controller
	recorder *MockmalfeasanceInfoMockRecorder
	isgomock struct{}
}

// MockmalfeasanceInfoMockRecorder is the mock recorder for MockmalfeasanceInfo.
type MockmalfeasanceInfoMockRecorder struct {
	mock *MockmalfeasanceInfo
}

// NewMockmalfeasanceInfo creates a new mock instance.
func NewMockmalfeasanceInfo(ctrl *gomock.Controller) *MockmalfeasanceInfo {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmalfeasanceInfo) EXPECT() *MockmalfeasanceInfoMockRecorder {
	_ = "STUB: not implemented"

	// Info mocks base method.
	return nil
}

func (m *MockmalfeasanceInfo) Info(ctx context.Context, nodeID types.NodeID) (map[string]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Info indicates an expected call of Info.
func (mr *MockmalfeasanceInfoMockRecorder) Info(ctx, nodeID any) *MockmalfeasanceInfoInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// MockmalfeasanceInfoInfoCall wrap *gomock.Call
type MockmalfeasanceInfoInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockmalfeasanceInfoInfoCall) Return(arg0 map[string]string, arg1 error) *MockmalfeasanceInfoInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockmalfeasanceInfoInfoCall) Do(f func(context.Context, types.NodeID) (map[string]string, error)) *MockmalfeasanceInfoInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockmalfeasanceInfoInfoCall) DoAndReturn(f func(context.Context, types.NodeID) (map[string]string, error)) *MockmalfeasanceInfoInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// Mocksyncer is a mock of syncer interface.
type Mocksyncer struct {
	ctrl     *gomock.Controller
	recorder *MocksyncerMockRecorder
	isgomock struct{}
}

// MocksyncerMockRecorder is the mock recorder for Mocksyncer.
type MocksyncerMockRecorder struct {
	mock *Mocksyncer
}

// NewMocksyncer creates a new mock instance.
func NewMocksyncer(ctrl *gomock.Controller) *Mocksyncer { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksyncer) EXPECT() *MocksyncerMockRecorder {
	_ = "STUB: not implemented"

	// IsSynced mocks base method.
	return nil
}

func (m *Mocksyncer) IsSynced(arg0 context.Context) bool { _ = "STUB: not implemented"; return false }

// IsSynced indicates an expected call of IsSynced.
func (mr *MocksyncerMockRecorder) IsSynced(arg0 any) *MocksyncerIsSyncedCall {
	_ = "STUB: not implemented"
	return nil
}

// MocksyncerIsSyncedCall wrap *gomock.Call
type MocksyncerIsSyncedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksyncerIsSyncedCall) Return(arg0 bool) *MocksyncerIsSyncedCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocksyncerIsSyncedCall) Do(f func(context.Context) bool) *MocksyncerIsSyncedCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksyncerIsSyncedCall) DoAndReturn(f func(context.Context) bool) *MocksyncerIsSyncedCall {
	_ = "STUB: not implemented"
	return nil
}

// Mocksubscription is a mock of subscription interface.
type Mocksubscription struct {
	ctrl     *gomock.Controller
	recorder *MocksubscriptionMockRecorder
	isgomock struct{}
}

// MocksubscriptionMockRecorder is the mock recorder for Mocksubscription.
type MocksubscriptionMockRecorder struct {
	mock *Mocksubscription
}

// NewMocksubscription creates a new mock instance.
func NewMocksubscription(ctrl *gomock.Controller) *Mocksubscription {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksubscription) EXPECT() *MocksubscriptionMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *Mocksubscription) Close() { _ = "STUB: not implemented"; return }

// Close indicates an expected call of Close.
func (mr *MocksubscriptionMockRecorder) Close() *MocksubscriptionCloseCall {
	_ = "STUB: not implemented"
	return nil
}

// MocksubscriptionCloseCall wrap *gomock.Call
type MocksubscriptionCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksubscriptionCloseCall) Return() *MocksubscriptionCloseCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocksubscriptionCloseCall) Do(f func()) *MocksubscriptionCloseCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksubscriptionCloseCall) DoAndReturn(f func()) *MocksubscriptionCloseCall {
	_ = "STUB: not implemented"
	return nil
}

// Full mocks base method.
func (m *Mocksubscription) Full() <-chan struct{} { _ = "STUB: not implemented"; return nil }

// Full indicates an expected call of Full.
func (mr *MocksubscriptionMockRecorder) Full() *MocksubscriptionFullCall {
	_ = "STUB: not implemented"
	return nil
}

// MocksubscriptionFullCall wrap *gomock.Call
type MocksubscriptionFullCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksubscriptionFullCall) Return(arg0 <-chan struct{}) *MocksubscriptionFullCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocksubscriptionFullCall) Do(f func() <-chan struct{}) *MocksubscriptionFullCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksubscriptionFullCall) DoAndReturn(f func() <-chan struct{}) *MocksubscriptionFullCall {
	_ = "STUB: not implemented"
	return nil
}

// Out mocks base method.
func (m *Mocksubscription) Out() <-chan events.EventMalfeasance {
	_ = "STUB: not implemented"
	return nil
}

// Out indicates an expected call of Out.
func (mr *MocksubscriptionMockRecorder) Out() *MocksubscriptionOutCall {
	_ = "STUB: not implemented"
	return nil
}

// MocksubscriptionOutCall wrap *gomock.Call
type MocksubscriptionOutCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksubscriptionOutCall) Return(arg0 <-chan events.EventMalfeasance) *MocksubscriptionOutCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocksubscriptionOutCall) Do(f func() <-chan events.EventMalfeasance) *MocksubscriptionOutCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksubscriptionOutCall) DoAndReturn(f func() <-chan events.EventMalfeasance) *MocksubscriptionOutCall {
	_ = "STUB: not implemented"
	return nil
}

// MockeventProvider is a mock of eventProvider interface.
type MockeventProvider struct {
	ctrl     *gomock.Controller
	recorder *MockeventProviderMockRecorder
	isgomock struct{}
}

// MockeventProviderMockRecorder is the mock recorder for MockeventProvider.
type MockeventProviderMockRecorder struct {
	mock *MockeventProvider
}

// NewMockeventProvider creates a new mock instance.
func NewMockeventProvider(ctrl *gomock.Controller) *MockeventProvider {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockeventProvider) EXPECT() *MockeventProviderMockRecorder {
	_ = "STUB: not implemented"

	// SubscribeMatched mocks base method.
	return nil
}

func (m *MockeventProvider) SubscribeMatched(request *spacemeshv2alpha1.MalfeasanceStreamRequest) (subscription, error) {
	_ = "STUB: not implemented"
	return *new(subscription), nil
}

// SubscribeMatched indicates an expected call of SubscribeMatched.
func (mr *MockeventProviderMockRecorder) SubscribeMatched(request any) *MockeventProviderSubscribeMatchedCall {
	_ = "STUB: not implemented"
	return nil
}

// MockeventProviderSubscribeMatchedCall wrap *gomock.Call
type MockeventProviderSubscribeMatchedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockeventProviderSubscribeMatchedCall) Return(arg0 subscription, arg1 error) *MockeventProviderSubscribeMatchedCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockeventProviderSubscribeMatchedCall) Do(f func(*spacemeshv2alpha1.MalfeasanceStreamRequest) (subscription, error)) *MockeventProviderSubscribeMatchedCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockeventProviderSubscribeMatchedCall) DoAndReturn(f func(*spacemeshv2alpha1.MalfeasanceStreamRequest) (subscription, error)) *MockeventProviderSubscribeMatchedCall {
	_ = "STUB: not implemented"
	return nil
}
