// Code generated by MockGen. DO NOT EDIT.
// Source: ./transaction.go
//
// Generated by this command:
//
//	mockgen -typed -package=v2alpha1 -destination=./transaction_mocks.go -source=./transaction.go
//

// Package v2alpha1 is a generated GoMock package.
package v2alpha1

import (
	context "context"

	types "github.com/spacemeshos/go-spacemesh/common/types"
	system "github.com/spacemeshos/go-spacemesh/system"
	gomock "go.uber.org/mock/gomock"
)

// MocktransactionConState is a mock of transactionConState interface.
type MocktransactionConState struct {
	ctrl     *gomock.Controller
	recorder *MocktransactionConStateMockRecorder
	isgomock struct{}
}

// MocktransactionConStateMockRecorder is the mock recorder for MocktransactionConState.
type MocktransactionConStateMockRecorder struct {
	mock *MocktransactionConState
}

// NewMocktransactionConState creates a new mock instance.
func NewMocktransactionConState(ctrl *gomock.Controller) *MocktransactionConState {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktransactionConState) EXPECT() *MocktransactionConStateMockRecorder {
	_ = "STUB: not implemented"

	// HasEvicted mocks base method.
	return nil
}

func (m *MocktransactionConState) HasEvicted(tid types.TransactionID) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// HasEvicted indicates an expected call of HasEvicted.
func (mr *MocktransactionConStateMockRecorder) HasEvicted(tid any) *MocktransactionConStateHasEvictedCall {
	_ = "STUB: not implemented"
	return nil
}

// MocktransactionConStateHasEvictedCall wrap *gomock.Call
type MocktransactionConStateHasEvictedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocktransactionConStateHasEvictedCall) Return(arg0 bool, arg1 error) *MocktransactionConStateHasEvictedCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocktransactionConStateHasEvictedCall) Do(f func(types.TransactionID) (bool, error)) *MocktransactionConStateHasEvictedCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocktransactionConStateHasEvictedCall) DoAndReturn(f func(types.TransactionID) (bool, error)) *MocktransactionConStateHasEvictedCall {
	_ = "STUB: not implemented"
	return nil
}

// Validation mocks base method.
func (m *MocktransactionConState) Validation(raw types.RawTx) system.ValidationRequest {
	_ = "STUB: not implemented"
	return *new(system.ValidationRequest)
}

// Validation indicates an expected call of Validation.
func (mr *MocktransactionConStateMockRecorder) Validation(raw any) *MocktransactionConStateValidationCall {
	_ = "STUB: not implemented"
	return nil
}

// MocktransactionConStateValidationCall wrap *gomock.Call
type MocktransactionConStateValidationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocktransactionConStateValidationCall) Return(arg0 system.ValidationRequest) *MocktransactionConStateValidationCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocktransactionConStateValidationCall) Do(f func(types.RawTx) system.ValidationRequest) *MocktransactionConStateValidationCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocktransactionConStateValidationCall) DoAndReturn(f func(types.RawTx) system.ValidationRequest) *MocktransactionConStateValidationCall {
	_ = "STUB: not implemented"
	return nil
}

// MocktransactionSyncer is a mock of transactionSyncer interface.
type MocktransactionSyncer struct {
	ctrl     *gomock.Controller
	recorder *MocktransactionSyncerMockRecorder
	isgomock struct{}
}

// MocktransactionSyncerMockRecorder is the mock recorder for MocktransactionSyncer.
type MocktransactionSyncerMockRecorder struct {
	mock *MocktransactionSyncer
}

// NewMocktransactionSyncer creates a new mock instance.
func NewMocktransactionSyncer(ctrl *gomock.Controller) *MocktransactionSyncer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktransactionSyncer) EXPECT() *MocktransactionSyncerMockRecorder {
	_ = "STUB: not implemented"

	// IsSynced mocks base method.
	return nil
}

func (m *MocktransactionSyncer) IsSynced(arg0 context.Context) bool {
	_ = "STUB: not implemented"
	return false
}

// IsSynced indicates an expected call of IsSynced.
func (mr *MocktransactionSyncerMockRecorder) IsSynced(arg0 any) *MocktransactionSyncerIsSyncedCall {
	_ = "STUB: not implemented"
	return nil
}

// MocktransactionSyncerIsSyncedCall wrap *gomock.Call
type MocktransactionSyncerIsSyncedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocktransactionSyncerIsSyncedCall) Return(arg0 bool) *MocktransactionSyncerIsSyncedCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocktransactionSyncerIsSyncedCall) Do(f func(context.Context) bool) *MocktransactionSyncerIsSyncedCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocktransactionSyncerIsSyncedCall) DoAndReturn(f func(context.Context) bool) *MocktransactionSyncerIsSyncedCall {
	_ = "STUB: not implemented"
	return nil
}

// MocktransactionValidator is a mock of transactionValidator interface.
type MocktransactionValidator struct {
	ctrl     *gomock.Controller
	recorder *MocktransactionValidatorMockRecorder
	isgomock struct{}
}

// MocktransactionValidatorMockRecorder is the mock recorder for MocktransactionValidator.
type MocktransactionValidatorMockRecorder struct {
	mock *MocktransactionValidator
}

// NewMocktransactionValidator creates a new mock instance.
func NewMocktransactionValidator(ctrl *gomock.Controller) *MocktransactionValidator {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktransactionValidator) EXPECT() *MocktransactionValidatorMockRecorder {
	_ = "STUB: not implemented"

	// VerifyAndCacheTx mocks base method.
	return nil
}

func (m *MocktransactionValidator) VerifyAndCacheTx(arg0 context.Context, arg1 []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// VerifyAndCacheTx indicates an expected call of VerifyAndCacheTx.
func (mr *MocktransactionValidatorMockRecorder) VerifyAndCacheTx(arg0, arg1 any) *MocktransactionValidatorVerifyAndCacheTxCall {
	_ = "STUB: not implemented"
	return nil
}

// MocktransactionValidatorVerifyAndCacheTxCall wrap *gomock.Call
type MocktransactionValidatorVerifyAndCacheTxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocktransactionValidatorVerifyAndCacheTxCall) Return(arg0 error) *MocktransactionValidatorVerifyAndCacheTxCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocktransactionValidatorVerifyAndCacheTxCall) Do(f func(context.Context, []byte) error) *MocktransactionValidatorVerifyAndCacheTxCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocktransactionValidatorVerifyAndCacheTxCall) DoAndReturn(f func(context.Context, []byte) error) *MocktransactionValidatorVerifyAndCacheTxCall {
	_ = "STUB: not implemented"
	return nil
}
