// Code generated by MockGen. DO NOT EDIT.
// Source: ./node.go
//
// Generated by this command:
//
//	mockgen -typed -package=v2beta1 -destination=./node_mocks.go -source=./node.go
//

// Package v2beta1 is a generated GoMock package.
package v2beta1

import (
	context "context"

	types "github.com/spacemeshos/go-spacemesh/common/types"
	gomock "go.uber.org/mock/gomock"
)

// MocknodePeerCounter is a mock of nodePeerCounter interface.
type MocknodePeerCounter struct {
	ctrl     *gomock.Controller
	recorder *MocknodePeerCounterMockRecorder
}

// MocknodePeerCounterMockRecorder is the mock recorder for MocknodePeerCounter.
type MocknodePeerCounterMockRecorder struct {
	mock *MocknodePeerCounter
}

// NewMocknodePeerCounter creates a new mock instance.
func NewMocknodePeerCounter(ctrl *gomock.Controller) *MocknodePeerCounter {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknodePeerCounter) EXPECT() *MocknodePeerCounterMockRecorder {
	_ = "STUB: not implemented"

	// PeerCount mocks base method.
	return nil
}

func (m *MocknodePeerCounter) PeerCount() uint64 { _ = "STUB: not implemented"; return 0 }

// PeerCount indicates an expected call of PeerCount.
func (mr *MocknodePeerCounterMockRecorder) PeerCount() *MocknodePeerCounterPeerCountCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknodePeerCounterPeerCountCall wrap *gomock.Call
type MocknodePeerCounterPeerCountCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknodePeerCounterPeerCountCall) Return(arg0 uint64) *MocknodePeerCounterPeerCountCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknodePeerCounterPeerCountCall) Do(f func() uint64) *MocknodePeerCounterPeerCountCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknodePeerCounterPeerCountCall) DoAndReturn(f func() uint64) *MocknodePeerCounterPeerCountCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknodeMeshAPI is a mock of nodeMeshAPI interface.
type MocknodeMeshAPI struct {
	ctrl     *gomock.Controller
	recorder *MocknodeMeshAPIMockRecorder
}

// MocknodeMeshAPIMockRecorder is the mock recorder for MocknodeMeshAPI.
type MocknodeMeshAPIMockRecorder struct {
	mock *MocknodeMeshAPI
}

// NewMocknodeMeshAPI creates a new mock instance.
func NewMocknodeMeshAPI(ctrl *gomock.Controller) *MocknodeMeshAPI {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknodeMeshAPI) EXPECT() *MocknodeMeshAPIMockRecorder {
	_ = "STUB: not implemented"

	// LatestLayer mocks base method.
	return nil
}

func (m *MocknodeMeshAPI) LatestLayer() types.LayerID {
	_ = "STUB: not implemented"
	return *new(types.LayerID)
}

// LatestLayer indicates an expected call of LatestLayer.
func (mr *MocknodeMeshAPIMockRecorder) LatestLayer() *MocknodeMeshAPILatestLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknodeMeshAPILatestLayerCall wrap *gomock.Call
type MocknodeMeshAPILatestLayerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknodeMeshAPILatestLayerCall) Return(arg0 types.LayerID) *MocknodeMeshAPILatestLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknodeMeshAPILatestLayerCall) Do(f func() types.LayerID) *MocknodeMeshAPILatestLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknodeMeshAPILatestLayerCall) DoAndReturn(f func() types.LayerID) *MocknodeMeshAPILatestLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// LatestLayerInState mocks base method.
func (m *MocknodeMeshAPI) LatestLayerInState() types.LayerID {
	_ = "STUB: not implemented"
	return *new(types.LayerID)
}

// LatestLayerInState indicates an expected call of LatestLayerInState.
func (mr *MocknodeMeshAPIMockRecorder) LatestLayerInState() *MocknodeMeshAPILatestLayerInStateCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknodeMeshAPILatestLayerInStateCall wrap *gomock.Call
type MocknodeMeshAPILatestLayerInStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknodeMeshAPILatestLayerInStateCall) Return(arg0 types.LayerID) *MocknodeMeshAPILatestLayerInStateCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknodeMeshAPILatestLayerInStateCall) Do(f func() types.LayerID) *MocknodeMeshAPILatestLayerInStateCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknodeMeshAPILatestLayerInStateCall) DoAndReturn(f func() types.LayerID) *MocknodeMeshAPILatestLayerInStateCall {
	_ = "STUB: not implemented"
	return nil
}

// ProcessedLayer mocks base method.
func (m *MocknodeMeshAPI) ProcessedLayer() types.LayerID {
	_ = "STUB: not implemented"
	return *new(types.LayerID)
}

// ProcessedLayer indicates an expected call of ProcessedLayer.
func (mr *MocknodeMeshAPIMockRecorder) ProcessedLayer() *MocknodeMeshAPIProcessedLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknodeMeshAPIProcessedLayerCall wrap *gomock.Call
type MocknodeMeshAPIProcessedLayerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknodeMeshAPIProcessedLayerCall) Return(arg0 types.LayerID) *MocknodeMeshAPIProcessedLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknodeMeshAPIProcessedLayerCall) Do(f func() types.LayerID) *MocknodeMeshAPIProcessedLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknodeMeshAPIProcessedLayerCall) DoAndReturn(f func() types.LayerID) *MocknodeMeshAPIProcessedLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknodeSyncer is a mock of nodeSyncer interface.
type MocknodeSyncer struct {
	ctrl     *gomock.Controller
	recorder *MocknodeSyncerMockRecorder
}

// MocknodeSyncerMockRecorder is the mock recorder for MocknodeSyncer.
type MocknodeSyncerMockRecorder struct {
	mock *MocknodeSyncer
}

// NewMocknodeSyncer creates a new mock instance.
func NewMocknodeSyncer(ctrl *gomock.Controller) *MocknodeSyncer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknodeSyncer) EXPECT() *MocknodeSyncerMockRecorder {
	_ = "STUB: not implemented"

	// IsSynced mocks base method.
	return nil
}

func (m *MocknodeSyncer) IsSynced(arg0 context.Context) bool {
	_ = "STUB: not implemented"
	return false
}

// IsSynced indicates an expected call of IsSynced.
func (mr *MocknodeSyncerMockRecorder) IsSynced(arg0 any) *MocknodeSyncerIsSyncedCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknodeSyncerIsSyncedCall wrap *gomock.Call
type MocknodeSyncerIsSyncedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknodeSyncerIsSyncedCall) Return(arg0 bool) *MocknodeSyncerIsSyncedCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknodeSyncerIsSyncedCall) Do(f func(context.Context) bool) *MocknodeSyncerIsSyncedCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknodeSyncerIsSyncedCall) DoAndReturn(f func(context.Context) bool) *MocknodeSyncerIsSyncedCall {
	_ = "STUB: not implemented"
	return nil
}
