// Code generated by MockGen. DO NOT EDIT.
// Source: ./blocks.go
//
// Generated by this command:
//
//	mockgen -typed -package=blockssync -destination=./mocks.go -source=./blocks.go
//

// Package blockssync is a generated GoMock package.
package blockssync

import (
	context "context"

	types "github.com/spacemeshos/go-spacemesh/common/types"
	gomock "go.uber.org/mock/gomock"
)

// MockblockFetcher is a mock of blockFetcher interface.
type MockblockFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockblockFetcherMockRecorder
	isgomock struct{}
}

// MockblockFetcherMockRecorder is the mock recorder for MockblockFetcher.
type MockblockFetcherMockRecorder struct {
	mock *MockblockFetcher
}

// NewMockblockFetcher creates a new mock instance.
func NewMockblockFetcher(ctrl *gomock.Controller) *MockblockFetcher {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockblockFetcher) EXPECT() *MockblockFetcherMockRecorder {
	_ = "STUB: not implemented"

	// GetBlocks mocks base method.
	return nil
}

func (m *MockblockFetcher) GetBlocks(arg0 context.Context, arg1 []types.BlockID) error {
	_ = "STUB: not implemented"
	return nil
}

// GetBlocks indicates an expected call of GetBlocks.
func (mr *MockblockFetcherMockRecorder) GetBlocks(arg0, arg1 any) *MockblockFetcherGetBlocksCall {
	_ = "STUB: not implemented"
	return nil
}

// MockblockFetcherGetBlocksCall wrap *gomock.Call
type MockblockFetcherGetBlocksCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockblockFetcherGetBlocksCall) Return(arg0 error) *MockblockFetcherGetBlocksCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockblockFetcherGetBlocksCall) Do(f func(context.Context, []types.BlockID) error) *MockblockFetcherGetBlocksCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockblockFetcherGetBlocksCall) DoAndReturn(f func(context.Context, []types.BlockID) error) *MockblockFetcherGetBlocksCall {
	_ = "STUB: not implemented"
	return nil
}
