// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -typed -package=weakcoin -destination=./mocks.go -source=./interface.go
//

// Package weakcoin is a generated GoMock package.
package weakcoin

import (
	types "github.com/spacemeshos/go-spacemesh/common/types"
	gomock "go.uber.org/mock/gomock"
)

// MockvrfSigner is a mock of vrfSigner interface.
type MockvrfSigner struct {
	ctrl     *gomock.Controller
	recorder *MockvrfSignerMockRecorder
	isgomock struct{}
}

// MockvrfSignerMockRecorder is the mock recorder for MockvrfSigner.
type MockvrfSignerMockRecorder struct {
	mock *MockvrfSigner
}

// NewMockvrfSigner creates a new mock instance.
func NewMockvrfSigner(ctrl *gomock.Controller) *MockvrfSigner {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvrfSigner) EXPECT() *MockvrfSignerMockRecorder {
	_ = "STUB: not implemented"

	// NodeID mocks base method.
	return nil
}

func (m *MockvrfSigner) NodeID() types.NodeID { _ = "STUB: not implemented"; return *new(types.NodeID) }

// NodeID indicates an expected call of NodeID.
func (mr *MockvrfSignerMockRecorder) NodeID() *MockvrfSignerNodeIDCall {
	_ = "STUB: not implemented"
	return nil
}

// MockvrfSignerNodeIDCall wrap *gomock.Call
type MockvrfSignerNodeIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockvrfSignerNodeIDCall) Return(arg0 types.NodeID) *MockvrfSignerNodeIDCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockvrfSignerNodeIDCall) Do(f func() types.NodeID) *MockvrfSignerNodeIDCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockvrfSignerNodeIDCall) DoAndReturn(f func() types.NodeID) *MockvrfSignerNodeIDCall {
	_ = "STUB: not implemented"
	return nil
}

// Sign mocks base method.
func (m *MockvrfSigner) Sign(msg []byte) types.VrfSignature {
	_ = "STUB: not implemented"
	return *new(types.VrfSignature)
}

// Sign indicates an expected call of Sign.
func (mr *MockvrfSignerMockRecorder) Sign(msg any) *MockvrfSignerSignCall {
	_ = "STUB: not implemented"
	return nil
}

// MockvrfSignerSignCall wrap *gomock.Call
type MockvrfSignerSignCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockvrfSignerSignCall) Return(arg0 types.VrfSignature) *MockvrfSignerSignCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockvrfSignerSignCall) Do(f func([]byte) types.VrfSignature) *MockvrfSignerSignCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockvrfSignerSignCall) DoAndReturn(f func([]byte) types.VrfSignature) *MockvrfSignerSignCall {
	_ = "STUB: not implemented"
	return nil
}

// MockvrfVerifier is a mock of vrfVerifier interface.
type MockvrfVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockvrfVerifierMockRecorder
	isgomock struct{}
}

// MockvrfVerifierMockRecorder is the mock recorder for MockvrfVerifier.
type MockvrfVerifierMockRecorder struct {
	mock *MockvrfVerifier
}

// NewMockvrfVerifier creates a new mock instance.
func NewMockvrfVerifier(ctrl *gomock.Controller) *MockvrfVerifier {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvrfVerifier) EXPECT() *MockvrfVerifierMockRecorder {
	_ = "STUB: not implemented"

	// Verify mocks base method.
	return nil
}

func (m *MockvrfVerifier) Verify(nodeID types.NodeID, msg []byte, sig types.VrfSignature) bool {
	_ = "STUB: not implemented"
	return false
}

// Verify indicates an expected call of Verify.
func (mr *MockvrfVerifierMockRecorder) Verify(nodeID, msg, sig any) *MockvrfVerifierVerifyCall {
	_ = "STUB: not implemented"
	return nil
}

// MockvrfVerifierVerifyCall wrap *gomock.Call
type MockvrfVerifierVerifyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockvrfVerifierVerifyCall) Return(arg0 bool) *MockvrfVerifierVerifyCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockvrfVerifierVerifyCall) Do(f func(types.NodeID, []byte, types.VrfSignature) bool) *MockvrfVerifierVerifyCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockvrfVerifierVerifyCall) DoAndReturn(f func(types.NodeID, []byte, types.VrfSignature) bool) *MockvrfVerifierVerifyCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknonceFetcher is a mock of nonceFetcher interface.
type MocknonceFetcher struct {
	ctrl     *gomock.Controller
	recorder *MocknonceFetcherMockRecorder
	isgomock struct{}
}

// MocknonceFetcherMockRecorder is the mock recorder for MocknonceFetcher.
type MocknonceFetcherMockRecorder struct {
	mock *MocknonceFetcher
}

// NewMocknonceFetcher creates a new mock instance.
func NewMocknonceFetcher(ctrl *gomock.Controller) *MocknonceFetcher {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknonceFetcher) EXPECT() *MocknonceFetcherMockRecorder {
	_ = "STUB: not implemented"

	// VRFNonce mocks base method.
	return nil
}

func (m *MocknonceFetcher) VRFNonce(arg0 types.NodeID, arg1 types.EpochID) (types.VRFPostIndex, error) {
	_ = "STUB: not implemented"
	return *new(types.VRFPostIndex), nil
}

// VRFNonce indicates an expected call of VRFNonce.
func (mr *MocknonceFetcherMockRecorder) VRFNonce(arg0, arg1 any) *MocknonceFetcherVRFNonceCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknonceFetcherVRFNonceCall wrap *gomock.Call
type MocknonceFetcherVRFNonceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknonceFetcherVRFNonceCall) Return(arg0 types.VRFPostIndex, arg1 error) *MocknonceFetcherVRFNonceCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknonceFetcherVRFNonceCall) Do(f func(types.NodeID, types.EpochID) (types.VRFPostIndex, error)) *MocknonceFetcherVRFNonceCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknonceFetcherVRFNonceCall) DoAndReturn(f func(types.NodeID, types.EpochID) (types.VRFPostIndex, error)) *MocknonceFetcherVRFNonceCall {
	_ = "STUB: not implemented"
	return nil
}

// Mockallowance is a mock of allowance interface.
type Mockallowance struct {
	ctrl     *gomock.Controller
	recorder *MockallowanceMockRecorder
	isgomock struct{}
}

// MockallowanceMockRecorder is the mock recorder for Mockallowance.
type MockallowanceMockRecorder struct {
	mock *Mockallowance
}

// NewMockallowance creates a new mock instance.
func NewMockallowance(ctrl *gomock.Controller) *Mockallowance {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockallowance) EXPECT() *MockallowanceMockRecorder {
	_ = "STUB: not implemented"

	// MinerAllowance mocks base method.
	return nil
}

func (m *Mockallowance) MinerAllowance(arg0 types.EpochID, arg1 types.NodeID) uint32 {
	_ = "STUB: not implemented"
	return 0
}

// MinerAllowance indicates an expected call of MinerAllowance.
func (mr *MockallowanceMockRecorder) MinerAllowance(arg0, arg1 any) *MockallowanceMinerAllowanceCall {
	_ = "STUB: not implemented"
	return nil
}

// MockallowanceMinerAllowanceCall wrap *gomock.Call
type MockallowanceMinerAllowanceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockallowanceMinerAllowanceCall) Return(arg0 uint32) *MockallowanceMinerAllowanceCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockallowanceMinerAllowanceCall) Do(f func(types.EpochID, types.NodeID) uint32) *MockallowanceMinerAllowanceCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockallowanceMinerAllowanceCall) DoAndReturn(f func(types.EpochID, types.NodeID) uint32) *MockallowanceMinerAllowanceCall {
	_ = "STUB: not implemented"
	return nil
}
