// Code generated by github.com/spacemeshos/go-scale/scalegen. DO NOT EDIT.

// nolint
package wire

import (
	"github.com/spacemeshos/go-scale"
)

func (t *MalfeasanceProof) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *MalfeasanceProof) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *MalfeasanceGossip) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *MalfeasanceGossip) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *AtxProof) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *AtxProof) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *BallotProof) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *BallotProof) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *HareProof) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *HareProof) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *AtxProofMsg) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *AtxProofMsg) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *BallotProofMsg) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *BallotProofMsg) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *HareProofMsg) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *HareProofMsg) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *HareMetadata) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *HareMetadata) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *InvalidPostIndexProof) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *InvalidPostIndexProof) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *InvalidPrevATXProof) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *InvalidPrevATXProof) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}
