// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -typed -package=malfeasance2 -destination=./mocks.go -source=./interface.go
//

// Package malfeasance2 is a generated GoMock package.
package malfeasance2

import (
	context "context"

	types "github.com/spacemeshos/go-spacemesh/common/types"
	gomock "go.uber.org/mock/gomock"
)

// Mocktortoise is a mock of tortoise interface.
type Mocktortoise struct {
	ctrl     *gomock.Controller
	recorder *MocktortoiseMockRecorder
	isgomock struct{}
}

// MocktortoiseMockRecorder is the mock recorder for Mocktortoise.
type MocktortoiseMockRecorder struct {
	mock *Mocktortoise
}

// NewMocktortoise creates a new mock instance.
func NewMocktortoise(ctrl *gomock.Controller) *Mocktortoise { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocktortoise) EXPECT() *MocktortoiseMockRecorder {
	_ = "STUB: not implemented"

	// OnMalfeasance mocks base method.
	return nil
}

func (m *Mocktortoise) OnMalfeasance(arg0 types.NodeID) { _ = "STUB: not implemented"; return }

// OnMalfeasance indicates an expected call of OnMalfeasance.
func (mr *MocktortoiseMockRecorder) OnMalfeasance(arg0 any) *MocktortoiseOnMalfeasanceCall {
	_ = "STUB: not implemented"
	return nil
}

// MocktortoiseOnMalfeasanceCall wrap *gomock.Call
type MocktortoiseOnMalfeasanceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocktortoiseOnMalfeasanceCall) Return() *MocktortoiseOnMalfeasanceCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocktortoiseOnMalfeasanceCall) Do(f func(types.NodeID)) *MocktortoiseOnMalfeasanceCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocktortoiseOnMalfeasanceCall) DoAndReturn(f func(types.NodeID)) *MocktortoiseOnMalfeasanceCall {
	_ = "STUB: not implemented"
	return nil
}

// Mocksyncer is a mock of syncer interface.
type Mocksyncer struct {
	ctrl     *gomock.Controller
	recorder *MocksyncerMockRecorder
	isgomock struct{}
}

// MocksyncerMockRecorder is the mock recorder for Mocksyncer.
type MocksyncerMockRecorder struct {
	mock *Mocksyncer
}

// NewMocksyncer creates a new mock instance.
func NewMocksyncer(ctrl *gomock.Controller) *Mocksyncer { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksyncer) EXPECT() *MocksyncerMockRecorder {
	_ = "STUB: not implemented"

	// ListenToATXGossip mocks base method.
	return nil
}

func (m *Mocksyncer) ListenToATXGossip() bool { _ = "STUB: not implemented"; return false }

// ListenToATXGossip indicates an expected call of ListenToATXGossip.
func (mr *MocksyncerMockRecorder) ListenToATXGossip() *MocksyncerListenToATXGossipCall {
	_ = "STUB: not implemented"
	return nil
}

// MocksyncerListenToATXGossipCall wrap *gomock.Call
type MocksyncerListenToATXGossipCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksyncerListenToATXGossipCall) Return(arg0 bool) *MocksyncerListenToATXGossipCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocksyncerListenToATXGossipCall) Do(f func() bool) *MocksyncerListenToATXGossipCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksyncerListenToATXGossipCall) DoAndReturn(f func() bool) *MocksyncerListenToATXGossipCall {
	_ = "STUB: not implemented"
	return nil
}

// MockMalfeasanceHandler is a mock of MalfeasanceHandler interface.
type MockMalfeasanceHandler struct {
	ctrl     *gomock.Controller
	recorder *MockMalfeasanceHandlerMockRecorder
	isgomock struct{}
}

// MockMalfeasanceHandlerMockRecorder is the mock recorder for MockMalfeasanceHandler.
type MockMalfeasanceHandlerMockRecorder struct {
	mock *MockMalfeasanceHandler
}

// NewMockMalfeasanceHandler creates a new mock instance.
func NewMockMalfeasanceHandler(ctrl *gomock.Controller) *MockMalfeasanceHandler {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMalfeasanceHandler) EXPECT() *MockMalfeasanceHandlerMockRecorder {
	_ = "STUB: not implemented"

	// Info mocks base method.
	return nil
}

func (m *MockMalfeasanceHandler) Info(data []byte) (map[string]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Info indicates an expected call of Info.
func (mr *MockMalfeasanceHandlerMockRecorder) Info(data any) *MockMalfeasanceHandlerInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// MockMalfeasanceHandlerInfoCall wrap *gomock.Call
type MockMalfeasanceHandlerInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMalfeasanceHandlerInfoCall) Return(arg0 map[string]string, arg1 error) *MockMalfeasanceHandlerInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockMalfeasanceHandlerInfoCall) Do(f func([]byte) (map[string]string, error)) *MockMalfeasanceHandlerInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMalfeasanceHandlerInfoCall) DoAndReturn(f func([]byte) (map[string]string, error)) *MockMalfeasanceHandlerInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// ReportLabels mocks base method.
func (m *MockMalfeasanceHandler) ReportLabels(data []byte) []string {
	_ = "STUB: not implemented"
	return nil
}

// ReportLabels indicates an expected call of ReportLabels.
func (mr *MockMalfeasanceHandlerMockRecorder) ReportLabels(data any) *MockMalfeasanceHandlerReportLabelsCall {
	_ = "STUB: not implemented"
	return nil
}

// MockMalfeasanceHandlerReportLabelsCall wrap *gomock.Call
type MockMalfeasanceHandlerReportLabelsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMalfeasanceHandlerReportLabelsCall) Return(arg0 []string) *MockMalfeasanceHandlerReportLabelsCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockMalfeasanceHandlerReportLabelsCall) Do(f func([]byte) []string) *MockMalfeasanceHandlerReportLabelsCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMalfeasanceHandlerReportLabelsCall) DoAndReturn(f func([]byte) []string) *MockMalfeasanceHandlerReportLabelsCall {
	_ = "STUB: not implemented"
	return nil
}

// Validate mocks base method.
func (m *MockMalfeasanceHandler) Validate(ctx context.Context, data []byte) (types.NodeID, error) {
	_ = "STUB: not implemented"
	return *new(types.NodeID), nil
}

// Validate indicates an expected call of Validate.
func (mr *MockMalfeasanceHandlerMockRecorder) Validate(ctx, data any) *MockMalfeasanceHandlerValidateCall {
	_ = "STUB: not implemented"
	return nil
}

// MockMalfeasanceHandlerValidateCall wrap *gomock.Call
type MockMalfeasanceHandlerValidateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMalfeasanceHandlerValidateCall) Return(arg0 types.NodeID, arg1 error) *MockMalfeasanceHandlerValidateCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockMalfeasanceHandlerValidateCall) Do(f func(context.Context, []byte) (types.NodeID, error)) *MockMalfeasanceHandlerValidateCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMalfeasanceHandlerValidateCall) DoAndReturn(f func(context.Context, []byte) (types.NodeID, error)) *MockMalfeasanceHandlerValidateCall {
	_ = "STUB: not implemented"
	return nil
}
