// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -typed -package=activation -destination=./mocks.go -source=./interface.go
//

// Package activation is a generated GoMock package.
package activation

import (
	context "context"
	url "net/url"
	time "time"

	wire "github.com/spacemeshos/go-spacemesh/activation/wire"
	types "github.com/spacemeshos/go-spacemesh/common/types"
	wire0 "github.com/spacemeshos/go-spacemesh/malfeasance/wire"
	signing "github.com/spacemeshos/go-spacemesh/signing"
	certifier "github.com/spacemeshos/go-spacemesh/sql/localsql/certifier"
	nipost "github.com/spacemeshos/go-spacemesh/sql/localsql/nipost"
	shared "github.com/spacemeshos/post/shared"
	gomock "go.uber.org/mock/gomock"
)

// MockatxReceiver is a mock of atxReceiver interface.
type MockatxReceiver struct {
	ctrl     *gomock.Controller
	recorder *MockatxReceiverMockRecorder
	isgomock struct{}
}

// MockatxReceiverMockRecorder is the mock recorder for MockatxReceiver.
type MockatxReceiverMockRecorder struct {
	mock *MockatxReceiver
}

// NewMockatxReceiver creates a new mock instance.
func NewMockatxReceiver(ctrl *gomock.Controller) *MockatxReceiver {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockatxReceiver) EXPECT() *MockatxReceiverMockRecorder {
	_ = "STUB: not implemented"

	// OnAtx mocks base method.
	return nil
}

func (m *MockatxReceiver) OnAtx(arg0 *types.ActivationTx) { _ = "STUB: not implemented"; return }

// OnAtx indicates an expected call of OnAtx.
func (mr *MockatxReceiverMockRecorder) OnAtx(arg0 any) *MockatxReceiverOnAtxCall {
	_ = "STUB: not implemented"
	return nil
}

// MockatxReceiverOnAtxCall wrap *gomock.Call
type MockatxReceiverOnAtxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockatxReceiverOnAtxCall) Return() *MockatxReceiverOnAtxCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockatxReceiverOnAtxCall) Do(f func(*types.ActivationTx)) *MockatxReceiverOnAtxCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockatxReceiverOnAtxCall) DoAndReturn(f func(*types.ActivationTx)) *MockatxReceiverOnAtxCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPostVerifier is a mock of PostVerifier interface.
type MockPostVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockPostVerifierMockRecorder
	isgomock struct{}
}

// MockPostVerifierMockRecorder is the mock recorder for MockPostVerifier.
type MockPostVerifierMockRecorder struct {
	mock *MockPostVerifier
}

// NewMockPostVerifier creates a new mock instance.
func NewMockPostVerifier(ctrl *gomock.Controller) *MockPostVerifier {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostVerifier) EXPECT() *MockPostVerifierMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockPostVerifier) Close() error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockPostVerifierMockRecorder) Close() *MockPostVerifierCloseCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPostVerifierCloseCall wrap *gomock.Call
type MockPostVerifierCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPostVerifierCloseCall) Return(arg0 error) *MockPostVerifierCloseCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPostVerifierCloseCall) Do(f func() error) *MockPostVerifierCloseCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPostVerifierCloseCall) DoAndReturn(f func() error) *MockPostVerifierCloseCall {
	_ = "STUB: not implemented"
	return nil
}

// Verify mocks base method.
func (m_2 *MockPostVerifier) Verify(ctx context.Context, p *shared.Proof, m *shared.ProofMetadata, opts ...postVerifierOptionFunc) error {
	_ = "STUB: not implemented"
	return nil
}

// Verify indicates an expected call of Verify.
func (mr *MockPostVerifierMockRecorder) Verify(ctx, p, m any, opts ...any) *MockPostVerifierVerifyCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPostVerifierVerifyCall wrap *gomock.Call
type MockPostVerifierVerifyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPostVerifierVerifyCall) Return(arg0 error) *MockPostVerifierVerifyCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPostVerifierVerifyCall) Do(f func(context.Context, *shared.Proof, *shared.ProofMetadata, ...postVerifierOptionFunc) error) *MockPostVerifierVerifyCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPostVerifierVerifyCall) DoAndReturn(f func(context.Context, *shared.Proof, *shared.ProofMetadata, ...postVerifierOptionFunc) error) *MockPostVerifierVerifyCall {
	_ = "STUB: not implemented"
	return nil
}

// Mockscaler is a mock of scaler interface.
type Mockscaler struct {
	ctrl     *gomock.Controller
	recorder *MockscalerMockRecorder
	isgomock struct{}
}

// MockscalerMockRecorder is the mock recorder for Mockscaler.
type MockscalerMockRecorder struct {
	mock *Mockscaler
}

// NewMockscaler creates a new mock instance.
func NewMockscaler(ctrl *gomock.Controller) *Mockscaler { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockscaler) EXPECT() *MockscalerMockRecorder {
	_ = "STUB: not implemented"

	// scale mocks base method.
	return nil
}

func (m *Mockscaler) scale(arg0 int) { _ = "STUB: not implemented"; return }

// scale indicates an expected call of scale.
func (mr *MockscalerMockRecorder) scale(arg0 any) *MockscalerscaleCall {
	_ = "STUB: not implemented"
	return nil
}

// MockscalerscaleCall wrap *gomock.Call
type MockscalerscaleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockscalerscaleCall) Return() *MockscalerscaleCall { _ = "STUB: not implemented"; return nil }

// Do rewrite *gomock.Call.Do
func (c *MockscalerscaleCall) Do(f func(int)) *MockscalerscaleCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockscalerscaleCall) DoAndReturn(f func(int)) *MockscalerscaleCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknipostValidator is a mock of nipostValidator interface.
type MocknipostValidator struct {
	ctrl     *gomock.Controller
	recorder *MocknipostValidatorMockRecorder
	isgomock struct{}
}

// MocknipostValidatorMockRecorder is the mock recorder for MocknipostValidator.
type MocknipostValidatorMockRecorder struct {
	mock *MocknipostValidator
}

// NewMocknipostValidator creates a new mock instance.
func NewMocknipostValidator(ctrl *gomock.Controller) *MocknipostValidator {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknipostValidator) EXPECT() *MocknipostValidatorMockRecorder {
	_ = "STUB: not implemented"

	// InitialNIPostChallengeV1 mocks base method.
	return nil
}

func (m *MocknipostValidator) InitialNIPostChallengeV1(challenge *wire.NIPostChallengeV1, atxs atxProvider, goldenATXID types.ATXID) error {
	_ = "STUB: not implemented"
	return nil
}

// InitialNIPostChallengeV1 indicates an expected call of InitialNIPostChallengeV1.
func (mr *MocknipostValidatorMockRecorder) InitialNIPostChallengeV1(challenge, atxs, goldenATXID any) *MocknipostValidatorInitialNIPostChallengeV1Call {
	_ = "STUB: not implemented"
	return nil
}

// MocknipostValidatorInitialNIPostChallengeV1Call wrap *gomock.Call
type MocknipostValidatorInitialNIPostChallengeV1Call struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknipostValidatorInitialNIPostChallengeV1Call) Return(arg0 error) *MocknipostValidatorInitialNIPostChallengeV1Call {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknipostValidatorInitialNIPostChallengeV1Call) Do(f func(*wire.NIPostChallengeV1, atxProvider, types.ATXID) error) *MocknipostValidatorInitialNIPostChallengeV1Call {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknipostValidatorInitialNIPostChallengeV1Call) DoAndReturn(f func(*wire.NIPostChallengeV1, atxProvider, types.ATXID) error) *MocknipostValidatorInitialNIPostChallengeV1Call {
	_ = "STUB: not implemented"
	return nil
}

// IsVerifyingFullPost mocks base method.
func (m *MocknipostValidator) IsVerifyingFullPost() bool { _ = "STUB: not implemented"; return false }

// IsVerifyingFullPost indicates an expected call of IsVerifyingFullPost.
func (mr *MocknipostValidatorMockRecorder) IsVerifyingFullPost() *MocknipostValidatorIsVerifyingFullPostCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknipostValidatorIsVerifyingFullPostCall wrap *gomock.Call
type MocknipostValidatorIsVerifyingFullPostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknipostValidatorIsVerifyingFullPostCall) Return(arg0 bool) *MocknipostValidatorIsVerifyingFullPostCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknipostValidatorIsVerifyingFullPostCall) Do(f func() bool) *MocknipostValidatorIsVerifyingFullPostCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknipostValidatorIsVerifyingFullPostCall) DoAndReturn(f func() bool) *MocknipostValidatorIsVerifyingFullPostCall {
	_ = "STUB: not implemented"
	return nil
}

// NIPost mocks base method.
func (m *MocknipostValidator) NIPost(ctx context.Context, nodeId types.NodeID, commitmentAtxId types.ATXID, NIPost *types.NIPost, expectedChallenge types.Hash32, numUnits uint32, opts ...validatorOption) (uint64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// NIPost indicates an expected call of NIPost.
func (mr *MocknipostValidatorMockRecorder) NIPost(ctx, nodeId, commitmentAtxId, NIPost, expectedChallenge, numUnits any, opts ...any) *MocknipostValidatorNIPostCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknipostValidatorNIPostCall wrap *gomock.Call
type MocknipostValidatorNIPostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknipostValidatorNIPostCall) Return(arg0 uint64, arg1 error) *MocknipostValidatorNIPostCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknipostValidatorNIPostCall) Do(f func(context.Context, types.NodeID, types.ATXID, *types.NIPost, types.Hash32, uint32, ...validatorOption) (uint64, error)) *MocknipostValidatorNIPostCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknipostValidatorNIPostCall) DoAndReturn(f func(context.Context, types.NodeID, types.ATXID, *types.NIPost, types.Hash32, uint32, ...validatorOption) (uint64, error)) *MocknipostValidatorNIPostCall {
	_ = "STUB: not implemented"
	return nil
}

// NIPostChallengeV1 mocks base method.
func (m *MocknipostValidator) NIPostChallengeV1(challenge *wire.NIPostChallengeV1, previous *types.ActivationTx, nodeID types.NodeID) error {
	_ = "STUB: not implemented"
	return nil
}

// NIPostChallengeV1 indicates an expected call of NIPostChallengeV1.
func (mr *MocknipostValidatorMockRecorder) NIPostChallengeV1(challenge, previous, nodeID any) *MocknipostValidatorNIPostChallengeV1Call {
	_ = "STUB: not implemented"
	return nil
}

// MocknipostValidatorNIPostChallengeV1Call wrap *gomock.Call
type MocknipostValidatorNIPostChallengeV1Call struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknipostValidatorNIPostChallengeV1Call) Return(arg0 error) *MocknipostValidatorNIPostChallengeV1Call {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknipostValidatorNIPostChallengeV1Call) Do(f func(*wire.NIPostChallengeV1, *types.ActivationTx, types.NodeID) error) *MocknipostValidatorNIPostChallengeV1Call {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknipostValidatorNIPostChallengeV1Call) DoAndReturn(f func(*wire.NIPostChallengeV1, *types.ActivationTx, types.NodeID) error) *MocknipostValidatorNIPostChallengeV1Call {
	_ = "STUB: not implemented"
	return nil
}

// NumUnits mocks base method.
func (m *MocknipostValidator) NumUnits(cfg *PostConfig, numUnits uint32) error {
	_ = "STUB: not implemented"
	return nil
}

// NumUnits indicates an expected call of NumUnits.
func (mr *MocknipostValidatorMockRecorder) NumUnits(cfg, numUnits any) *MocknipostValidatorNumUnitsCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknipostValidatorNumUnitsCall wrap *gomock.Call
type MocknipostValidatorNumUnitsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknipostValidatorNumUnitsCall) Return(arg0 error) *MocknipostValidatorNumUnitsCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknipostValidatorNumUnitsCall) Do(f func(*PostConfig, uint32) error) *MocknipostValidatorNumUnitsCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknipostValidatorNumUnitsCall) DoAndReturn(f func(*PostConfig, uint32) error) *MocknipostValidatorNumUnitsCall {
	_ = "STUB: not implemented"
	return nil
}

// PoetMembership mocks base method.
func (m *MocknipostValidator) PoetMembership(ctx context.Context, membership *types.MultiMerkleProof, postChallenge types.Hash32, poetChallenges [][]byte) (uint64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// PoetMembership indicates an expected call of PoetMembership.
func (mr *MocknipostValidatorMockRecorder) PoetMembership(ctx, membership, postChallenge, poetChallenges any) *MocknipostValidatorPoetMembershipCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknipostValidatorPoetMembershipCall wrap *gomock.Call
type MocknipostValidatorPoetMembershipCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknipostValidatorPoetMembershipCall) Return(arg0 uint64, arg1 error) *MocknipostValidatorPoetMembershipCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknipostValidatorPoetMembershipCall) Do(f func(context.Context, *types.MultiMerkleProof, types.Hash32, [][]byte) (uint64, error)) *MocknipostValidatorPoetMembershipCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknipostValidatorPoetMembershipCall) DoAndReturn(f func(context.Context, *types.MultiMerkleProof, types.Hash32, [][]byte) (uint64, error)) *MocknipostValidatorPoetMembershipCall {
	_ = "STUB: not implemented"
	return nil
}

// PositioningAtx mocks base method.
func (m *MocknipostValidator) PositioningAtx(id types.ATXID, atxs atxProvider, goldenATXID types.ATXID, pubEpoch types.EpochID) error {
	_ = "STUB: not implemented"
	return nil
}

// PositioningAtx indicates an expected call of PositioningAtx.
func (mr *MocknipostValidatorMockRecorder) PositioningAtx(id, atxs, goldenATXID, pubEpoch any) *MocknipostValidatorPositioningAtxCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknipostValidatorPositioningAtxCall wrap *gomock.Call
type MocknipostValidatorPositioningAtxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknipostValidatorPositioningAtxCall) Return(arg0 error) *MocknipostValidatorPositioningAtxCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknipostValidatorPositioningAtxCall) Do(f func(types.ATXID, atxProvider, types.ATXID, types.EpochID) error) *MocknipostValidatorPositioningAtxCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknipostValidatorPositioningAtxCall) DoAndReturn(f func(types.ATXID, atxProvider, types.ATXID, types.EpochID) error) *MocknipostValidatorPositioningAtxCall {
	_ = "STUB: not implemented"
	return nil
}

// Post mocks base method.
func (m *MocknipostValidator) Post(ctx context.Context, nodeId types.NodeID, commitmentAtxId types.ATXID, post *types.Post, metadata *types.PostMetadata, numUnits uint32, opts ...validatorOption) error {
	_ = "STUB: not implemented"
	return nil
}

// Post indicates an expected call of Post.
func (mr *MocknipostValidatorMockRecorder) Post(ctx, nodeId, commitmentAtxId, post, metadata, numUnits any, opts ...any) *MocknipostValidatorPostCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknipostValidatorPostCall wrap *gomock.Call
type MocknipostValidatorPostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknipostValidatorPostCall) Return(arg0 error) *MocknipostValidatorPostCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknipostValidatorPostCall) Do(f func(context.Context, types.NodeID, types.ATXID, *types.Post, *types.PostMetadata, uint32, ...validatorOption) error) *MocknipostValidatorPostCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknipostValidatorPostCall) DoAndReturn(f func(context.Context, types.NodeID, types.ATXID, *types.Post, *types.PostMetadata, uint32, ...validatorOption) error) *MocknipostValidatorPostCall {
	_ = "STUB: not implemented"
	return nil
}

// PostV2 mocks base method.
func (m *MocknipostValidator) PostV2(ctx context.Context, smesherID types.NodeID, commitment types.ATXID, post *types.Post, challenge []byte, numUnits uint32, opts ...validatorOption) error {
	_ = "STUB: not implemented"
	return nil
}

// PostV2 indicates an expected call of PostV2.
func (mr *MocknipostValidatorMockRecorder) PostV2(ctx, smesherID, commitment, post, challenge, numUnits any, opts ...any) *MocknipostValidatorPostV2Call {
	_ = "STUB: not implemented"
	return nil
}

// MocknipostValidatorPostV2Call wrap *gomock.Call
type MocknipostValidatorPostV2Call struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknipostValidatorPostV2Call) Return(arg0 error) *MocknipostValidatorPostV2Call {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknipostValidatorPostV2Call) Do(f func(context.Context, types.NodeID, types.ATXID, *types.Post, []byte, uint32, ...validatorOption) error) *MocknipostValidatorPostV2Call {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknipostValidatorPostV2Call) DoAndReturn(f func(context.Context, types.NodeID, types.ATXID, *types.Post, []byte, uint32, ...validatorOption) error) *MocknipostValidatorPostV2Call {
	_ = "STUB: not implemented"
	return nil
}

// VRFNonce mocks base method.
func (m *MocknipostValidator) VRFNonce(nodeId types.NodeID, commitmentAtxId types.ATXID, vrfNonce, labelsPerUnit uint64, numUnits uint32) error {
	_ = "STUB: not implemented"
	return nil
}

// VRFNonce indicates an expected call of VRFNonce.
func (mr *MocknipostValidatorMockRecorder) VRFNonce(nodeId, commitmentAtxId, vrfNonce, labelsPerUnit, numUnits any) *MocknipostValidatorVRFNonceCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknipostValidatorVRFNonceCall wrap *gomock.Call
type MocknipostValidatorVRFNonceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknipostValidatorVRFNonceCall) Return(arg0 error) *MocknipostValidatorVRFNonceCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknipostValidatorVRFNonceCall) Do(f func(types.NodeID, types.ATXID, uint64, uint64, uint32) error) *MocknipostValidatorVRFNonceCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknipostValidatorVRFNonceCall) DoAndReturn(f func(types.NodeID, types.ATXID, uint64, uint64, uint32) error) *MocknipostValidatorVRFNonceCall {
	_ = "STUB: not implemented"
	return nil
}

// VRFNonceV2 mocks base method.
func (m *MocknipostValidator) VRFNonceV2(smesherID types.NodeID, commitment types.ATXID, vrfNonce uint64, numUnits uint32) error {
	_ = "STUB: not implemented"
	return nil
}

// VRFNonceV2 indicates an expected call of VRFNonceV2.
func (mr *MocknipostValidatorMockRecorder) VRFNonceV2(smesherID, commitment, vrfNonce, numUnits any) *MocknipostValidatorVRFNonceV2Call {
	_ = "STUB: not implemented"
	return nil
}

// MocknipostValidatorVRFNonceV2Call wrap *gomock.Call
type MocknipostValidatorVRFNonceV2Call struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknipostValidatorVRFNonceV2Call) Return(arg0 error) *MocknipostValidatorVRFNonceV2Call {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknipostValidatorVRFNonceV2Call) Do(f func(types.NodeID, types.ATXID, uint64, uint32) error) *MocknipostValidatorVRFNonceV2Call {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknipostValidatorVRFNonceV2Call) DoAndReturn(f func(types.NodeID, types.ATXID, uint64, uint32) error) *MocknipostValidatorVRFNonceV2Call {
	_ = "STUB: not implemented"
	return nil
}

// VerifyChain mocks base method.
func (m *MocknipostValidator) VerifyChain(ctx context.Context, id, goldenATXID types.ATXID, opts ...VerifyChainOption) error {
	_ = "STUB: not implemented"
	return nil
}

// VerifyChain indicates an expected call of VerifyChain.
func (mr *MocknipostValidatorMockRecorder) VerifyChain(ctx, id, goldenATXID any, opts ...any) *MocknipostValidatorVerifyChainCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknipostValidatorVerifyChainCall wrap *gomock.Call
type MocknipostValidatorVerifyChainCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknipostValidatorVerifyChainCall) Return(arg0 error) *MocknipostValidatorVerifyChainCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknipostValidatorVerifyChainCall) Do(f func(context.Context, types.ATXID, types.ATXID, ...VerifyChainOption) error) *MocknipostValidatorVerifyChainCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknipostValidatorVerifyChainCall) DoAndReturn(f func(context.Context, types.ATXID, types.ATXID, ...VerifyChainOption) error) *MocknipostValidatorVerifyChainCall {
	_ = "STUB: not implemented"
	return nil
}

// MocklayerClock is a mock of layerClock interface.
type MocklayerClock struct {
	ctrl     *gomock.Controller
	recorder *MocklayerClockMockRecorder
	isgomock struct{}
}

// MocklayerClockMockRecorder is the mock recorder for MocklayerClock.
type MocklayerClockMockRecorder struct {
	mock *MocklayerClock
}

// NewMocklayerClock creates a new mock instance.
func NewMocklayerClock(ctrl *gomock.Controller) *MocklayerClock {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklayerClock) EXPECT() *MocklayerClockMockRecorder {
	_ = "STUB: not implemented"

	// AwaitLayer mocks base method.
	return nil
}

func (m *MocklayerClock) AwaitLayer(layerID types.LayerID) <-chan struct{} {
	_ = "STUB: not implemented"
	return nil
}

// AwaitLayer indicates an expected call of AwaitLayer.
func (mr *MocklayerClockMockRecorder) AwaitLayer(layerID any) *MocklayerClockAwaitLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// MocklayerClockAwaitLayerCall wrap *gomock.Call
type MocklayerClockAwaitLayerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocklayerClockAwaitLayerCall) Return(arg0 <-chan struct{}) *MocklayerClockAwaitLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocklayerClockAwaitLayerCall) Do(f func(types.LayerID) <-chan struct{}) *MocklayerClockAwaitLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocklayerClockAwaitLayerCall) DoAndReturn(f func(types.LayerID) <-chan struct{}) *MocklayerClockAwaitLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// CurrentLayer mocks base method.
func (m *MocklayerClock) CurrentLayer() types.LayerID {
	_ = "STUB: not implemented"
	return *new(types.LayerID)
}

// CurrentLayer indicates an expected call of CurrentLayer.
func (mr *MocklayerClockMockRecorder) CurrentLayer() *MocklayerClockCurrentLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// MocklayerClockCurrentLayerCall wrap *gomock.Call
type MocklayerClockCurrentLayerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocklayerClockCurrentLayerCall) Return(arg0 types.LayerID) *MocklayerClockCurrentLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocklayerClockCurrentLayerCall) Do(f func() types.LayerID) *MocklayerClockCurrentLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocklayerClockCurrentLayerCall) DoAndReturn(f func() types.LayerID) *MocklayerClockCurrentLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// LayerToTime mocks base method.
func (m *MocklayerClock) LayerToTime(arg0 types.LayerID) time.Time {
	_ = "STUB: not implemented"
	return *new(time.Time)
}

// LayerToTime indicates an expected call of LayerToTime.
func (mr *MocklayerClockMockRecorder) LayerToTime(arg0 any) *MocklayerClockLayerToTimeCall {
	_ = "STUB: not implemented"
	return nil
}

// MocklayerClockLayerToTimeCall wrap *gomock.Call
type MocklayerClockLayerToTimeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocklayerClockLayerToTimeCall) Return(arg0 time.Time) *MocklayerClockLayerToTimeCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocklayerClockLayerToTimeCall) Do(f func(types.LayerID) time.Time) *MocklayerClockLayerToTimeCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocklayerClockLayerToTimeCall) DoAndReturn(f func(types.LayerID) time.Time) *MocklayerClockLayerToTimeCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknipostBuilder is a mock of nipostBuilder interface.
type MocknipostBuilder struct {
	ctrl     *gomock.Controller
	recorder *MocknipostBuilderMockRecorder
	isgomock struct{}
}

// MocknipostBuilderMockRecorder is the mock recorder for MocknipostBuilder.
type MocknipostBuilderMockRecorder struct {
	mock *MocknipostBuilder
}

// NewMocknipostBuilder creates a new mock instance.
func NewMocknipostBuilder(ctrl *gomock.Controller) *MocknipostBuilder {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknipostBuilder) EXPECT() *MocknipostBuilderMockRecorder {
	_ = "STUB: not implemented"

	// BuildNIPost mocks base method.
	return nil
}

func (m *MocknipostBuilder) BuildNIPost(ctx context.Context, sig *signing.EdSigner, challengeHash types.Hash32, postChallenge *types.NIPostChallenge) (*nipost.NIPostState, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// BuildNIPost indicates an expected call of BuildNIPost.
func (mr *MocknipostBuilderMockRecorder) BuildNIPost(ctx, sig, challengeHash, postChallenge any) *MocknipostBuilderBuildNIPostCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknipostBuilderBuildNIPostCall wrap *gomock.Call
type MocknipostBuilderBuildNIPostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknipostBuilderBuildNIPostCall) Return(arg0 *nipost.NIPostState, arg1 error) *MocknipostBuilderBuildNIPostCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknipostBuilderBuildNIPostCall) Do(f func(context.Context, *signing.EdSigner, types.Hash32, *types.NIPostChallenge) (*nipost.NIPostState, error)) *MocknipostBuilderBuildNIPostCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknipostBuilderBuildNIPostCall) DoAndReturn(f func(context.Context, *signing.EdSigner, types.Hash32, *types.NIPostChallenge) (*nipost.NIPostState, error)) *MocknipostBuilderBuildNIPostCall {
	_ = "STUB: not implemented"
	return nil
}

// Proof mocks base method.
func (m *MocknipostBuilder) Proof(ctx context.Context, nodeID types.NodeID, challenge []byte, postChallenge *types.NIPostChallenge) (*types.Post, *types.PostInfo, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

// Proof indicates an expected call of Proof.
func (mr *MocknipostBuilderMockRecorder) Proof(ctx, nodeID, challenge, postChallenge any) *MocknipostBuilderProofCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknipostBuilderProofCall wrap *gomock.Call
type MocknipostBuilderProofCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknipostBuilderProofCall) Return(arg0 *types.Post, arg1 *types.PostInfo, arg2 error) *MocknipostBuilderProofCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknipostBuilderProofCall) Do(f func(context.Context, types.NodeID, []byte, *types.NIPostChallenge) (*types.Post, *types.PostInfo, error)) *MocknipostBuilderProofCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknipostBuilderProofCall) DoAndReturn(f func(context.Context, types.NodeID, []byte, *types.NIPostChallenge) (*types.Post, *types.PostInfo, error)) *MocknipostBuilderProofCall {
	_ = "STUB: not implemented"
	return nil
}

// ResetState mocks base method.
func (m *MocknipostBuilder) ResetState(arg0 types.NodeID) error {
	_ = "STUB: not implemented"
	return nil
}

// ResetState indicates an expected call of ResetState.
func (mr *MocknipostBuilderMockRecorder) ResetState(arg0 any) *MocknipostBuilderResetStateCall {
	_ = "STUB: not implemented"
	return nil
}

// MocknipostBuilderResetStateCall wrap *gomock.Call
type MocknipostBuilderResetStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocknipostBuilderResetStateCall) Return(arg0 error) *MocknipostBuilderResetStateCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocknipostBuilderResetStateCall) Do(f func(types.NodeID) error) *MocknipostBuilderResetStateCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocknipostBuilderResetStateCall) DoAndReturn(f func(types.NodeID) error) *MocknipostBuilderResetStateCall {
	_ = "STUB: not implemented"
	return nil
}

// Mocksyncer is a mock of syncer interface.
type Mocksyncer struct {
	ctrl     *gomock.Controller
	recorder *MocksyncerMockRecorder
	isgomock struct{}
}

// MocksyncerMockRecorder is the mock recorder for Mocksyncer.
type MocksyncerMockRecorder struct {
	mock *Mocksyncer
}

// NewMocksyncer creates a new mock instance.
func NewMocksyncer(ctrl *gomock.Controller) *Mocksyncer { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksyncer) EXPECT() *MocksyncerMockRecorder {
	_ = "STUB: not implemented"

	// RegisterForATXSynced mocks base method.
	return nil
}

func (m *Mocksyncer) RegisterForATXSynced() <-chan struct{} { _ = "STUB: not implemented"; return nil }

// RegisterForATXSynced indicates an expected call of RegisterForATXSynced.
func (mr *MocksyncerMockRecorder) RegisterForATXSynced() *MocksyncerRegisterForATXSyncedCall {
	_ = "STUB: not implemented"
	return nil
}

// MocksyncerRegisterForATXSyncedCall wrap *gomock.Call
type MocksyncerRegisterForATXSyncedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksyncerRegisterForATXSyncedCall) Return(arg0 <-chan struct{}) *MocksyncerRegisterForATXSyncedCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocksyncerRegisterForATXSyncedCall) Do(f func() <-chan struct{}) *MocksyncerRegisterForATXSyncedCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksyncerRegisterForATXSyncedCall) DoAndReturn(f func() <-chan struct{}) *MocksyncerRegisterForATXSyncedCall {
	_ = "STUB: not implemented"
	return nil
}

// MocklegacyMalfeasancePublisher is a mock of legacyMalfeasancePublisher interface.
type MocklegacyMalfeasancePublisher struct {
	ctrl     *gomock.Controller
	recorder *MocklegacyMalfeasancePublisherMockRecorder
	isgomock struct{}
}

// MocklegacyMalfeasancePublisherMockRecorder is the mock recorder for MocklegacyMalfeasancePublisher.
type MocklegacyMalfeasancePublisherMockRecorder struct {
	mock *MocklegacyMalfeasancePublisher
}

// NewMocklegacyMalfeasancePublisher creates a new mock instance.
func NewMocklegacyMalfeasancePublisher(ctrl *gomock.Controller) *MocklegacyMalfeasancePublisher {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklegacyMalfeasancePublisher) EXPECT() *MocklegacyMalfeasancePublisherMockRecorder {
	_ = "STUB: not implemented"

	// PublishProof mocks base method.
	return nil
}

func (m *MocklegacyMalfeasancePublisher) PublishProof(ctx context.Context, smesherID types.NodeID, proof *wire0.MalfeasanceProof) error {
	_ = "STUB: not implemented"
	return nil
}

// PublishProof indicates an expected call of PublishProof.
func (mr *MocklegacyMalfeasancePublisherMockRecorder) PublishProof(ctx, smesherID, proof any) *MocklegacyMalfeasancePublisherPublishProofCall {
	_ = "STUB: not implemented"
	return nil
}

// MocklegacyMalfeasancePublisherPublishProofCall wrap *gomock.Call
type MocklegacyMalfeasancePublisherPublishProofCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocklegacyMalfeasancePublisherPublishProofCall) Return(arg0 error) *MocklegacyMalfeasancePublisherPublishProofCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocklegacyMalfeasancePublisherPublishProofCall) Do(f func(context.Context, types.NodeID, *wire0.MalfeasanceProof) error) *MocklegacyMalfeasancePublisherPublishProofCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocklegacyMalfeasancePublisherPublishProofCall) DoAndReturn(f func(context.Context, types.NodeID, *wire0.MalfeasanceProof) error) *MocklegacyMalfeasancePublisherPublishProofCall {
	_ = "STUB: not implemented"
	return nil
}

// MockatxMalfeasancePublisher is a mock of atxMalfeasancePublisher interface.
type MockatxMalfeasancePublisher struct {
	ctrl     *gomock.Controller
	recorder *MockatxMalfeasancePublisherMockRecorder
	isgomock struct{}
}

// MockatxMalfeasancePublisherMockRecorder is the mock recorder for MockatxMalfeasancePublisher.
type MockatxMalfeasancePublisherMockRecorder struct {
	mock *MockatxMalfeasancePublisher
}

// NewMockatxMalfeasancePublisher creates a new mock instance.
func NewMockatxMalfeasancePublisher(ctrl *gomock.Controller) *MockatxMalfeasancePublisher {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockatxMalfeasancePublisher) EXPECT() *MockatxMalfeasancePublisherMockRecorder {
	_ = "STUB: not implemented"

	// Publish mocks base method.
	return nil
}

func (m *MockatxMalfeasancePublisher) Publish(ctx context.Context, nodeID types.NodeID, proof wire.Proof) error {
	_ = "STUB: not implemented"
	return nil
}

// Publish indicates an expected call of Publish.
func (mr *MockatxMalfeasancePublisherMockRecorder) Publish(ctx, nodeID, proof any) *MockatxMalfeasancePublisherPublishCall {
	_ = "STUB: not implemented"
	return nil
}

// MockatxMalfeasancePublisherPublishCall wrap *gomock.Call
type MockatxMalfeasancePublisherPublishCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockatxMalfeasancePublisherPublishCall) Return(arg0 error) *MockatxMalfeasancePublisherPublishCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockatxMalfeasancePublisherPublishCall) Do(f func(context.Context, types.NodeID, wire.Proof) error) *MockatxMalfeasancePublisherPublishCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockatxMalfeasancePublisherPublishCall) DoAndReturn(f func(context.Context, types.NodeID, wire.Proof) error) *MockatxMalfeasancePublisherPublishCall {
	_ = "STUB: not implemented"
	return nil
}

// Regossip mocks base method.
func (m *MockatxMalfeasancePublisher) Regossip(ctx context.Context, nodeID types.NodeID) error {
	_ = "STUB: not implemented"
	return nil
}

// Regossip indicates an expected call of Regossip.
func (mr *MockatxMalfeasancePublisherMockRecorder) Regossip(ctx, nodeID any) *MockatxMalfeasancePublisherRegossipCall {
	_ = "STUB: not implemented"
	return nil
}

// MockatxMalfeasancePublisherRegossipCall wrap *gomock.Call
type MockatxMalfeasancePublisherRegossipCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockatxMalfeasancePublisherRegossipCall) Return(arg0 error) *MockatxMalfeasancePublisherRegossipCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockatxMalfeasancePublisherRegossipCall) Do(f func(context.Context, types.NodeID) error) *MockatxMalfeasancePublisherRegossipCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockatxMalfeasancePublisherRegossipCall) DoAndReturn(f func(context.Context, types.NodeID) error) *MockatxMalfeasancePublisherRegossipCall {
	_ = "STUB: not implemented"
	return nil
}

// MockmalfeasancePublisher is a mock of malfeasancePublisher interface.
type MockmalfeasancePublisher struct {
	ctrl     *gomock.Controller
	recorder *MockmalfeasancePublisherMockRecorder
	isgomock struct{}
}

// MockmalfeasancePublisherMockRecorder is the mock recorder for MockmalfeasancePublisher.
type MockmalfeasancePublisherMockRecorder struct {
	mock *MockmalfeasancePublisher
}

// NewMockmalfeasancePublisher creates a new mock instance.
func NewMockmalfeasancePublisher(ctrl *gomock.Controller) *MockmalfeasancePublisher {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmalfeasancePublisher) EXPECT() *MockmalfeasancePublisherMockRecorder {
	_ = "STUB: not implemented"

	// PublishATXProof mocks base method.
	return nil
}

func (m *MockmalfeasancePublisher) PublishATXProof(ctx context.Context, nodeID types.NodeID, proof []byte, allowNoRefATXs bool) error {
	_ = "STUB: not implemented"
	return nil
}

// PublishATXProof indicates an expected call of PublishATXProof.
func (mr *MockmalfeasancePublisherMockRecorder) PublishATXProof(ctx, nodeID, proof, allowNoRefATXs any) *MockmalfeasancePublisherPublishATXProofCall {
	_ = "STUB: not implemented"
	return nil
}

// MockmalfeasancePublisherPublishATXProofCall wrap *gomock.Call
type MockmalfeasancePublisherPublishATXProofCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockmalfeasancePublisherPublishATXProofCall) Return(arg0 error) *MockmalfeasancePublisherPublishATXProofCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockmalfeasancePublisherPublishATXProofCall) Do(f func(context.Context, types.NodeID, []byte, bool) error) *MockmalfeasancePublisherPublishATXProofCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockmalfeasancePublisherPublishATXProofCall) DoAndReturn(f func(context.Context, types.NodeID, []byte, bool) error) *MockmalfeasancePublisherPublishATXProofCall {
	_ = "STUB: not implemented"
	return nil
}

// Regossip mocks base method.
func (m *MockmalfeasancePublisher) Regossip(ctx context.Context, nodeID types.NodeID) error {
	_ = "STUB: not implemented"
	return nil
}

// Regossip indicates an expected call of Regossip.
func (mr *MockmalfeasancePublisherMockRecorder) Regossip(ctx, nodeID any) *MockmalfeasancePublisherRegossipCall {
	_ = "STUB: not implemented"
	return nil
}

// MockmalfeasancePublisherRegossipCall wrap *gomock.Call
type MockmalfeasancePublisherRegossipCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockmalfeasancePublisherRegossipCall) Return(arg0 error) *MockmalfeasancePublisherRegossipCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockmalfeasancePublisherRegossipCall) Do(f func(context.Context, types.NodeID) error) *MockmalfeasancePublisherRegossipCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockmalfeasancePublisherRegossipCall) DoAndReturn(f func(context.Context, types.NodeID) error) *MockmalfeasancePublisherRegossipCall {
	_ = "STUB: not implemented"
	return nil
}

// MockatxProvider is a mock of atxProvider interface.
type MockatxProvider struct {
	ctrl     *gomock.Controller
	recorder *MockatxProviderMockRecorder
	isgomock struct{}
}

// MockatxProviderMockRecorder is the mock recorder for MockatxProvider.
type MockatxProviderMockRecorder struct {
	mock *MockatxProvider
}

// NewMockatxProvider creates a new mock instance.
func NewMockatxProvider(ctrl *gomock.Controller) *MockatxProvider {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockatxProvider) EXPECT() *MockatxProviderMockRecorder {
	_ = "STUB: not implemented"

	// GetAtx mocks base method.
	return nil
}

func (m *MockatxProvider) GetAtx(id types.ATXID) (*types.ActivationTx, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAtx indicates an expected call of GetAtx.
func (mr *MockatxProviderMockRecorder) GetAtx(id any) *MockatxProviderGetAtxCall {
	_ = "STUB: not implemented"
	return nil
}

// MockatxProviderGetAtxCall wrap *gomock.Call
type MockatxProviderGetAtxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockatxProviderGetAtxCall) Return(arg0 *types.ActivationTx, arg1 error) *MockatxProviderGetAtxCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockatxProviderGetAtxCall) Do(f func(types.ATXID) (*types.ActivationTx, error)) *MockatxProviderGetAtxCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockatxProviderGetAtxCall) DoAndReturn(f func(types.ATXID) (*types.ActivationTx, error)) *MockatxProviderGetAtxCall {
	_ = "STUB: not implemented"
	return nil
}

// MockpostSetupProvider is a mock of postSetupProvider interface.
type MockpostSetupProvider struct {
	ctrl     *gomock.Controller
	recorder *MockpostSetupProviderMockRecorder
	isgomock struct{}
}

// MockpostSetupProviderMockRecorder is the mock recorder for MockpostSetupProvider.
type MockpostSetupProviderMockRecorder struct {
	mock *MockpostSetupProvider
}

// NewMockpostSetupProvider creates a new mock instance.
func NewMockpostSetupProvider(ctrl *gomock.Controller) *MockpostSetupProvider {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpostSetupProvider) EXPECT() *MockpostSetupProviderMockRecorder {
	_ = "STUB: not implemented"

	// PrepareInitializer mocks base method.
	return nil
}

func (m *MockpostSetupProvider) PrepareInitializer(ctx context.Context, opts PostSetupOpts, id types.NodeID) error {
	_ = "STUB: not implemented"
	return nil
}

// PrepareInitializer indicates an expected call of PrepareInitializer.
func (mr *MockpostSetupProviderMockRecorder) PrepareInitializer(ctx, opts, id any) *MockpostSetupProviderPrepareInitializerCall {
	_ = "STUB: not implemented"
	return nil
}

// MockpostSetupProviderPrepareInitializerCall wrap *gomock.Call
type MockpostSetupProviderPrepareInitializerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpostSetupProviderPrepareInitializerCall) Return(arg0 error) *MockpostSetupProviderPrepareInitializerCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockpostSetupProviderPrepareInitializerCall) Do(f func(context.Context, PostSetupOpts, types.NodeID) error) *MockpostSetupProviderPrepareInitializerCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpostSetupProviderPrepareInitializerCall) DoAndReturn(f func(context.Context, PostSetupOpts, types.NodeID) error) *MockpostSetupProviderPrepareInitializerCall {
	_ = "STUB: not implemented"
	return nil
}

// Reset mocks base method.
func (m *MockpostSetupProvider) Reset() error { _ = "STUB: not implemented"; return nil }

// Reset indicates an expected call of Reset.
func (mr *MockpostSetupProviderMockRecorder) Reset() *MockpostSetupProviderResetCall {
	_ = "STUB: not implemented"
	return nil
}

// MockpostSetupProviderResetCall wrap *gomock.Call
type MockpostSetupProviderResetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpostSetupProviderResetCall) Return(arg0 error) *MockpostSetupProviderResetCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockpostSetupProviderResetCall) Do(f func() error) *MockpostSetupProviderResetCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpostSetupProviderResetCall) DoAndReturn(f func() error) *MockpostSetupProviderResetCall {
	_ = "STUB: not implemented"
	return nil
}

// StartSession mocks base method.
func (m *MockpostSetupProvider) StartSession(ctx context.Context, id types.NodeID) error {
	_ = "STUB: not implemented"
	return nil
}

// StartSession indicates an expected call of StartSession.
func (mr *MockpostSetupProviderMockRecorder) StartSession(ctx, id any) *MockpostSetupProviderStartSessionCall {
	_ = "STUB: not implemented"
	return nil
}

// MockpostSetupProviderStartSessionCall wrap *gomock.Call
type MockpostSetupProviderStartSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpostSetupProviderStartSessionCall) Return(arg0 error) *MockpostSetupProviderStartSessionCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockpostSetupProviderStartSessionCall) Do(f func(context.Context, types.NodeID) error) *MockpostSetupProviderStartSessionCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpostSetupProviderStartSessionCall) DoAndReturn(f func(context.Context, types.NodeID) error) *MockpostSetupProviderStartSessionCall {
	_ = "STUB: not implemented"
	return nil
}

// Status mocks base method.
func (m *MockpostSetupProvider) Status() *PostSetupStatus { _ = "STUB: not implemented"; return nil }

// Status indicates an expected call of Status.
func (mr *MockpostSetupProviderMockRecorder) Status() *MockpostSetupProviderStatusCall {
	_ = "STUB: not implemented"
	return nil
}

// MockpostSetupProviderStatusCall wrap *gomock.Call
type MockpostSetupProviderStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpostSetupProviderStatusCall) Return(arg0 *PostSetupStatus) *MockpostSetupProviderStatusCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockpostSetupProviderStatusCall) Do(f func() *PostSetupStatus) *MockpostSetupProviderStatusCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpostSetupProviderStatusCall) DoAndReturn(f func() *PostSetupStatus) *MockpostSetupProviderStatusCall {
	_ = "STUB: not implemented"
	return nil
}

// MockSmeshingProvider is a mock of SmeshingProvider interface.
type MockSmeshingProvider struct {
	ctrl     *gomock.Controller
	recorder *MockSmeshingProviderMockRecorder
	isgomock struct{}
}

// MockSmeshingProviderMockRecorder is the mock recorder for MockSmeshingProvider.
type MockSmeshingProviderMockRecorder struct {
	mock *MockSmeshingProvider
}

// NewMockSmeshingProvider creates a new mock instance.
func NewMockSmeshingProvider(ctrl *gomock.Controller) *MockSmeshingProvider {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSmeshingProvider) EXPECT() *MockSmeshingProviderMockRecorder {
	_ = "STUB: not implemented"

	// Coinbase mocks base method.
	return nil
}

func (m *MockSmeshingProvider) Coinbase() types.Address {
	_ = "STUB: not implemented"
	return *new(types.Address)
}

// Coinbase indicates an expected call of Coinbase.
func (mr *MockSmeshingProviderMockRecorder) Coinbase() *MockSmeshingProviderCoinbaseCall {
	_ = "STUB: not implemented"
	return nil
}

// MockSmeshingProviderCoinbaseCall wrap *gomock.Call
type MockSmeshingProviderCoinbaseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSmeshingProviderCoinbaseCall) Return(arg0 types.Address) *MockSmeshingProviderCoinbaseCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockSmeshingProviderCoinbaseCall) Do(f func() types.Address) *MockSmeshingProviderCoinbaseCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSmeshingProviderCoinbaseCall) DoAndReturn(f func() types.Address) *MockSmeshingProviderCoinbaseCall {
	_ = "STUB: not implemented"
	return nil
}

// SetCoinbase mocks base method.
func (m *MockSmeshingProvider) SetCoinbase(coinbase types.Address) {
	_ = "STUB: not implemented"
	return
}

// SetCoinbase indicates an expected call of SetCoinbase.
func (mr *MockSmeshingProviderMockRecorder) SetCoinbase(coinbase any) *MockSmeshingProviderSetCoinbaseCall {
	_ = "STUB: not implemented"
	return nil
}

// MockSmeshingProviderSetCoinbaseCall wrap *gomock.Call
type MockSmeshingProviderSetCoinbaseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSmeshingProviderSetCoinbaseCall) Return() *MockSmeshingProviderSetCoinbaseCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockSmeshingProviderSetCoinbaseCall) Do(f func(types.Address)) *MockSmeshingProviderSetCoinbaseCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSmeshingProviderSetCoinbaseCall) DoAndReturn(f func(types.Address)) *MockSmeshingProviderSetCoinbaseCall {
	_ = "STUB: not implemented"
	return nil
}

// SmesherIDs mocks base method.
func (m *MockSmeshingProvider) SmesherIDs() []types.NodeID { _ = "STUB: not implemented"; return nil }

// SmesherIDs indicates an expected call of SmesherIDs.
func (mr *MockSmeshingProviderMockRecorder) SmesherIDs() *MockSmeshingProviderSmesherIDsCall {
	_ = "STUB: not implemented"
	return nil
}

// MockSmeshingProviderSmesherIDsCall wrap *gomock.Call
type MockSmeshingProviderSmesherIDsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSmeshingProviderSmesherIDsCall) Return(arg0 []types.NodeID) *MockSmeshingProviderSmesherIDsCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockSmeshingProviderSmesherIDsCall) Do(f func() []types.NodeID) *MockSmeshingProviderSmesherIDsCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSmeshingProviderSmesherIDsCall) DoAndReturn(f func() []types.NodeID) *MockSmeshingProviderSmesherIDsCall {
	_ = "STUB: not implemented"
	return nil
}

// Smeshing mocks base method.
func (m *MockSmeshingProvider) Smeshing() bool { _ = "STUB: not implemented"; return false }

// Smeshing indicates an expected call of Smeshing.
func (mr *MockSmeshingProviderMockRecorder) Smeshing() *MockSmeshingProviderSmeshingCall {
	_ = "STUB: not implemented"
	return nil
}

// MockSmeshingProviderSmeshingCall wrap *gomock.Call
type MockSmeshingProviderSmeshingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSmeshingProviderSmeshingCall) Return(arg0 bool) *MockSmeshingProviderSmeshingCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockSmeshingProviderSmeshingCall) Do(f func() bool) *MockSmeshingProviderSmeshingCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSmeshingProviderSmeshingCall) DoAndReturn(f func() bool) *MockSmeshingProviderSmeshingCall {
	_ = "STUB: not implemented"
	return nil
}

// StartSmeshing mocks base method.
func (m *MockSmeshingProvider) StartSmeshing(arg0 types.Address) error {
	_ = "STUB: not implemented"
	return nil
}

// StartSmeshing indicates an expected call of StartSmeshing.
func (mr *MockSmeshingProviderMockRecorder) StartSmeshing(arg0 any) *MockSmeshingProviderStartSmeshingCall {
	_ = "STUB: not implemented"
	return nil
}

// MockSmeshingProviderStartSmeshingCall wrap *gomock.Call
type MockSmeshingProviderStartSmeshingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSmeshingProviderStartSmeshingCall) Return(arg0 error) *MockSmeshingProviderStartSmeshingCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockSmeshingProviderStartSmeshingCall) Do(f func(types.Address) error) *MockSmeshingProviderStartSmeshingCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSmeshingProviderStartSmeshingCall) DoAndReturn(f func(types.Address) error) *MockSmeshingProviderStartSmeshingCall {
	_ = "STUB: not implemented"
	return nil
}

// StopSmeshing mocks base method.
func (m *MockSmeshingProvider) StopSmeshing(arg0 bool) error { _ = "STUB: not implemented"; return nil }

// StopSmeshing indicates an expected call of StopSmeshing.
func (mr *MockSmeshingProviderMockRecorder) StopSmeshing(arg0 any) *MockSmeshingProviderStopSmeshingCall {
	_ = "STUB: not implemented"
	return nil
}

// MockSmeshingProviderStopSmeshingCall wrap *gomock.Call
type MockSmeshingProviderStopSmeshingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSmeshingProviderStopSmeshingCall) Return(arg0 error) *MockSmeshingProviderStopSmeshingCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockSmeshingProviderStopSmeshingCall) Do(f func(bool) error) *MockSmeshingProviderStopSmeshingCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSmeshingProviderStopSmeshingCall) DoAndReturn(f func(bool) error) *MockSmeshingProviderStopSmeshingCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPoetService is a mock of PoetService interface.
type MockPoetService struct {
	ctrl     *gomock.Controller
	recorder *MockPoetServiceMockRecorder
	isgomock struct{}
}

// MockPoetServiceMockRecorder is the mock recorder for MockPoetService.
type MockPoetServiceMockRecorder struct {
	mock *MockPoetService
}

// NewMockPoetService creates a new mock instance.
func NewMockPoetService(ctrl *gomock.Controller) *MockPoetService {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoetService) EXPECT() *MockPoetServiceMockRecorder {
	_ = "STUB: not implemented"

	// Address mocks base method.
	return nil
}

func (m *MockPoetService) Address() string { _ = "STUB: not implemented"; return "" }

// Address indicates an expected call of Address.
func (mr *MockPoetServiceMockRecorder) Address() *MockPoetServiceAddressCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPoetServiceAddressCall wrap *gomock.Call
type MockPoetServiceAddressCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPoetServiceAddressCall) Return(arg0 string) *MockPoetServiceAddressCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPoetServiceAddressCall) Do(f func() string) *MockPoetServiceAddressCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPoetServiceAddressCall) DoAndReturn(f func() string) *MockPoetServiceAddressCall {
	_ = "STUB: not implemented"
	return nil
}

// Certify mocks base method.
func (m *MockPoetService) Certify(ctx context.Context, id types.NodeID) (*certifier.PoetCert, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Certify indicates an expected call of Certify.
func (mr *MockPoetServiceMockRecorder) Certify(ctx, id any) *MockPoetServiceCertifyCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPoetServiceCertifyCall wrap *gomock.Call
type MockPoetServiceCertifyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPoetServiceCertifyCall) Return(arg0 *certifier.PoetCert, arg1 error) *MockPoetServiceCertifyCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPoetServiceCertifyCall) Do(f func(context.Context, types.NodeID) (*certifier.PoetCert, error)) *MockPoetServiceCertifyCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPoetServiceCertifyCall) DoAndReturn(f func(context.Context, types.NodeID) (*certifier.PoetCert, error)) *MockPoetServiceCertifyCall {
	_ = "STUB: not implemented"
	return nil
}

// Proof mocks base method.
func (m *MockPoetService) Proof(ctx context.Context, roundID string) (*types.PoetProof, []types.Hash32, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

// Proof indicates an expected call of Proof.
func (mr *MockPoetServiceMockRecorder) Proof(ctx, roundID any) *MockPoetServiceProofCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPoetServiceProofCall wrap *gomock.Call
type MockPoetServiceProofCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPoetServiceProofCall) Return(arg0 *types.PoetProof, arg1 []types.Hash32, arg2 error) *MockPoetServiceProofCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPoetServiceProofCall) Do(f func(context.Context, string) (*types.PoetProof, []types.Hash32, error)) *MockPoetServiceProofCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPoetServiceProofCall) DoAndReturn(f func(context.Context, string) (*types.PoetProof, []types.Hash32, error)) *MockPoetServiceProofCall {
	_ = "STUB: not implemented"
	return nil
}

// Submit mocks base method.
func (m *MockPoetService) Submit(ctx context.Context, deadline time.Time, prefix, challenge []byte, signature types.EdSignature, nodeID types.NodeID) (*types.PoetRound, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Submit indicates an expected call of Submit.
func (mr *MockPoetServiceMockRecorder) Submit(ctx, deadline, prefix, challenge, signature, nodeID any) *MockPoetServiceSubmitCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPoetServiceSubmitCall wrap *gomock.Call
type MockPoetServiceSubmitCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPoetServiceSubmitCall) Return(arg0 *types.PoetRound, arg1 error) *MockPoetServiceSubmitCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPoetServiceSubmitCall) Do(f func(context.Context, time.Time, []byte, []byte, types.EdSignature, types.NodeID) (*types.PoetRound, error)) *MockPoetServiceSubmitCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPoetServiceSubmitCall) DoAndReturn(f func(context.Context, time.Time, []byte, []byte, types.EdSignature, types.NodeID) (*types.PoetRound, error)) *MockPoetServiceSubmitCall {
	_ = "STUB: not implemented"
	return nil
}

// TickSize mocks base method.
func (m *MockPoetService) TickSize() uint64 { _ = "STUB: not implemented"; return 0 }

// TickSize indicates an expected call of TickSize.
func (mr *MockPoetServiceMockRecorder) TickSize() *MockPoetServiceTickSizeCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPoetServiceTickSizeCall wrap *gomock.Call
type MockPoetServiceTickSizeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPoetServiceTickSizeCall) Return(arg0 uint64) *MockPoetServiceTickSizeCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPoetServiceTickSizeCall) Do(f func() uint64) *MockPoetServiceTickSizeCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPoetServiceTickSizeCall) DoAndReturn(f func() uint64) *MockPoetServiceTickSizeCall {
	_ = "STUB: not implemented"
	return nil
}

// MockcertifierClient is a mock of certifierClient interface.
type MockcertifierClient struct {
	ctrl     *gomock.Controller
	recorder *MockcertifierClientMockRecorder
	isgomock struct{}
}

// MockcertifierClientMockRecorder is the mock recorder for MockcertifierClient.
type MockcertifierClientMockRecorder struct {
	mock *MockcertifierClient
}

// NewMockcertifierClient creates a new mock instance.
func NewMockcertifierClient(ctrl *gomock.Controller) *MockcertifierClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcertifierClient) EXPECT() *MockcertifierClientMockRecorder {
	_ = "STUB: not implemented"

	// Certify mocks base method.
	return nil
}

func (m *MockcertifierClient) Certify(ctx context.Context, id types.NodeID, certifierAddress *url.URL, pubkey []byte) (*certifier.PoetCert, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Certify indicates an expected call of Certify.
func (mr *MockcertifierClientMockRecorder) Certify(ctx, id, certifierAddress, pubkey any) *MockcertifierClientCertifyCall {
	_ = "STUB: not implemented"
	return nil
}

// MockcertifierClientCertifyCall wrap *gomock.Call
type MockcertifierClientCertifyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockcertifierClientCertifyCall) Return(arg0 *certifier.PoetCert, arg1 error) *MockcertifierClientCertifyCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockcertifierClientCertifyCall) Do(f func(context.Context, types.NodeID, *url.URL, []byte) (*certifier.PoetCert, error)) *MockcertifierClientCertifyCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockcertifierClientCertifyCall) DoAndReturn(f func(context.Context, types.NodeID, *url.URL, []byte) (*certifier.PoetCert, error)) *MockcertifierClientCertifyCall {
	_ = "STUB: not implemented"
	return nil
}

// MockcertifierService is a mock of certifierService interface.
type MockcertifierService struct {
	ctrl     *gomock.Controller
	recorder *MockcertifierServiceMockRecorder
	isgomock struct{}
}

// MockcertifierServiceMockRecorder is the mock recorder for MockcertifierService.
type MockcertifierServiceMockRecorder struct {
	mock *MockcertifierService
}

// NewMockcertifierService creates a new mock instance.
func NewMockcertifierService(ctrl *gomock.Controller) *MockcertifierService {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcertifierService) EXPECT() *MockcertifierServiceMockRecorder {
	_ = "STUB: not implemented"

	// Certificate mocks base method.
	return nil
}

func (m *MockcertifierService) Certificate(ctx context.Context, id types.NodeID, certifierAddress *url.URL, pubkey []byte) (*certifier.PoetCert, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Certificate indicates an expected call of Certificate.
func (mr *MockcertifierServiceMockRecorder) Certificate(ctx, id, certifierAddress, pubkey any) *MockcertifierServiceCertificateCall {
	_ = "STUB: not implemented"
	return nil
}

// MockcertifierServiceCertificateCall wrap *gomock.Call
type MockcertifierServiceCertificateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockcertifierServiceCertificateCall) Return(arg0 *certifier.PoetCert, arg1 error) *MockcertifierServiceCertificateCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockcertifierServiceCertificateCall) Do(f func(context.Context, types.NodeID, *url.URL, []byte) (*certifier.PoetCert, error)) *MockcertifierServiceCertificateCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockcertifierServiceCertificateCall) DoAndReturn(f func(context.Context, types.NodeID, *url.URL, []byte) (*certifier.PoetCert, error)) *MockcertifierServiceCertificateCall {
	_ = "STUB: not implemented"
	return nil
}

// DeleteCertificate mocks base method.
func (m *MockcertifierService) DeleteCertificate(id types.NodeID, pubkey []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteCertificate indicates an expected call of DeleteCertificate.
func (mr *MockcertifierServiceMockRecorder) DeleteCertificate(id, pubkey any) *MockcertifierServiceDeleteCertificateCall {
	_ = "STUB: not implemented"
	return nil
}

// MockcertifierServiceDeleteCertificateCall wrap *gomock.Call
type MockcertifierServiceDeleteCertificateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockcertifierServiceDeleteCertificateCall) Return(arg0 error) *MockcertifierServiceDeleteCertificateCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockcertifierServiceDeleteCertificateCall) Do(f func(types.NodeID, []byte) error) *MockcertifierServiceDeleteCertificateCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockcertifierServiceDeleteCertificateCall) DoAndReturn(f func(types.NodeID, []byte) error) *MockcertifierServiceDeleteCertificateCall {
	_ = "STUB: not implemented"
	return nil
}

// MockpoetDbAPI is a mock of poetDbAPI interface.
type MockpoetDbAPI struct {
	ctrl     *gomock.Controller
	recorder *MockpoetDbAPIMockRecorder
	isgomock struct{}
}

// MockpoetDbAPIMockRecorder is the mock recorder for MockpoetDbAPI.
type MockpoetDbAPIMockRecorder struct {
	mock *MockpoetDbAPI
}

// NewMockpoetDbAPI creates a new mock instance.
func NewMockpoetDbAPI(ctrl *gomock.Controller) *MockpoetDbAPI {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpoetDbAPI) EXPECT() *MockpoetDbAPIMockRecorder {
	_ = "STUB: not implemented"

	// Proof mocks base method.
	return nil
}

func (m *MockpoetDbAPI) Proof(arg0 types.PoetProofRef) (*types.PoetProof, *types.Hash32, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

// Proof indicates an expected call of Proof.
func (mr *MockpoetDbAPIMockRecorder) Proof(arg0 any) *MockpoetDbAPIProofCall {
	_ = "STUB: not implemented"
	return nil
}

// MockpoetDbAPIProofCall wrap *gomock.Call
type MockpoetDbAPIProofCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpoetDbAPIProofCall) Return(arg0 *types.PoetProof, arg1 *types.Hash32, arg2 error) *MockpoetDbAPIProofCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockpoetDbAPIProofCall) Do(f func(types.PoetProofRef) (*types.PoetProof, *types.Hash32, error)) *MockpoetDbAPIProofCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpoetDbAPIProofCall) DoAndReturn(f func(types.PoetProofRef) (*types.PoetProof, *types.Hash32, error)) *MockpoetDbAPIProofCall {
	_ = "STUB: not implemented"
	return nil
}

// ProofForRound mocks base method.
func (m *MockpoetDbAPI) ProofForRound(poetID []byte, roundID string) (*types.PoetProof, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ProofForRound indicates an expected call of ProofForRound.
func (mr *MockpoetDbAPIMockRecorder) ProofForRound(poetID, roundID any) *MockpoetDbAPIProofForRoundCall {
	_ = "STUB: not implemented"
	return nil
}

// MockpoetDbAPIProofForRoundCall wrap *gomock.Call
type MockpoetDbAPIProofForRoundCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpoetDbAPIProofForRoundCall) Return(arg0 *types.PoetProof, arg1 error) *MockpoetDbAPIProofForRoundCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockpoetDbAPIProofForRoundCall) Do(f func([]byte, string) (*types.PoetProof, error)) *MockpoetDbAPIProofForRoundCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpoetDbAPIProofForRoundCall) DoAndReturn(f func([]byte, string) (*types.PoetProof, error)) *MockpoetDbAPIProofForRoundCall {
	_ = "STUB: not implemented"
	return nil
}

// ValidateAndStore mocks base method.
func (m *MockpoetDbAPI) ValidateAndStore(ctx context.Context, proofMessage *types.PoetProofMessage) error {
	_ = "STUB: not implemented"
	return nil
}

// ValidateAndStore indicates an expected call of ValidateAndStore.
func (mr *MockpoetDbAPIMockRecorder) ValidateAndStore(ctx, proofMessage any) *MockpoetDbAPIValidateAndStoreCall {
	_ = "STUB: not implemented"
	return nil
}

// MockpoetDbAPIValidateAndStoreCall wrap *gomock.Call
type MockpoetDbAPIValidateAndStoreCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpoetDbAPIValidateAndStoreCall) Return(arg0 error) *MockpoetDbAPIValidateAndStoreCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockpoetDbAPIValidateAndStoreCall) Do(f func(context.Context, *types.PoetProofMessage) error) *MockpoetDbAPIValidateAndStoreCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpoetDbAPIValidateAndStoreCall) DoAndReturn(f func(context.Context, *types.PoetProofMessage) error) *MockpoetDbAPIValidateAndStoreCall {
	_ = "STUB: not implemented"
	return nil
}

// MockatxBuilder is a mock of atxBuilder interface.
type MockatxBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockatxBuilderMockRecorder
	isgomock struct{}
}

// MockatxBuilderMockRecorder is the mock recorder for MockatxBuilder.
type MockatxBuilderMockRecorder struct {
	mock *MockatxBuilder
}

// NewMockatxBuilder creates a new mock instance.
func NewMockatxBuilder(ctrl *gomock.Controller) *MockatxBuilder {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockatxBuilder) EXPECT() *MockatxBuilderMockRecorder {
	_ = "STUB: not implemented"

	// Register mocks base method.
	return nil
}

func (m *MockatxBuilder) Register(sig *signing.EdSigner) { _ = "STUB: not implemented"; return }

// Register indicates an expected call of Register.
func (mr *MockatxBuilderMockRecorder) Register(sig any) *MockatxBuilderRegisterCall {
	_ = "STUB: not implemented"
	return nil
}

// MockatxBuilderRegisterCall wrap *gomock.Call
type MockatxBuilderRegisterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockatxBuilderRegisterCall) Return() *MockatxBuilderRegisterCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockatxBuilderRegisterCall) Do(f func(*signing.EdSigner)) *MockatxBuilderRegisterCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockatxBuilderRegisterCall) DoAndReturn(f func(*signing.EdSigner)) *MockatxBuilderRegisterCall {
	_ = "STUB: not implemented"
	return nil
}

// MockpostService is a mock of postService interface.
type MockpostService struct {
	ctrl     *gomock.Controller
	recorder *MockpostServiceMockRecorder
	isgomock struct{}
}

// MockpostServiceMockRecorder is the mock recorder for MockpostService.
type MockpostServiceMockRecorder struct {
	mock *MockpostService
}

// NewMockpostService creates a new mock instance.
func NewMockpostService(ctrl *gomock.Controller) *MockpostService {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpostService) EXPECT() *MockpostServiceMockRecorder {
	_ = "STUB: not implemented"

	// Client mocks base method.
	return nil
}

func (m *MockpostService) Client(nodeId types.NodeID) (PostClient, error) {
	_ = "STUB: not implemented"
	return *new(PostClient), nil
}

// Client indicates an expected call of Client.
func (mr *MockpostServiceMockRecorder) Client(nodeId any) *MockpostServiceClientCall {
	_ = "STUB: not implemented"
	return nil
}

// MockpostServiceClientCall wrap *gomock.Call
type MockpostServiceClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpostServiceClientCall) Return(arg0 PostClient, arg1 error) *MockpostServiceClientCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockpostServiceClientCall) Do(f func(types.NodeID) (PostClient, error)) *MockpostServiceClientCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpostServiceClientCall) DoAndReturn(f func(types.NodeID) (PostClient, error)) *MockpostServiceClientCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPostClient is a mock of PostClient interface.
type MockPostClient struct {
	ctrl     *gomock.Controller
	recorder *MockPostClientMockRecorder
	isgomock struct{}
}

// MockPostClientMockRecorder is the mock recorder for MockPostClient.
type MockPostClientMockRecorder struct {
	mock *MockPostClient
}

// NewMockPostClient creates a new mock instance.
func NewMockPostClient(ctrl *gomock.Controller) *MockPostClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostClient) EXPECT() *MockPostClientMockRecorder {
	_ = "STUB: not implemented"

	// Info mocks base method.
	return nil
}

func (m *MockPostClient) Info(ctx context.Context) (*types.PostInfo, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Info indicates an expected call of Info.
func (mr *MockPostClientMockRecorder) Info(ctx any) *MockPostClientInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPostClientInfoCall wrap *gomock.Call
type MockPostClientInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPostClientInfoCall) Return(arg0 *types.PostInfo, arg1 error) *MockPostClientInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPostClientInfoCall) Do(f func(context.Context) (*types.PostInfo, error)) *MockPostClientInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPostClientInfoCall) DoAndReturn(f func(context.Context) (*types.PostInfo, error)) *MockPostClientInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// Proof mocks base method.
func (m *MockPostClient) Proof(ctx context.Context, challenge []byte) (*types.Post, *types.PostInfo, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

// Proof indicates an expected call of Proof.
func (mr *MockPostClientMockRecorder) Proof(ctx, challenge any) *MockPostClientProofCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPostClientProofCall wrap *gomock.Call
type MockPostClientProofCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPostClientProofCall) Return(arg0 *types.Post, arg1 *types.PostInfo, arg2 error) *MockPostClientProofCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPostClientProofCall) Do(f func(context.Context, []byte) (*types.Post, *types.PostInfo, error)) *MockPostClientProofCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPostClientProofCall) DoAndReturn(f func(context.Context, []byte) (*types.Post, *types.PostInfo, error)) *MockPostClientProofCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPostStates is a mock of PostStates interface.
type MockPostStates struct {
	ctrl     *gomock.Controller
	recorder *MockPostStatesMockRecorder
	isgomock struct{}
}

// MockPostStatesMockRecorder is the mock recorder for MockPostStates.
type MockPostStatesMockRecorder struct {
	mock *MockPostStates
}

// NewMockPostStates creates a new mock instance.
func NewMockPostStates(ctrl *gomock.Controller) *MockPostStates {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostStates) EXPECT() *MockPostStatesMockRecorder {
	_ = "STUB: not implemented"

	// Get mocks base method.
	return nil
}

func (m *MockPostStates) Get() map[types.NodeID]types.PostState {
	_ = "STUB: not implemented"
	return nil
}

// Get indicates an expected call of Get.
func (mr *MockPostStatesMockRecorder) Get() *MockPostStatesGetCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPostStatesGetCall wrap *gomock.Call
type MockPostStatesGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPostStatesGetCall) Return(arg0 map[types.NodeID]types.PostState) *MockPostStatesGetCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPostStatesGetCall) Do(f func() map[types.NodeID]types.PostState) *MockPostStatesGetCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPostStatesGetCall) DoAndReturn(f func() map[types.NodeID]types.PostState) *MockPostStatesGetCall {
	_ = "STUB: not implemented"
	return nil
}

// Set mocks base method.
func (m *MockPostStates) Set(id types.NodeID, state types.PostState) {
	_ = "STUB: not implemented"
	return
}

// Set indicates an expected call of Set.
func (mr *MockPostStatesMockRecorder) Set(id, state any) *MockPostStatesSetCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPostStatesSetCall wrap *gomock.Call
type MockPostStatesSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPostStatesSetCall) Return() *MockPostStatesSetCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPostStatesSetCall) Do(f func(types.NodeID, types.PostState)) *MockPostStatesSetCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPostStatesSetCall) DoAndReturn(f func(types.NodeID, types.PostState)) *MockPostStatesSetCall {
	_ = "STUB: not implemented"
	return nil
}
