// Code generated by MockGen. DO NOT EDIT.
// Source: ./poet.go
//
// Generated by this command:
//
//	mockgen -typed -package=activation -destination=poet_mocks.go -source=./poet.go
//

// Package activation is a generated GoMock package.
package activation

import (
	context "context"
	time "time"

	types "github.com/spacemeshos/go-spacemesh/common/types"
	gomock "go.uber.org/mock/gomock"
)

// MockPoetClient is a mock of PoetClient interface.
type MockPoetClient struct {
	ctrl     *gomock.Controller
	recorder *MockPoetClientMockRecorder
	isgomock struct{}
}

// MockPoetClientMockRecorder is the mock recorder for MockPoetClient.
type MockPoetClientMockRecorder struct {
	mock *MockPoetClient
}

// NewMockPoetClient creates a new mock instance.
func NewMockPoetClient(ctrl *gomock.Controller) *MockPoetClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoetClient) EXPECT() *MockPoetClientMockRecorder {
	_ = "STUB: not implemented"

	// Address mocks base method.
	return nil
}

func (m *MockPoetClient) Address() string { _ = "STUB: not implemented"; return "" }

// Address indicates an expected call of Address.
func (mr *MockPoetClientMockRecorder) Address() *MockPoetClientAddressCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPoetClientAddressCall wrap *gomock.Call
type MockPoetClientAddressCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPoetClientAddressCall) Return(arg0 string) *MockPoetClientAddressCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPoetClientAddressCall) Do(f func() string) *MockPoetClientAddressCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPoetClientAddressCall) DoAndReturn(f func() string) *MockPoetClientAddressCall {
	_ = "STUB: not implemented"
	return nil
}

// Id mocks base method.
func (m *MockPoetClient) Id() []byte { _ = "STUB: not implemented"; return nil }

// Id indicates an expected call of Id.
func (mr *MockPoetClientMockRecorder) Id() *MockPoetClientIdCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPoetClientIdCall wrap *gomock.Call
type MockPoetClientIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPoetClientIdCall) Return(arg0 []byte) *MockPoetClientIdCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPoetClientIdCall) Do(f func() []byte) *MockPoetClientIdCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPoetClientIdCall) DoAndReturn(f func() []byte) *MockPoetClientIdCall {
	_ = "STUB: not implemented"
	return nil
}

// Info mocks base method.
func (m *MockPoetClient) Info(ctx context.Context) (*types.PoetInfo, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Info indicates an expected call of Info.
func (mr *MockPoetClientMockRecorder) Info(ctx any) *MockPoetClientInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPoetClientInfoCall wrap *gomock.Call
type MockPoetClientInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPoetClientInfoCall) Return(arg0 *types.PoetInfo, arg1 error) *MockPoetClientInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPoetClientInfoCall) Do(f func(context.Context) (*types.PoetInfo, error)) *MockPoetClientInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPoetClientInfoCall) DoAndReturn(f func(context.Context) (*types.PoetInfo, error)) *MockPoetClientInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// PowParams mocks base method.
func (m *MockPoetClient) PowParams(ctx context.Context) (*PoetPowParams, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PowParams indicates an expected call of PowParams.
func (mr *MockPoetClientMockRecorder) PowParams(ctx any) *MockPoetClientPowParamsCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPoetClientPowParamsCall wrap *gomock.Call
type MockPoetClientPowParamsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPoetClientPowParamsCall) Return(arg0 *PoetPowParams, arg1 error) *MockPoetClientPowParamsCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPoetClientPowParamsCall) Do(f func(context.Context) (*PoetPowParams, error)) *MockPoetClientPowParamsCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPoetClientPowParamsCall) DoAndReturn(f func(context.Context) (*PoetPowParams, error)) *MockPoetClientPowParamsCall {
	_ = "STUB: not implemented"
	return nil
}

// Proof mocks base method.
func (m *MockPoetClient) Proof(ctx context.Context, roundID string) (*types.PoetProofMessage, []types.Hash32, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

// Proof indicates an expected call of Proof.
func (mr *MockPoetClientMockRecorder) Proof(ctx, roundID any) *MockPoetClientProofCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPoetClientProofCall wrap *gomock.Call
type MockPoetClientProofCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPoetClientProofCall) Return(arg0 *types.PoetProofMessage, arg1 []types.Hash32, arg2 error) *MockPoetClientProofCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPoetClientProofCall) Do(f func(context.Context, string) (*types.PoetProofMessage, []types.Hash32, error)) *MockPoetClientProofCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPoetClientProofCall) DoAndReturn(f func(context.Context, string) (*types.PoetProofMessage, []types.Hash32, error)) *MockPoetClientProofCall {
	_ = "STUB: not implemented"
	return nil
}

// Submit mocks base method.
func (m *MockPoetClient) Submit(ctx context.Context, deadline time.Time, prefix, challenge []byte, signature types.EdSignature, nodeID types.NodeID, auth PoetAuth) (*types.PoetRound, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Submit indicates an expected call of Submit.
func (mr *MockPoetClientMockRecorder) Submit(ctx, deadline, prefix, challenge, signature, nodeID, auth any) *MockPoetClientSubmitCall {
	_ = "STUB: not implemented"
	return nil
}

// MockPoetClientSubmitCall wrap *gomock.Call
type MockPoetClientSubmitCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPoetClientSubmitCall) Return(arg0 *types.PoetRound, arg1 error) *MockPoetClientSubmitCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockPoetClientSubmitCall) Do(f func(context.Context, time.Time, []byte, []byte, types.EdSignature, types.NodeID, PoetAuth) (*types.PoetRound, error)) *MockPoetClientSubmitCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPoetClientSubmitCall) DoAndReturn(f func(context.Context, time.Time, []byte, []byte, types.EdSignature, types.NodeID, PoetAuth) (*types.PoetRound, error)) *MockPoetClientSubmitCall {
	_ = "STUB: not implemented"
	return nil
}
