// Code generated by MockGen. DO NOT EDIT.
// Source: ./beacons.go
//
// Generated by this command:
//
//	mockgen -typed -package=mocks -destination=./mocks/beacons.go -source=./beacons.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	fixed "github.com/spacemeshos/fixed"
	types "github.com/spacemeshos/go-spacemesh/common/types"
	gomock "go.uber.org/mock/gomock"
)

// MockBeaconCollector is a mock of BeaconCollector interface.
type MockBeaconCollector struct {
	ctrl     *gomock.Controller
	recorder *MockBeaconCollectorMockRecorder
	isgomock struct{}
}

// MockBeaconCollectorMockRecorder is the mock recorder for MockBeaconCollector.
type MockBeaconCollectorMockRecorder struct {
	mock *MockBeaconCollector
}

// NewMockBeaconCollector creates a new mock instance.
func NewMockBeaconCollector(ctrl *gomock.Controller) *MockBeaconCollector {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBeaconCollector) EXPECT() *MockBeaconCollectorMockRecorder {
	_ = "STUB: not implemented"

	// ReportBeaconFromBallot mocks base method.
	return nil
}

func (m *MockBeaconCollector) ReportBeaconFromBallot(arg0 types.EpochID, arg1 *types.Ballot, arg2 types.Beacon, arg3 fixed.Fixed) {
	_ = "STUB: not implemented"
	return
}

// ReportBeaconFromBallot indicates an expected call of ReportBeaconFromBallot.
func (mr *MockBeaconCollectorMockRecorder) ReportBeaconFromBallot(arg0, arg1, arg2, arg3 any) *MockBeaconCollectorReportBeaconFromBallotCall {
	_ = "STUB: not implemented"
	return nil
}

// MockBeaconCollectorReportBeaconFromBallotCall wrap *gomock.Call
type MockBeaconCollectorReportBeaconFromBallotCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBeaconCollectorReportBeaconFromBallotCall) Return() *MockBeaconCollectorReportBeaconFromBallotCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockBeaconCollectorReportBeaconFromBallotCall) Do(f func(types.EpochID, *types.Ballot, types.Beacon, fixed.Fixed)) *MockBeaconCollectorReportBeaconFromBallotCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBeaconCollectorReportBeaconFromBallotCall) DoAndReturn(f func(types.EpochID, *types.Ballot, types.Beacon, fixed.Fixed)) *MockBeaconCollectorReportBeaconFromBallotCall {
	_ = "STUB: not implemented"
	return nil
}

// MockBeaconGetter is a mock of BeaconGetter interface.
type MockBeaconGetter struct {
	ctrl     *gomock.Controller
	recorder *MockBeaconGetterMockRecorder
	isgomock struct{}
}

// MockBeaconGetterMockRecorder is the mock recorder for MockBeaconGetter.
type MockBeaconGetterMockRecorder struct {
	mock *MockBeaconGetter
}

// NewMockBeaconGetter creates a new mock instance.
func NewMockBeaconGetter(ctrl *gomock.Controller) *MockBeaconGetter {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBeaconGetter) EXPECT() *MockBeaconGetterMockRecorder {
	_ = "STUB: not implemented"

	// GetBeacon mocks base method.
	return nil
}

func (m *MockBeaconGetter) GetBeacon(arg0 types.EpochID) (types.Beacon, error) {
	_ = "STUB: not implemented"
	return *new(types.Beacon), nil
}

// GetBeacon indicates an expected call of GetBeacon.
func (mr *MockBeaconGetterMockRecorder) GetBeacon(arg0 any) *MockBeaconGetterGetBeaconCall {
	_ = "STUB: not implemented"
	return nil
}

// MockBeaconGetterGetBeaconCall wrap *gomock.Call
type MockBeaconGetterGetBeaconCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBeaconGetterGetBeaconCall) Return(arg0 types.Beacon, arg1 error) *MockBeaconGetterGetBeaconCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockBeaconGetterGetBeaconCall) Do(f func(types.EpochID) (types.Beacon, error)) *MockBeaconGetterGetBeaconCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBeaconGetterGetBeaconCall) DoAndReturn(f func(types.EpochID) (types.Beacon, error)) *MockBeaconGetterGetBeaconCall {
	_ = "STUB: not implemented"
	return nil
}
