// Code generated by MockGen. DO NOT EDIT.
// Source: ./sync.go
//
// Generated by this command:
//
//	mockgen -typed -package=mocks -destination=./mocks/sync.go -source=./sync.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	gomock "go.uber.org/mock/gomock"
)

// MockSyncStateProvider is a mock of SyncStateProvider interface.
type MockSyncStateProvider struct {
	ctrl     *gomock.Controller
	recorder *MockSyncStateProviderMockRecorder
	isgomock struct{}
}

// MockSyncStateProviderMockRecorder is the mock recorder for MockSyncStateProvider.
type MockSyncStateProviderMockRecorder struct {
	mock *MockSyncStateProvider
}

// NewMockSyncStateProvider creates a new mock instance.
func NewMockSyncStateProvider(ctrl *gomock.Controller) *MockSyncStateProvider {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncStateProvider) EXPECT() *MockSyncStateProviderMockRecorder {
	_ = "STUB: not implemented"

	// IsSynced mocks base method.
	return nil
}

func (m *MockSyncStateProvider) IsSynced(arg0 context.Context) bool {
	_ = "STUB: not implemented"
	return false
}

// IsSynced indicates an expected call of IsSynced.
func (mr *MockSyncStateProviderMockRecorder) IsSynced(arg0 any) *MockSyncStateProviderIsSyncedCall {
	_ = "STUB: not implemented"
	return nil
}

// MockSyncStateProviderIsSyncedCall wrap *gomock.Call
type MockSyncStateProviderIsSyncedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSyncStateProviderIsSyncedCall) Return(arg0 bool) *MockSyncStateProviderIsSyncedCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockSyncStateProviderIsSyncedCall) Do(f func(context.Context) bool) *MockSyncStateProviderIsSyncedCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSyncStateProviderIsSyncedCall) DoAndReturn(f func(context.Context) bool) *MockSyncStateProviderIsSyncedCall {
	_ = "STUB: not implemented"
	return nil
}
