// Code generated by MockGen. DO NOT EDIT.
// Source: ./tortoise.go
//
// Generated by this command:
//
//	mockgen -typed -package=mocks -destination=./mocks/tortoise.go -source=./tortoise.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	atxsdata "github.com/spacemeshos/go-spacemesh/atxsdata"
	types "github.com/spacemeshos/go-spacemesh/common/types"
	result "github.com/spacemeshos/go-spacemesh/common/types/result"
	gomock "go.uber.org/mock/gomock"
)

// MockTortoise is a mock of Tortoise interface.
type MockTortoise struct {
	ctrl     *gomock.Controller
	recorder *MockTortoiseMockRecorder
	isgomock struct{}
}

// MockTortoiseMockRecorder is the mock recorder for MockTortoise.
type MockTortoiseMockRecorder struct {
	mock *MockTortoise
}

// NewMockTortoise creates a new mock instance.
func NewMockTortoise(ctrl *gomock.Controller) *MockTortoise { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTortoise) EXPECT() *MockTortoiseMockRecorder {
	_ = "STUB: not implemented"

	// GetMissingActiveSet mocks base method.
	return nil
}

func (m *MockTortoise) GetMissingActiveSet(arg0 types.EpochID, arg1 []types.ATXID) []types.ATXID {
	_ = "STUB: not implemented"
	return nil
}

// GetMissingActiveSet indicates an expected call of GetMissingActiveSet.
func (mr *MockTortoiseMockRecorder) GetMissingActiveSet(arg0, arg1 any) *MockTortoiseGetMissingActiveSetCall {
	_ = "STUB: not implemented"
	return nil
}

// MockTortoiseGetMissingActiveSetCall wrap *gomock.Call
type MockTortoiseGetMissingActiveSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTortoiseGetMissingActiveSetCall) Return(arg0 []types.ATXID) *MockTortoiseGetMissingActiveSetCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockTortoiseGetMissingActiveSetCall) Do(f func(types.EpochID, []types.ATXID) []types.ATXID) *MockTortoiseGetMissingActiveSetCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTortoiseGetMissingActiveSetCall) DoAndReturn(f func(types.EpochID, []types.ATXID) []types.ATXID) *MockTortoiseGetMissingActiveSetCall {
	_ = "STUB: not implemented"
	return nil
}

// LatestComplete mocks base method.
func (m *MockTortoise) LatestComplete() types.LayerID {
	_ = "STUB: not implemented"
	return *new(types.LayerID)
}

// LatestComplete indicates an expected call of LatestComplete.
func (mr *MockTortoiseMockRecorder) LatestComplete() *MockTortoiseLatestCompleteCall {
	_ = "STUB: not implemented"
	return nil
}

// MockTortoiseLatestCompleteCall wrap *gomock.Call
type MockTortoiseLatestCompleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTortoiseLatestCompleteCall) Return(arg0 types.LayerID) *MockTortoiseLatestCompleteCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockTortoiseLatestCompleteCall) Do(f func() types.LayerID) *MockTortoiseLatestCompleteCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTortoiseLatestCompleteCall) DoAndReturn(f func() types.LayerID) *MockTortoiseLatestCompleteCall {
	_ = "STUB: not implemented"
	return nil
}

// OnApplied mocks base method.
func (m *MockTortoise) OnApplied(arg0 types.LayerID, arg1 types.Hash32) bool {
	_ = "STUB: not implemented"
	return false
}

// OnApplied indicates an expected call of OnApplied.
func (mr *MockTortoiseMockRecorder) OnApplied(arg0, arg1 any) *MockTortoiseOnAppliedCall {
	_ = "STUB: not implemented"
	return nil
}

// MockTortoiseOnAppliedCall wrap *gomock.Call
type MockTortoiseOnAppliedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTortoiseOnAppliedCall) Return(arg0 bool) *MockTortoiseOnAppliedCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockTortoiseOnAppliedCall) Do(f func(types.LayerID, types.Hash32) bool) *MockTortoiseOnAppliedCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTortoiseOnAppliedCall) DoAndReturn(f func(types.LayerID, types.Hash32) bool) *MockTortoiseOnAppliedCall {
	_ = "STUB: not implemented"
	return nil
}

// OnAtx mocks base method.
func (m *MockTortoise) OnAtx(arg0 types.EpochID, arg1 types.ATXID, arg2 *atxsdata.ATX) {
	_ = "STUB: not implemented"
	return
}

// OnAtx indicates an expected call of OnAtx.
func (mr *MockTortoiseMockRecorder) OnAtx(arg0, arg1, arg2 any) *MockTortoiseOnAtxCall {
	_ = "STUB: not implemented"
	return nil
}

// MockTortoiseOnAtxCall wrap *gomock.Call
type MockTortoiseOnAtxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTortoiseOnAtxCall) Return() *MockTortoiseOnAtxCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockTortoiseOnAtxCall) Do(f func(types.EpochID, types.ATXID, *atxsdata.ATX)) *MockTortoiseOnAtxCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTortoiseOnAtxCall) DoAndReturn(f func(types.EpochID, types.ATXID, *atxsdata.ATX)) *MockTortoiseOnAtxCall {
	_ = "STUB: not implemented"
	return nil
}

// OnBlock mocks base method.
func (m *MockTortoise) OnBlock(arg0 types.BlockHeader) { _ = "STUB: not implemented"; return }

// OnBlock indicates an expected call of OnBlock.
func (mr *MockTortoiseMockRecorder) OnBlock(arg0 any) *MockTortoiseOnBlockCall {
	_ = "STUB: not implemented"
	return nil
}

// MockTortoiseOnBlockCall wrap *gomock.Call
type MockTortoiseOnBlockCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTortoiseOnBlockCall) Return() *MockTortoiseOnBlockCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockTortoiseOnBlockCall) Do(f func(types.BlockHeader)) *MockTortoiseOnBlockCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTortoiseOnBlockCall) DoAndReturn(f func(types.BlockHeader)) *MockTortoiseOnBlockCall {
	_ = "STUB: not implemented"
	return nil
}

// OnHareOutput mocks base method.
func (m *MockTortoise) OnHareOutput(arg0 types.LayerID, arg1 types.BlockID) {
	_ = "STUB: not implemented"
	return
}

// OnHareOutput indicates an expected call of OnHareOutput.
func (mr *MockTortoiseMockRecorder) OnHareOutput(arg0, arg1 any) *MockTortoiseOnHareOutputCall {
	_ = "STUB: not implemented"
	return nil
}

// MockTortoiseOnHareOutputCall wrap *gomock.Call
type MockTortoiseOnHareOutputCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTortoiseOnHareOutputCall) Return() *MockTortoiseOnHareOutputCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockTortoiseOnHareOutputCall) Do(f func(types.LayerID, types.BlockID)) *MockTortoiseOnHareOutputCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTortoiseOnHareOutputCall) DoAndReturn(f func(types.LayerID, types.BlockID)) *MockTortoiseOnHareOutputCall {
	_ = "STUB: not implemented"
	return nil
}

// OnMalfeasance mocks base method.
func (m *MockTortoise) OnMalfeasance(arg0 types.NodeID) { _ = "STUB: not implemented"; return }

// OnMalfeasance indicates an expected call of OnMalfeasance.
func (mr *MockTortoiseMockRecorder) OnMalfeasance(arg0 any) *MockTortoiseOnMalfeasanceCall {
	_ = "STUB: not implemented"
	return nil
}

// MockTortoiseOnMalfeasanceCall wrap *gomock.Call
type MockTortoiseOnMalfeasanceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTortoiseOnMalfeasanceCall) Return() *MockTortoiseOnMalfeasanceCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockTortoiseOnMalfeasanceCall) Do(f func(types.NodeID)) *MockTortoiseOnMalfeasanceCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTortoiseOnMalfeasanceCall) DoAndReturn(f func(types.NodeID)) *MockTortoiseOnMalfeasanceCall {
	_ = "STUB: not implemented"
	return nil
}

// OnWeakCoin mocks base method.
func (m *MockTortoise) OnWeakCoin(arg0 types.LayerID, arg1 bool) { _ = "STUB: not implemented"; return }

// OnWeakCoin indicates an expected call of OnWeakCoin.
func (mr *MockTortoiseMockRecorder) OnWeakCoin(arg0, arg1 any) *MockTortoiseOnWeakCoinCall {
	_ = "STUB: not implemented"
	return nil
}

// MockTortoiseOnWeakCoinCall wrap *gomock.Call
type MockTortoiseOnWeakCoinCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTortoiseOnWeakCoinCall) Return() *MockTortoiseOnWeakCoinCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockTortoiseOnWeakCoinCall) Do(f func(types.LayerID, bool)) *MockTortoiseOnWeakCoinCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTortoiseOnWeakCoinCall) DoAndReturn(f func(types.LayerID, bool)) *MockTortoiseOnWeakCoinCall {
	_ = "STUB: not implemented"
	return nil
}

// TallyVotes mocks base method.
func (m *MockTortoise) TallyVotes(arg0 types.LayerID) { _ = "STUB: not implemented"; return }

// TallyVotes indicates an expected call of TallyVotes.
func (mr *MockTortoiseMockRecorder) TallyVotes(arg0 any) *MockTortoiseTallyVotesCall {
	_ = "STUB: not implemented"
	return nil
}

// MockTortoiseTallyVotesCall wrap *gomock.Call
type MockTortoiseTallyVotesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTortoiseTallyVotesCall) Return() *MockTortoiseTallyVotesCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockTortoiseTallyVotesCall) Do(f func(types.LayerID)) *MockTortoiseTallyVotesCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTortoiseTallyVotesCall) DoAndReturn(f func(types.LayerID)) *MockTortoiseTallyVotesCall {
	_ = "STUB: not implemented"
	return nil
}

// Updates mocks base method.
func (m *MockTortoise) Updates() []result.Layer { _ = "STUB: not implemented"; return nil }

// Updates indicates an expected call of Updates.
func (mr *MockTortoiseMockRecorder) Updates() *MockTortoiseUpdatesCall {
	_ = "STUB: not implemented"
	return nil
}

// MockTortoiseUpdatesCall wrap *gomock.Call
type MockTortoiseUpdatesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTortoiseUpdatesCall) Return(arg0 []result.Layer) *MockTortoiseUpdatesCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockTortoiseUpdatesCall) Do(f func() []result.Layer) *MockTortoiseUpdatesCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTortoiseUpdatesCall) DoAndReturn(f func() []result.Layer) *MockTortoiseUpdatesCall {
	_ = "STUB: not implemented"
	return nil
}
