// Code generated by MockGen. DO NOT EDIT.
// Source: ./vm.go
//
// Generated by this command:
//
//	mockgen -typed -package=mocks -destination=./mocks/vm.go -source=./vm.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	types "github.com/spacemeshos/go-spacemesh/common/types"
	gomock "go.uber.org/mock/gomock"
)

// MockValidationRequest is a mock of ValidationRequest interface.
type MockValidationRequest struct {
	ctrl     *gomock.Controller
	recorder *MockValidationRequestMockRecorder
	isgomock struct{}
}

// MockValidationRequestMockRecorder is the mock recorder for MockValidationRequest.
type MockValidationRequestMockRecorder struct {
	mock *MockValidationRequest
}

// NewMockValidationRequest creates a new mock instance.
func NewMockValidationRequest(ctrl *gomock.Controller) *MockValidationRequest {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidationRequest) EXPECT() *MockValidationRequestMockRecorder {
	_ = "STUB: not implemented"

	// Parse mocks base method.
	return nil
}

func (m *MockValidationRequest) Parse() (*types.TxHeader, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Parse indicates an expected call of Parse.
func (mr *MockValidationRequestMockRecorder) Parse() *MockValidationRequestParseCall {
	_ = "STUB: not implemented"
	return nil
}

// MockValidationRequestParseCall wrap *gomock.Call
type MockValidationRequestParseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockValidationRequestParseCall) Return(arg0 *types.TxHeader, arg1 error) *MockValidationRequestParseCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockValidationRequestParseCall) Do(f func() (*types.TxHeader, error)) *MockValidationRequestParseCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockValidationRequestParseCall) DoAndReturn(f func() (*types.TxHeader, error)) *MockValidationRequestParseCall {
	_ = "STUB: not implemented"
	return nil
}

// Verify mocks base method.
func (m *MockValidationRequest) Verify() bool { _ = "STUB: not implemented"; return false }

// Verify indicates an expected call of Verify.
func (mr *MockValidationRequestMockRecorder) Verify() *MockValidationRequestVerifyCall {
	_ = "STUB: not implemented"
	return nil
}

// MockValidationRequestVerifyCall wrap *gomock.Call
type MockValidationRequestVerifyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockValidationRequestVerifyCall) Return(arg0 bool) *MockValidationRequestVerifyCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockValidationRequestVerifyCall) Do(f func() bool) *MockValidationRequestVerifyCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockValidationRequestVerifyCall) DoAndReturn(f func() bool) *MockValidationRequestVerifyCall {
	_ = "STUB: not implemented"
	return nil
}
