// Code generated by github.com/spacemeshos/go-scale/scalegen. DO NOT EDIT.

// nolint
package types

import (
	"github.com/spacemeshos/go-scale"
)

func (t *Ballot) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *Ballot) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *BallotMetadata) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *BallotMetadata) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *InnerBallot) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *InnerBallot) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *Votes) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *Votes) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *BlockHeader) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *BlockHeader) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *Opinion) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *Opinion) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *EpochData) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *EpochData) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}
