// Code generated by github.com/spacemeshos/go-scale/scalegen. DO NOT EDIT.

// nolint
package types

import (
	"github.com/spacemeshos/go-scale"
)

func (t *Block) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *Block) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *InnerBlock) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *InnerBlock) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *RatNum) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *RatNum) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *AnyReward) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *AnyReward) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *Certificate) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *Certificate) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *CertifyMessage) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *CertifyMessage) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *CertifyContent) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *CertifyContent) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}
