// Code generated by github.com/spacemeshos/go-scale/scalegen. DO NOT EDIT.

// nolint
package types

import (
	"github.com/spacemeshos/go-scale"
)

func (t *HareEligibilityGossip) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *HareEligibilityGossip) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *HareEligibility) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *HareEligibility) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *VotingEligibility) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *VotingEligibility) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}
