// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -typed -package=mocks -destination=./mocks/mocks.go -source=./interface.go -exclude_interfaces Host,PeerInfoHost
//

// Package mocks is a generated GoMock package.
package mocks

import (
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockpeerStream is a mock of peerStream interface.
type MockpeerStream struct {
	ctrl     *gomock.Controller
	recorder *MockpeerStreamMockRecorder
	isgomock struct{}
}

// MockpeerStreamMockRecorder is the mock recorder for MockpeerStream.
type MockpeerStreamMockRecorder struct {
	mock *MockpeerStream
}

// NewMockpeerStream creates a new mock instance.
func NewMockpeerStream(ctrl *gomock.Controller) *MockpeerStream {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpeerStream) EXPECT() *MockpeerStreamMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockpeerStream) Close() error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockpeerStreamMockRecorder) Close() *MockpeerStreamCloseCall {
	_ = "STUB: not implemented"
	return nil
}

// MockpeerStreamCloseCall wrap *gomock.Call
type MockpeerStreamCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpeerStreamCloseCall) Return(arg0 error) *MockpeerStreamCloseCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockpeerStreamCloseCall) Do(f func() error) *MockpeerStreamCloseCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpeerStreamCloseCall) DoAndReturn(f func() error) *MockpeerStreamCloseCall {
	_ = "STUB: not implemented"
	return nil
}

// Read mocks base method.
func (m *MockpeerStream) Read(p []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

// Read indicates an expected call of Read.
func (mr *MockpeerStreamMockRecorder) Read(p any) *MockpeerStreamReadCall {
	_ = "STUB: not implemented"
	return nil
}

// MockpeerStreamReadCall wrap *gomock.Call
type MockpeerStreamReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpeerStreamReadCall) Return(n int, err error) *MockpeerStreamReadCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockpeerStreamReadCall) Do(f func([]byte) (int, error)) *MockpeerStreamReadCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpeerStreamReadCall) DoAndReturn(f func([]byte) (int, error)) *MockpeerStreamReadCall {
	_ = "STUB: not implemented"
	return nil
}

// SetDeadline mocks base method.
func (m *MockpeerStream) SetDeadline(arg0 time.Time) error { _ = "STUB: not implemented"; return nil }

// SetDeadline indicates an expected call of SetDeadline.
func (mr *MockpeerStreamMockRecorder) SetDeadline(arg0 any) *MockpeerStreamSetDeadlineCall {
	_ = "STUB: not implemented"
	return nil
}

// MockpeerStreamSetDeadlineCall wrap *gomock.Call
type MockpeerStreamSetDeadlineCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpeerStreamSetDeadlineCall) Return(arg0 error) *MockpeerStreamSetDeadlineCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockpeerStreamSetDeadlineCall) Do(f func(time.Time) error) *MockpeerStreamSetDeadlineCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpeerStreamSetDeadlineCall) DoAndReturn(f func(time.Time) error) *MockpeerStreamSetDeadlineCall {
	_ = "STUB: not implemented"
	return nil
}

// Write mocks base method.
func (m *MockpeerStream) Write(p []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

// Write indicates an expected call of Write.
func (mr *MockpeerStreamMockRecorder) Write(p any) *MockpeerStreamWriteCall {
	_ = "STUB: not implemented"
	return nil
}

// MockpeerStreamWriteCall wrap *gomock.Call
type MockpeerStreamWriteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpeerStreamWriteCall) Return(n int, err error) *MockpeerStreamWriteCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockpeerStreamWriteCall) Do(f func([]byte) (int, error)) *MockpeerStreamWriteCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpeerStreamWriteCall) DoAndReturn(f func([]byte) (int, error)) *MockpeerStreamWriteCall {
	_ = "STUB: not implemented"
	return nil
}
