// Code generated by MockGen. DO NOT EDIT.
// Source: ./proposal_builder.go
//
// Generated by this command:
//
//	mockgen -typed -package=mocks -destination=./mocks/mocks.go -source=./proposal_builder.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	time "time"

	atxsdata "github.com/spacemeshos/go-spacemesh/atxsdata"
	types "github.com/spacemeshos/go-spacemesh/common/types"
	tortoise "github.com/spacemeshos/go-spacemesh/tortoise"
	gomock "go.uber.org/mock/gomock"
)

// MockconservativeState is a mock of conservativeState interface.
type MockconservativeState struct {
	ctrl     *gomock.Controller
	recorder *MockconservativeStateMockRecorder
	isgomock struct{}
}

// MockconservativeStateMockRecorder is the mock recorder for MockconservativeState.
type MockconservativeStateMockRecorder struct {
	mock *MockconservativeState
}

// NewMockconservativeState creates a new mock instance.
func NewMockconservativeState(ctrl *gomock.Controller) *MockconservativeState {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconservativeState) EXPECT() *MockconservativeStateMockRecorder {
	_ = "STUB: not implemented"

	// SelectProposalTXs mocks base method.
	return nil
}

func (m *MockconservativeState) SelectProposalTXs(arg0 types.LayerID, arg1 int) []types.TransactionID {
	_ = "STUB: not implemented"
	return nil
}

// SelectProposalTXs indicates an expected call of SelectProposalTXs.
func (mr *MockconservativeStateMockRecorder) SelectProposalTXs(arg0, arg1 any) *MockconservativeStateSelectProposalTXsCall {
	_ = "STUB: not implemented"
	return nil
}

// MockconservativeStateSelectProposalTXsCall wrap *gomock.Call
type MockconservativeStateSelectProposalTXsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockconservativeStateSelectProposalTXsCall) Return(arg0 []types.TransactionID) *MockconservativeStateSelectProposalTXsCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockconservativeStateSelectProposalTXsCall) Do(f func(types.LayerID, int) []types.TransactionID) *MockconservativeStateSelectProposalTXsCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockconservativeStateSelectProposalTXsCall) DoAndReturn(f func(types.LayerID, int) []types.TransactionID) *MockconservativeStateSelectProposalTXsCall {
	_ = "STUB: not implemented"
	return nil
}

// MockvotesEncoder is a mock of votesEncoder interface.
type MockvotesEncoder struct {
	ctrl     *gomock.Controller
	recorder *MockvotesEncoderMockRecorder
	isgomock struct{}
}

// MockvotesEncoderMockRecorder is the mock recorder for MockvotesEncoder.
type MockvotesEncoderMockRecorder struct {
	mock *MockvotesEncoder
}

// NewMockvotesEncoder creates a new mock instance.
func NewMockvotesEncoder(ctrl *gomock.Controller) *MockvotesEncoder {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvotesEncoder) EXPECT() *MockvotesEncoderMockRecorder {
	_ = "STUB: not implemented"

	// EncodeVotes mocks base method.
	return nil
}

func (m *MockvotesEncoder) EncodeVotes(arg0 context.Context, arg1 ...tortoise.EncodeVotesOpts) (*types.Opinion, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// EncodeVotes indicates an expected call of EncodeVotes.
func (mr *MockvotesEncoderMockRecorder) EncodeVotes(arg0 any, arg1 ...any) *MockvotesEncoderEncodeVotesCall {
	_ = "STUB: not implemented"
	return nil
}

// MockvotesEncoderEncodeVotesCall wrap *gomock.Call
type MockvotesEncoderEncodeVotesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockvotesEncoderEncodeVotesCall) Return(arg0 *types.Opinion, arg1 error) *MockvotesEncoderEncodeVotesCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockvotesEncoderEncodeVotesCall) Do(f func(context.Context, ...tortoise.EncodeVotesOpts) (*types.Opinion, error)) *MockvotesEncoderEncodeVotesCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockvotesEncoderEncodeVotesCall) DoAndReturn(f func(context.Context, ...tortoise.EncodeVotesOpts) (*types.Opinion, error)) *MockvotesEncoderEncodeVotesCall {
	_ = "STUB: not implemented"
	return nil
}

// LatestComplete mocks base method.
func (m *MockvotesEncoder) LatestComplete() types.LayerID {
	_ = "STUB: not implemented"
	return *new(types.LayerID)
}

// LatestComplete indicates an expected call of LatestComplete.
func (mr *MockvotesEncoderMockRecorder) LatestComplete() *MockvotesEncoderLatestCompleteCall {
	_ = "STUB: not implemented"
	return nil
}

// MockvotesEncoderLatestCompleteCall wrap *gomock.Call
type MockvotesEncoderLatestCompleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockvotesEncoderLatestCompleteCall) Return(arg0 types.LayerID) *MockvotesEncoderLatestCompleteCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockvotesEncoderLatestCompleteCall) Do(f func() types.LayerID) *MockvotesEncoderLatestCompleteCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockvotesEncoderLatestCompleteCall) DoAndReturn(f func() types.LayerID) *MockvotesEncoderLatestCompleteCall {
	_ = "STUB: not implemented"
	return nil
}

// TallyVotes mocks base method.
func (m *MockvotesEncoder) TallyVotes(arg0 types.LayerID) { _ = "STUB: not implemented"; return }

// TallyVotes indicates an expected call of TallyVotes.
func (mr *MockvotesEncoderMockRecorder) TallyVotes(arg0 any) *MockvotesEncoderTallyVotesCall {
	_ = "STUB: not implemented"
	return nil
}

// MockvotesEncoderTallyVotesCall wrap *gomock.Call
type MockvotesEncoderTallyVotesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockvotesEncoderTallyVotesCall) Return() *MockvotesEncoderTallyVotesCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockvotesEncoderTallyVotesCall) Do(f func(types.LayerID)) *MockvotesEncoderTallyVotesCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockvotesEncoderTallyVotesCall) DoAndReturn(f func(types.LayerID)) *MockvotesEncoderTallyVotesCall {
	_ = "STUB: not implemented"
	return nil
}

// MocklayerClock is a mock of layerClock interface.
type MocklayerClock struct {
	ctrl     *gomock.Controller
	recorder *MocklayerClockMockRecorder
	isgomock struct{}
}

// MocklayerClockMockRecorder is the mock recorder for MocklayerClock.
type MocklayerClockMockRecorder struct {
	mock *MocklayerClock
}

// NewMocklayerClock creates a new mock instance.
func NewMocklayerClock(ctrl *gomock.Controller) *MocklayerClock {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklayerClock) EXPECT() *MocklayerClockMockRecorder {
	_ = "STUB: not implemented"

	// AwaitLayer mocks base method.
	return nil
}

func (m *MocklayerClock) AwaitLayer(layerID types.LayerID) <-chan struct{} {
	_ = "STUB: not implemented"
	return nil
}

// AwaitLayer indicates an expected call of AwaitLayer.
func (mr *MocklayerClockMockRecorder) AwaitLayer(layerID any) *MocklayerClockAwaitLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// MocklayerClockAwaitLayerCall wrap *gomock.Call
type MocklayerClockAwaitLayerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocklayerClockAwaitLayerCall) Return(arg0 <-chan struct{}) *MocklayerClockAwaitLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocklayerClockAwaitLayerCall) Do(f func(types.LayerID) <-chan struct{}) *MocklayerClockAwaitLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocklayerClockAwaitLayerCall) DoAndReturn(f func(types.LayerID) <-chan struct{}) *MocklayerClockAwaitLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// CurrentLayer mocks base method.
func (m *MocklayerClock) CurrentLayer() types.LayerID {
	_ = "STUB: not implemented"
	return *new(types.LayerID)
}

// CurrentLayer indicates an expected call of CurrentLayer.
func (mr *MocklayerClockMockRecorder) CurrentLayer() *MocklayerClockCurrentLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// MocklayerClockCurrentLayerCall wrap *gomock.Call
type MocklayerClockCurrentLayerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocklayerClockCurrentLayerCall) Return(arg0 types.LayerID) *MocklayerClockCurrentLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocklayerClockCurrentLayerCall) Do(f func() types.LayerID) *MocklayerClockCurrentLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocklayerClockCurrentLayerCall) DoAndReturn(f func() types.LayerID) *MocklayerClockCurrentLayerCall {
	_ = "STUB: not implemented"
	return nil
}

// LayerToTime mocks base method.
func (m *MocklayerClock) LayerToTime(arg0 types.LayerID) time.Time {
	_ = "STUB: not implemented"
	return *new(time.Time)
}

// LayerToTime indicates an expected call of LayerToTime.
func (mr *MocklayerClockMockRecorder) LayerToTime(arg0 any) *MocklayerClockLayerToTimeCall {
	_ = "STUB: not implemented"
	return nil
}

// MocklayerClockLayerToTimeCall wrap *gomock.Call
type MocklayerClockLayerToTimeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocklayerClockLayerToTimeCall) Return(arg0 time.Time) *MocklayerClockLayerToTimeCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MocklayerClockLayerToTimeCall) Do(f func(types.LayerID) time.Time) *MocklayerClockLayerToTimeCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocklayerClockLayerToTimeCall) DoAndReturn(f func(types.LayerID) time.Time) *MocklayerClockLayerToTimeCall {
	_ = "STUB: not implemented"
	return nil
}

// MockatxsData is a mock of atxsData interface.
type MockatxsData struct {
	ctrl     *gomock.Controller
	recorder *MockatxsDataMockRecorder
	isgomock struct{}
}

// MockatxsDataMockRecorder is the mock recorder for MockatxsData.
type MockatxsDataMockRecorder struct {
	mock *MockatxsData
}

// NewMockatxsData creates a new mock instance.
func NewMockatxsData(ctrl *gomock.Controller) *MockatxsData { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockatxsData) EXPECT() *MockatxsDataMockRecorder {
	_ = "STUB: not implemented"

	// Get mocks base method.
	return nil
}

func (m *MockatxsData) Get(arg0 types.EpochID, arg1 types.ATXID) *atxsdata.ATX {
	_ = "STUB: not implemented"
	return nil
}

// Get indicates an expected call of Get.
func (mr *MockatxsDataMockRecorder) Get(arg0, arg1 any) *MockatxsDataGetCall {
	_ = "STUB: not implemented"
	return nil
}

// MockatxsDataGetCall wrap *gomock.Call
type MockatxsDataGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockatxsDataGetCall) Return(arg0 *atxsdata.ATX) *MockatxsDataGetCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockatxsDataGetCall) Do(f func(types.EpochID, types.ATXID) *atxsdata.ATX) *MockatxsDataGetCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockatxsDataGetCall) DoAndReturn(f func(types.EpochID, types.ATXID) *atxsdata.ATX) *MockatxsDataGetCall {
	_ = "STUB: not implemented"
	return nil
}

// GetByEpochAndNodeID mocks base method.
func (m *MockatxsData) GetByEpochAndNodeID(arg0 types.EpochID, arg1 types.NodeID) (types.ATXID, *atxsdata.ATX) {
	_ = "STUB: not implemented"
	return *new(types.ATXID), nil
}

// GetByEpochAndNodeID indicates an expected call of GetByEpochAndNodeID.
func (mr *MockatxsDataMockRecorder) GetByEpochAndNodeID(arg0, arg1 any) *MockatxsDataGetByEpochAndNodeIDCall {
	_ = "STUB: not implemented"
	return nil
}

// MockatxsDataGetByEpochAndNodeIDCall wrap *gomock.Call
type MockatxsDataGetByEpochAndNodeIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockatxsDataGetByEpochAndNodeIDCall) Return(arg0 types.ATXID, arg1 *atxsdata.ATX) *MockatxsDataGetByEpochAndNodeIDCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockatxsDataGetByEpochAndNodeIDCall) Do(f func(types.EpochID, types.NodeID) (types.ATXID, *atxsdata.ATX)) *MockatxsDataGetByEpochAndNodeIDCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockatxsDataGetByEpochAndNodeIDCall) DoAndReturn(f func(types.EpochID, types.NodeID) (types.ATXID, *atxsdata.ATX)) *MockatxsDataGetByEpochAndNodeIDCall {
	_ = "STUB: not implemented"
	return nil
}
