// Code generated by MockGen. DO NOT EDIT.
// Source: ./sync.go
//
// Generated by this command:
//
//	mockgen -typed -package=mocks -destination=./mocks/mocks.go -source=./sync.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	time "time"

	p2p "github.com/spacemeshos/go-spacemesh/p2p"
	gomock "go.uber.org/mock/gomock"
)

// MockTime is a mock of Time interface.
type MockTime struct {
	ctrl     *gomock.Controller
	recorder *MockTimeMockRecorder
	isgomock struct{}
}

// MockTimeMockRecorder is the mock recorder for MockTime.
type MockTimeMockRecorder struct {
	mock *MockTime
}

// NewMockTime creates a new mock instance.
func NewMockTime(ctrl *gomock.Controller) *MockTime { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTime) EXPECT() *MockTimeMockRecorder {
	_ = "STUB: not implemented"

	// Now mocks base method.
	return nil
}

func (m *MockTime) Now() time.Time { _ = "STUB: not implemented"; return *new(time.Time) }

// Now indicates an expected call of Now.
func (mr *MockTimeMockRecorder) Now() *MockTimeNowCall { _ = "STUB: not implemented"; return nil }

// MockTimeNowCall wrap *gomock.Call
type MockTimeNowCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTimeNowCall) Return(arg0 time.Time) *MockTimeNowCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockTimeNowCall) Do(f func() time.Time) *MockTimeNowCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTimeNowCall) DoAndReturn(f func() time.Time) *MockTimeNowCall {
	_ = "STUB: not implemented"
	return nil
}

// MockgetPeers is a mock of getPeers interface.
type MockgetPeers struct {
	ctrl     *gomock.Controller
	recorder *MockgetPeersMockRecorder
	isgomock struct{}
}

// MockgetPeersMockRecorder is the mock recorder for MockgetPeers.
type MockgetPeersMockRecorder struct {
	mock *MockgetPeers
}

// NewMockgetPeers creates a new mock instance.
func NewMockgetPeers(ctrl *gomock.Controller) *MockgetPeers { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgetPeers) EXPECT() *MockgetPeersMockRecorder {
	_ = "STUB: not implemented"

	// GetPeers mocks base method.
	return nil
}

func (m *MockgetPeers) GetPeers() []p2p.Peer { _ = "STUB: not implemented"; return nil }

// GetPeers indicates an expected call of GetPeers.
func (mr *MockgetPeersMockRecorder) GetPeers() *MockgetPeersGetPeersCall {
	_ = "STUB: not implemented"
	return nil
}

// MockgetPeersGetPeersCall wrap *gomock.Call
type MockgetPeersGetPeersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockgetPeersGetPeersCall) Return(arg0 []p2p.Peer) *MockgetPeersGetPeersCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockgetPeersGetPeersCall) Do(f func() []p2p.Peer) *MockgetPeersGetPeersCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockgetPeersGetPeersCall) DoAndReturn(f func() []p2p.Peer) *MockgetPeersGetPeersCall {
	_ = "STUB: not implemented"
	return nil
}
