// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -typed -package=wire -destination=./mocks.go -source=./interface.go
//

// Package wire is a generated GoMock package.
package wire

import (
	context "context"

	scale "github.com/spacemeshos/go-scale"
	types "github.com/spacemeshos/go-spacemesh/common/types"
	signing "github.com/spacemeshos/go-spacemesh/signing"
	gomock "go.uber.org/mock/gomock"
)

// MockMalfeasanceValidator is a mock of MalfeasanceValidator interface.
type MockMalfeasanceValidator struct {
	ctrl     *gomock.Controller
	recorder *MockMalfeasanceValidatorMockRecorder
	isgomock struct{}
}

// MockMalfeasanceValidatorMockRecorder is the mock recorder for MockMalfeasanceValidator.
type MockMalfeasanceValidatorMockRecorder struct {
	mock *MockMalfeasanceValidator
}

// NewMockMalfeasanceValidator creates a new mock instance.
func NewMockMalfeasanceValidator(ctrl *gomock.Controller) *MockMalfeasanceValidator {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMalfeasanceValidator) EXPECT() *MockMalfeasanceValidatorMockRecorder {
	_ = "STUB: not implemented"

	// IdentityExists mocks base method.
	return nil
}

func (m *MockMalfeasanceValidator) IdentityExists(nodeID types.NodeID) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// IdentityExists indicates an expected call of IdentityExists.
func (mr *MockMalfeasanceValidatorMockRecorder) IdentityExists(nodeID any) *MockMalfeasanceValidatorIdentityExistsCall {
	_ = "STUB: not implemented"
	return nil
}

// MockMalfeasanceValidatorIdentityExistsCall wrap *gomock.Call
type MockMalfeasanceValidatorIdentityExistsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMalfeasanceValidatorIdentityExistsCall) Return(arg0 bool, arg1 error) *MockMalfeasanceValidatorIdentityExistsCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockMalfeasanceValidatorIdentityExistsCall) Do(f func(types.NodeID) (bool, error)) *MockMalfeasanceValidatorIdentityExistsCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMalfeasanceValidatorIdentityExistsCall) DoAndReturn(f func(types.NodeID) (bool, error)) *MockMalfeasanceValidatorIdentityExistsCall {
	_ = "STUB: not implemented"
	return nil
}

// PostIndex mocks base method.
func (m *MockMalfeasanceValidator) PostIndex(ctx context.Context, smesherID types.NodeID, commitment types.ATXID, post *types.Post, challenge []byte, numUnits uint32, idx int) error {
	_ = "STUB: not implemented"
	return nil
}

// PostIndex indicates an expected call of PostIndex.
func (mr *MockMalfeasanceValidatorMockRecorder) PostIndex(ctx, smesherID, commitment, post, challenge, numUnits, idx any) *MockMalfeasanceValidatorPostIndexCall {
	_ = "STUB: not implemented"
	return nil
}

// MockMalfeasanceValidatorPostIndexCall wrap *gomock.Call
type MockMalfeasanceValidatorPostIndexCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMalfeasanceValidatorPostIndexCall) Return(arg0 error) *MockMalfeasanceValidatorPostIndexCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockMalfeasanceValidatorPostIndexCall) Do(f func(context.Context, types.NodeID, types.ATXID, *types.Post, []byte, uint32, int) error) *MockMalfeasanceValidatorPostIndexCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMalfeasanceValidatorPostIndexCall) DoAndReturn(f func(context.Context, types.NodeID, types.ATXID, *types.Post, []byte, uint32, int) error) *MockMalfeasanceValidatorPostIndexCall {
	_ = "STUB: not implemented"
	return nil
}

// Signature mocks base method.
func (m_2 *MockMalfeasanceValidator) Signature(d signing.Domain, nodeID types.NodeID, m []byte, sig types.EdSignature) bool {
	_ = "STUB: not implemented"
	return false
}

// Signature indicates an expected call of Signature.
func (mr *MockMalfeasanceValidatorMockRecorder) Signature(d, nodeID, m, sig any) *MockMalfeasanceValidatorSignatureCall {
	_ = "STUB: not implemented"
	return nil
}

// MockMalfeasanceValidatorSignatureCall wrap *gomock.Call
type MockMalfeasanceValidatorSignatureCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMalfeasanceValidatorSignatureCall) Return(arg0 bool) *MockMalfeasanceValidatorSignatureCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockMalfeasanceValidatorSignatureCall) Do(f func(signing.Domain, types.NodeID, []byte, types.EdSignature) bool) *MockMalfeasanceValidatorSignatureCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMalfeasanceValidatorSignatureCall) DoAndReturn(f func(signing.Domain, types.NodeID, []byte, types.EdSignature) bool) *MockMalfeasanceValidatorSignatureCall {
	_ = "STUB: not implemented"
	return nil
}

// MockProof is a mock of Proof interface.
type MockProof struct {
	ctrl     *gomock.Controller
	recorder *MockProofMockRecorder
	isgomock struct{}
}

// MockProofMockRecorder is the mock recorder for MockProof.
type MockProofMockRecorder struct {
	mock *MockProof
}

// NewMockProof creates a new mock instance.
func NewMockProof(ctrl *gomock.Controller) *MockProof { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProof) EXPECT() *MockProofMockRecorder {
	_ = "STUB: not implemented"

	// AllowNoRefATXs mocks base method.
	return nil
}

func (m *MockProof) AllowNoRefATXs() bool { _ = "STUB: not implemented"; return false }

// AllowNoRefATXs indicates an expected call of AllowNoRefATXs.
func (mr *MockProofMockRecorder) AllowNoRefATXs() *MockProofAllowNoRefATXsCall {
	_ = "STUB: not implemented"
	return nil
}

// MockProofAllowNoRefATXsCall wrap *gomock.Call
type MockProofAllowNoRefATXsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProofAllowNoRefATXsCall) Return(arg0 bool) *MockProofAllowNoRefATXsCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockProofAllowNoRefATXsCall) Do(f func() bool) *MockProofAllowNoRefATXsCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProofAllowNoRefATXsCall) DoAndReturn(f func() bool) *MockProofAllowNoRefATXsCall {
	_ = "STUB: not implemented"
	return nil
}

// DecodeScale mocks base method.
func (m *MockProof) DecodeScale(dec *scale.Decoder) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// DecodeScale indicates an expected call of DecodeScale.
func (mr *MockProofMockRecorder) DecodeScale(dec any) *MockProofDecodeScaleCall {
	_ = "STUB: not implemented"
	return nil
}

// MockProofDecodeScaleCall wrap *gomock.Call
type MockProofDecodeScaleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProofDecodeScaleCall) Return(arg0 int, arg1 error) *MockProofDecodeScaleCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockProofDecodeScaleCall) Do(f func(*scale.Decoder) (int, error)) *MockProofDecodeScaleCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProofDecodeScaleCall) DoAndReturn(f func(*scale.Decoder) (int, error)) *MockProofDecodeScaleCall {
	_ = "STUB: not implemented"
	return nil
}

// EncodeScale mocks base method.
func (m *MockProof) EncodeScale(enc *scale.Encoder) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// EncodeScale indicates an expected call of EncodeScale.
func (mr *MockProofMockRecorder) EncodeScale(enc any) *MockProofEncodeScaleCall {
	_ = "STUB: not implemented"
	return nil
}

// MockProofEncodeScaleCall wrap *gomock.Call
type MockProofEncodeScaleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProofEncodeScaleCall) Return(arg0 int, arg1 error) *MockProofEncodeScaleCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockProofEncodeScaleCall) Do(f func(*scale.Encoder) (int, error)) *MockProofEncodeScaleCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProofEncodeScaleCall) DoAndReturn(f func(*scale.Encoder) (int, error)) *MockProofEncodeScaleCall {
	_ = "STUB: not implemented"
	return nil
}

// Info mocks base method.
func (m *MockProof) Info() map[string]string { _ = "STUB: not implemented"; return nil }

// Info indicates an expected call of Info.
func (mr *MockProofMockRecorder) Info() *MockProofInfoCall { _ = "STUB: not implemented"; return nil }

// MockProofInfoCall wrap *gomock.Call
type MockProofInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProofInfoCall) Return(arg0 map[string]string) *MockProofInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockProofInfoCall) Do(f func() map[string]string) *MockProofInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProofInfoCall) DoAndReturn(f func() map[string]string) *MockProofInfoCall {
	_ = "STUB: not implemented"
	return nil
}

// Type mocks base method.
func (m *MockProof) Type() ProofType { _ = "STUB: not implemented"; return *new(ProofType) }

// Type indicates an expected call of Type.
func (mr *MockProofMockRecorder) Type() *MockProofTypeCall { _ = "STUB: not implemented"; return nil }

// MockProofTypeCall wrap *gomock.Call
type MockProofTypeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProofTypeCall) Return(arg0 ProofType) *MockProofTypeCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockProofTypeCall) Do(f func() ProofType) *MockProofTypeCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProofTypeCall) DoAndReturn(f func() ProofType) *MockProofTypeCall {
	_ = "STUB: not implemented"
	return nil
}

// TypeName mocks base method.
func (m *MockProof) TypeName() string { _ = "STUB: not implemented"; return "" }

// TypeName indicates an expected call of TypeName.
func (mr *MockProofMockRecorder) TypeName() *MockProofTypeNameCall {
	_ = "STUB: not implemented"
	return nil
}

// MockProofTypeNameCall wrap *gomock.Call
type MockProofTypeNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProofTypeNameCall) Return(arg0 string) *MockProofTypeNameCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockProofTypeNameCall) Do(f func() string) *MockProofTypeNameCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProofTypeNameCall) DoAndReturn(f func() string) *MockProofTypeNameCall {
	_ = "STUB: not implemented"
	return nil
}

// Valid mocks base method.
func (m *MockProof) Valid(ctx context.Context, malHandler MalfeasanceValidator) (types.NodeID, error) {
	_ = "STUB: not implemented"
	return *new(types.NodeID), nil
}

// Valid indicates an expected call of Valid.
func (mr *MockProofMockRecorder) Valid(ctx, malHandler any) *MockProofValidCall {
	_ = "STUB: not implemented"
	return nil
}

// MockProofValidCall wrap *gomock.Call
type MockProofValidCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProofValidCall) Return(arg0 types.NodeID, arg1 error) *MockProofValidCall {
	_ = "STUB: not implemented"
	return nil
}

// Do rewrite *gomock.Call.Do
func (c *MockProofValidCall) Do(f func(context.Context, MalfeasanceValidator) (types.NodeID, error)) *MockProofValidCall {
	_ = "STUB: not implemented"
	return nil
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProofValidCall) DoAndReturn(f func(context.Context, MalfeasanceValidator) (types.NodeID, error)) *MockProofValidCall {
	_ = "STUB: not implemented"
	return nil
}
