// Code generated by github.com/spacemeshos/go-scale/scalegen. DO NOT EDIT.

// nolint
package wire

import (
	"github.com/spacemeshos/go-scale"
)

func (t *ActivationTxV1) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *ActivationTxV1) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *InnerActivationTxV1) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *InnerActivationTxV1) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *PostV1) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *PostV1) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *MerkleProofV1) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *MerkleProofV1) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *NIPostV1) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *NIPostV1) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *PostMetadataV1) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *PostMetadataV1) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *ATXMetadataV1) EncodeScale(enc *scale.Encoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (t *ATXMetadataV1) DecodeScale(dec *scale.Decoder) (total int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}
